### ISSUE TITLE
Creation of thumbnails/previews fails for new hi-res pics NC 23

### ISSUE THREAD

**Issue by hul51u** [nextcloud/photos#1088]
**Describe the bug**
For hi-resolution pics with >30Mpx NC fails to create thumbnails or previews for new photos.
This bug has been existing since I upgraded to NC 23.0.4 with photos 1.5.0 und viewer 1.7.0.
Older pics with this resolution can still be viewed. (I guess because thumbnails and previews already had been created and are chached.) With older NC versions there was no such problem.

**To Reproduce**
1. Upload a pic with >30Mpx
2. Creating Thumbnail und preview image fails. "Fehler beim Laden von ...."

**System Configurations**
* Upgraded to 23.0.4 via web
* Photos 1.5.0
* viewer 1.7.0

**Expected behavior**
Thumbnails and preview image should be created as in older NC instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/78090961/165289849-76eccbd9-7c63-4b95-9a22-49258d8e6d42.png)

**Desktop (please complete the following information):**
 - No problem with desktop clients...

**Smartphone (please complete the following information):**
 - NC app for android tells that there was no preview image but works if I download the file.

**Additional context**
You can try to import this image to your NC instance:
![MHG_6173](https://user-images.githubusercontent.com/78090961/165290272-515bf934-a71b-470d-8803-6fba412a965b.jpg)

**Comment by skjnldsv** [comment]
Please find the related error in your nextcloud log and paste it here :)
What's your max preview config?
Are you using imagick?
What setup to you have? Docker? Bare os install?

**Comment by hul51u** [comment]
* Nextcloud Log:
{"reqId":"XXXXXXXXXXXX","level":3,"time":"2022-04-26T20:26:29+00:00","remoteAddr":"XXXXXXXXXX","user":"XXXXXXXX","app":"core","method":"GET","url":"/index.php/core/preview?fileId=368011&x=1920&y=1080&a=true","message":"OC_Image::fixOrientation(): No image loaded","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1","id":"XXXXXXXXXX"}



* Max preview config: no entry in my config.php, I guess then... default value?
* imagick: Yes, I use imagick
* My setup: Ubuntu 20 with apache2, no docker, everything up to date
* My php memory limit is 3GB
* "All checks passed." @ Security & setup warnings @ Overview @ Admin-NC-User

**Comment by szaimen** [comment]
I suppose this is a duplicate of https://github.com/nextcloud/server/issues/31284

**Comment by hul51u** [comment]
> I suppose this is a duplicate of [nextcloud/server#31284](https://github.com/nextcloud/server/issues/31284)

Yes it is.

**Comment by PatRiot1337** [comment]
Haha, I have the same problem. So is there already someone working on a solution?

Took me a looong while finding out the resolution is causing this problem.... lol
thanks again at ❓️❓️❓️wat💸⛩️☯︎❓️❓️❓️for helping me ;)
