### ISSUE TITLE
Rename Photos App to Media App

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/photos#1108]
The app offers the same functions for images as for videos and should therefore not be named after a sub-function of the app. (Probably the app has evolved and was previously made only for photos!?)

But explain to the users why they should search for videos in the photos app.

**Comment by umgfoin** [comment]
This is not a bug.

**Comment by delacosta456** [comment]
hi
i second this request too . It could avoid confusion between the app link on left tab and a predefined photo folder (unless you change the default skeleton. all nextcloud user doesn't necessary know how to dill with skeleton)

And if possible make it possible to also set the path to video folder.
Thanks
