### ISSUE TITLE
External storage media is no longer shown with Nextcloud 24.0.x

### ISSUE THREAD

**Issue by Moltey** [nextcloud/photos#1111]
# Settings
- I installed a containerized Nextcloud setup, starting version 23.x. Among others, I run two containers of Nextcloud:
-- Nextcloud App
-- Nextcloud Cron
- An external storage from the host is passed through to both containers.
- Access to the external storage works fine. Previews are shown when accessing a folder.

# Observation
- The photos app running on Nextcloud _23_.x identifies and shows media on the external storage.
- The photos app running on Nextcloud _24_.x _does not_ identify and show media on the external storage. All media identified running NC 23 is no longer shown.
- The photos app running on Nextcloud _24_.x identifies and shows media on the "internal" storage managed by Nextcloud.

# Expectation
- Nextcloud  2**4**.x should show media on the external storage as experienced with Nextcloud 2**3**.x (I did not change any configuration).

# Request
Any ideas how to persuade Nextcloud _24_ to identify and show media in the photos app, again?

**Comment by skjnldsv** [comment]
@icewind1991 did we change anything regarding files search?

**Comment by Moltey** [comment]
BTW: New files saved on the external storage are correctly identified by the "Files" app and shown on the "Recent" menu.

**Comment by Limoniak** [comment]
same problem for me

**Comment by marianionut** [comment]
I have the same issue with NextCloud version 24.0.1, everything worked well before the upgrade.
I'm using an SSD external storage mounted inside the VM, in the Photos section I used to see all my photos and now I can see only the internal ones.
