### ISSUE TITLE
NC 24 UI slow to react to user actions

### ISSUE THREAD

**Issue by eibex** [nextcloud/photos#1126]
**Describe the bug**
Since updating to NC 24, the UI slow to react to user actions (e.g. clicks, arrow key presses), with delays of up to ~5 seconds.

**To Reproduce**
1. Go to the photos app
2. Click on anything

**Expected behavior**
The interface is snappy just like the rest of Nextcloud.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 103

**Browser log**
```
SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://cloud.example.com/') with script ('https://cloud.example.com/apps/photos/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
(anonymous) @ Photos.vue:116
```

**Additional context**
This happens when clicking on photos, using arrow keys to view another picture, clicking on UI elements such as the "X" to close the viewer.

I don't think the error is related to this issue since it only shows once.

This issue usually goes away when reloading the page, only to return after browsing for a few seconds. I don't see excessive memory or CPU usage on the server or client.

**Comment by skjnldsv** [comment]
Should be fixed in upcoming releases. It might be because of the infinite loading.


Btw, please make sure your webserver config is proper (see our documentation)
This should be served properly.

> ```
> SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://cloud.example.com/[](https://cloud.example.com/)') with script ('https://cloud.example.com/apps/photos/service-worker.js[](https://cloud.example.com/apps/photos/service-worker.js)'): A bad HTTP response code (404) was received when fetching the script.
> (anonymous) @ Photos.vue:116
> ```

**Comment by eibex** [comment]
> This should be served properly.
The file exists, I am not sure why it throws a 404. Related to #606 ?

**Comment by kozfelipe** [comment]
still present on docker version of nextcloudpi 25.0.3
