### ISSUE TITLE
[BITV/A11Y] Title not updating when changing sections in navigation

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/photos#1137]
Steps to reproduce:

Open Photos app (also on c.nc.com)
Click on the "Videos" section on the left
Expected result: document title also says "Videos - Nextcloud" or "Videos - Photos - Nextcloud".

Actual result: document title always stays on"Photos - Nextcloud"

**Comment by PVince81** [comment]
@skjnldsv can you maybe check this one ?

**Comment by JuliaKirschenheuter** [comment]
@AndyScherzinger , @PVince81 Could you please post some screenshots / video captures?

**Comment by PVince81** [comment]
@JuliaKirschenheuter steps to reproduce:

1. Open Photos app (also on c.nc.com)
2. Click on the "Videos" section on the left

Expected result: document title also says "Videos - Nextcloud" or "Videos - Photos - Nextcloud".

Actual result: document title always stays on"Photos - Nextcloud"
