### ISSUE TITLE
Still looking for a successor to the app Gallery.

### ISSUE THREAD

**Issue by GitWidi** [nextcloud/photos#1140]
I continue to use the app Gallery because I want to share photo albums with other people via a public link. 
I find the presentation of the photo albums in the app Gallery very successful, especially the design options via the file gallery.cnf. 

Until NC V23 you could install this app without any problems (see for example https://help.nextcloud.com/t/discussion-new-photo-app-in-nextcloud-18/69949/20).
Since NC V24, however, the full-screen display of the images no longer works. If you click on a picture in the photo album, you only get a black screen. 

Does anyone have a suggestion on how to solve this? 
Or does anyone know a good representation of photo albums for the app Photos?

Regards, Friedbert

**Comment by marcelm** [comment]
I just found out how to get Gallery to work on NC 24. In short, open `apps/gallery/templates/slideshow.php` and change line 23 from

    <div class="progress icon-pause icon-shadow icon-white icon-32"/>

to

    <div class="progress icon-pause icon-shadow icon-white icon-32"></div>

This is of course in addition to the other changes (`purify.js` etc.).

[Background](https://www.reddit.com/r/NextCloud/comments/qmsoqg/comment/iij7jtd/?utm_source=share&utm_medium=web2x&context=3)

**Comment by GitWidi** [comment]
> I just found out how to get Gallery working on NC 24. ... 

Hello Marcel, 
thank you very much, your bugfix works! I agree with the opinion of onymousbosch: you are a hero!

Nevertheless, I would appreciate it very much if such a presentation would be supported in the app Photos.

**Comment by marcelm** [comment]
Glad I could help! Agree with your request, would be great if Photos could become a proper replacement.

**Comment by skjnldsv** [comment]
Hey, thanks for the assistance here Marcel!
While it's great that people are still interested in the old gallery, this is not really the place to discuss, the forum would be much more fitting. We won't give help to help you get usage on something we are no longer supporting. We just don'thave enough time and focus for that :see_no_evil: 
I hope you will understand! :hugs: 

Have a great day both of you! :sunflower:
