### ISSUE TITLE
"Your photos" and "Your videos"  also display shared photos and videos

### ISSUE THREAD

**Issue by RobMahn** [nextcloud/photos#1141]
"Your photos" and "Your videos"  also display shared photos and videos.

**Expected behavior**
I expected to see only my own photos and videos.

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 103.0.5060.134

**Comment by joshtrichards** [comment]
Not able to reproduce this. Are you still experiencing this?

**Comment by RobMahn** [comment]
I can no longer reproduce this.
