### ISSUE TITLE
Hidden files and folders are displayed

### ISSUE THREAD

**Issue by RobMahn** [nextcloud/photos#1156]
**Describe the bug**
Photos displays hidden files.

**To Reproduce**
1. Add a hidden photo file.  e.g. Add a "." to the beginning of the file name.
2. Go to the Photos view.
3. The file is still displayed.
4. There is no option to view / not view hidden files.

My condition is that I'm using Resilio Sync to have a two way sync from my Android phone.  This syncs the phones ".trashed-* and .pending-* files.

**Expected behavior**
Hidden files should not be displayed, unless an option is added to display them.

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome

**Comment by skjnldsv** [comment]
Hi, which version of Nextcloud? :)

**Comment by RobMahn** [comment]
Nextcloud 24.0.4
... sorry for the omission.

**Comment by joshtrichards** [comment]
Duplicate of #1061.
