### ISSUE TITLE
Re-use Navigation for Timeline and Albums

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#1192]
This creates lots of css duplicates and lack a standard.
This is why we had the `Navigation` component, I think we should reuse that and adapt it so the design is the same accross all views and remove code duplicates.

https://github.com/nextcloud/photos/blob/dbe72c433de0cc4b17972dd6d9a123c8c930b574/src/views/Timeline.vue#L32-L94
https://github.com/nextcloud/photos/blob/dbe72c433de0cc4b17972dd6d9a123c8c930b574/src/views/Albums.vue#L30-L41
https://github.com/nextcloud/photos/blob/a1fa11f1ef1d5f734a91e30305f3a10f574d3675/src/views/AlbumContent.vue#L39-L116

cc @artonge

**Comment by artonge** [comment]
Closed by https://github.com/nextcloud/photos/pull/1224
