### ISSUE TITLE
[Bug]: NC 25 Failed to fetch albums lists 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1197]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/59488153/188194507-dc1a9293-fca5-4c9d-ac47-4fc5c1e0bda2.png)

### Steps to reproduce

Click on photos tab
Albums

### Expected behavior

.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by andyxheli** [comment]
Still an issue on NC 25 Beta 5

**Comment by andyxheli** [comment]
Still an issue on NC 25 Beta  @skjnldsv I know your super busy. when you have a chance can you please have someone look into this ?

**Comment by andyxheli** [comment]
[Web Console Logs.log](https://github.com/nextcloud/photos/files/9538047/Web.Console.Logs.log)

**Comment by skjnldsv** [comment]
Please share your nextcloud log and I will need a screenshot of your network requests.

Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by andyxheli** [comment]
Hi @skjnldsv 
Here's a screenshot of what you asked for and im not seeing any errors in the nextcloud logs only web con logs what i attached  above

![image](https://user-images.githubusercontent.com/59488153/189485889-d7d96ffc-cf83-4ea1-a61d-81f217be6b92.png)

**Comment by skjnldsv** [comment]
@andyxheli can you expand the last red error in the console please? :)

**Comment by andyxheli** [comment]
HI @skjnldsv here you go :) 

![image](https://user-images.githubusercontent.com/59488153/190651078-bb177540-d9b3-4803-b39c-a61c88b9f1f2.png)

**Comment by andyxheli** [comment]
@skjnldsv NO sure if anything changed but in NC 25 Beta 7 looks like the Albums are now working 

![image](https://user-images.githubusercontent.com/59488153/191090931-b04f786e-a803-4900-8f21-9daa92f7ba2e.png)

**Comment by nicrame** [comment]
I got same problem on every NC25, from beta 4 to RC 5.
