### ISSUE TITLE
Video thumbnails

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/photos#12]
Is it possible to show video thumbnails?

**Comment by jancborchardt** [comment]
As it is focused on media viewing, we should probably show video thumbnails? @jakobroehrl can you find out if and how Gallery or the Files grid view do it?

cc @rullzer for reference maybe

**Comment by rullzer** [comment]
We don't do this in files either. There is a preview provider that generates a picture. That is about it.

**Comment by jakobroehrl** [comment]
@rullzer With "preview provider" you mean https://github.com/rullzer/previewgenerator right?
Maybe we should give a hint for the admin user to install the previewgenerator?

It would be awesome if the video plays on mouseover like here eg: https://pixabay.com/videos/

**Comment by skjnldsv** [comment]
> It would be awesome if the video plays on mouseover like here eg: [pixabay.com/videos](https://pixabay.com/videos/)

That is a very different feature, please open a new issue about this :)
Regarding the preview, if there is a preview provider (any that generate some for videos) they will shwo ;)

**Comment by tacruc** [comment]
I will post here, as I think the issue is quite related.

If the video preview provider is enabled, it is impossible to tell which Thumbnail is from an video and which one is a picture.
Maybe a small play Icon cloud be shown above the video thumbnail.
