### ISSUE TITLE
Add albums feature and separate "folders" from "albums"

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/photos#120]
At the moment pictures need to physically be into the same folder to form a shareable collection. In my opinion, the current 'albums' navigation item should be called 'folders' as it provides a nicer way to browse photos in the folder structure, but aside from that It would be nice to be able to create any number of shareable collections of pictures (albums) without having to duplicate them in different folders.

This is how the menu would look like: 

* photos
* folders
* albums
* shared albums
* tagged photos
* location

**Comment by Mikescops** [comment]
It's a good idea (maybe Timeline instead of Photos) but this is related to #6 and #84 too.

**Comment by ma12-co** [comment]
cc @nextcloud/designers

**Comment by kaffeeringe** [comment]
I miss the old handling of folders. It was everythiny but perfect, but at least I was able to navigate it. 
Shotwell sorts all photos into folders of years, months and days. In Nextcloud it's now just 1 gazillion folders with numbers as names. And too many for previews to render...

**Comment by jancborchardt** [comment]
> It would be nice to be able to create any number of shareable collections of pictures (albums) without having to duplicate them in different folders.

Absolutely agree. It should be possible to select pictures and add them to "virtual" albums. We need to get a bit away from the filesystem paradigm here.

However, before we do this we should make sure we can integrate this with the mobile apps for feature parity, cc @tobiasKaminsky @marinofaggiana @AndyScherzinger.

**Comment by tobiasKaminsky** [comment]
This needs some real deep thinking, adding a "virtual" structure on top of existing folder structure is a big challenge, both UX and tech-wise.

**Comment by skjnldsv** [comment]
Yep :/
If we go for this, better drop the folder structure entirely and suggest marking all folder content as a single album instead. Also, we'd lose compatibility with other photos app I assume? Android is folderbased, no idea for iPhotos. But I ideally, opening your nextcloud data in iPhotos should also display your albums.

**Comment by kaffeeringe** [comment]
Please keep in mind that people already have hundreds of Photos in their Nextcloud.
The normal folders are not a replacement, because folders don't have a preview there. It's pretty hard to find certain photos within a complex folder structure.

**Comment by tobiasKaminsky** [comment]
To not make this too complicated, I suggest to first find a good way within this photo app.
Then it should be somehow integrated into NC server, and then we can think about integration into clients.

For now I always understood the photo app as a different view onto photos in NC, with the same hierarchy of folders.
If this has now changed, it does not mean necessarily that there needs to be a change on server/clients.

**Comment by tobiasKaminsky** [comment]
EDIT:
On Android we have the "photo" tab, which "only" lists images from new -> old.
If any, I guess we can try to do something there…

**Comment by ma12-co** [comment]
> both UX and tech-wise.

@tobiasKaminsky  I don't think that it would be a challenge UX-wise as we already have many of examples of photo apps that do just that. It's common sense by now that creating an album in a photo app means selecting an arbitrary set of pictures from whatever location.

> better drop the folder structure entirely and suggest marking all folder content as a single album instead.

@skjnldsv  What do you mean with this? 

> Android is folderbased.

I think that as a benchmark here we should look at google photos, not at the standard android gallery app.

**Comment by skjnldsv** [comment]
> I think that as a benchmark here we should look at google photos, not at the standard android gallery app.

what about iOS photos? And macOS photos?

**Comment by marinofaggiana** [comment]
Before this beautiful feature will be better write API for manage (and select) from server the photo. client-side API are inefficient.

**Comment by skjnldsv** [comment]
API discussion in #205
@marinofaggiana we have an api for albums & shared albums already :)
For the timeline we're using the new (18) improved DAV search

**Comment by Spartachetto** [comment]
Maybe I am "late for the party", as this issue is not so new, yet from reading #6 and #84 I had thought that this app was a way to make possible an **old** feature request....

Have a look at https://github.com/nextcloud/gallery/issues/116 , https://github.com/nextcloud/gallery/issues/121 , https://github.com/nextcloud/gallery/issues/463 
All of them ask for a way of having the option of visualizing photos by tag. Or, even better, by metadata (tag/tags, GPS coordinates, EXIF, 
...).

In addition consider that also the request of **adding** tags via the "visualization tool" (gallery or photos) is old: https://github.com/nextcloud/gallery/issues/153 , https://github.com/nextcloud/gallery/issues/204

**Comment by dlauper** [comment]
Try e last few days/weeks I thought a lot about what to expect from a photos app, and the separation of folders and albums is also something I would appreciate. 
I started a "discussion" over at the [Nextcloud forum](https://help.nextcloud.com/t/ideas-for-revolutionary-photo-organization/89278)  (no answers yet) of how to handle file structure and albums, amongst others. Maybe the ideas visualized in the drafts could be some inspiration here?

**Comment by knuxify** [comment]
IMO we should leave folders as-is and make "albums" lists of files contained in a separate database (possibly related to the proposal in #84), with an option to generate an album from a folder, then separate the folder view and album view in the UI. That way we keep compatibility with old apps that use folders and add a new way to group albums for newer apps.

**Comment by Mikescops** [comment]
Fixed by #457

**Comment by strugee** [comment]
Reopening since the albums feature still needs to be added (#457 was just a rename).

**Comment by Mikescops** [comment]
It's a separate issue and described earlier #84, please leave this one closed.

**Comment by strugee** [comment]
Forgot about that one, thanks. Sorry for the spam!
