### ISSUE TITLE
NC 25 photos not scrolling on mobile devices

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1202]
Go into photos tab scroll down nothing happens 

Please see video

https://user-images.githubusercontent.com/59488153/188273635-32750b95-1f7b-4a60-a14a-9d2894b69a07.mp4

**Comment by andyxheli** [comment]
Fixed in NC 25 Beta 5

**Comment by marcelklehr** [comment]
Thanks for reporting!
