### ISSUE TITLE
app takes long time to load (>5 min) with large set of pictures

### ISSUE THREAD

**Issue by sfabel** [nextcloud/photos#1222]
**Describe the bug**
I am using Nextcloud to store all of my photos. Currently, there are 127 GB of photos in total, each one ~9 MB large. I do have the preview-generator app installed, and have run the generation of the previews manually prior to opening the app. When I do, I only see a spinning 'circle' for roughly 4-5 minutes before it loads the first set of dozen pictures. It keeps spinning below this.

Server load seems reasonable (2.5 on 4 core), memory does not seem exhausted. PHP memory limit is set to 2048M. HTTP compression is turned ON (but the behavior also occurred with it turned OFF).

This behavior did seem to get worse over time, especially once I started uploading pictures from my actual camera rather than from my phone, i.e., once the filesize of the individual photo increased.

**To Reproduce**
1. Open the Photos app.
2. Watch the circle spin.

**Expected behavior**
Quick rendering of previews and show the photos without having to wait a long time.

**Desktop (please complete the following information):**
 - OS: Nextcloud 24.0.3snap1 running on Ubuntu 20.04, Laptop is a Macbook Pro.
 - Browser: Firefox (but behavior is the same under Safari and Chrome).
 - Version: FF 104.0.2 (64-bit)

**Comment by skjnldsv** [comment]
Fixed in latest beta, we reduced the amount of files loaded
