### ISSUE TITLE
NC 25 Upload Media via photos not working

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1230]
**Describe the bug**

**To Reproduce**
1. Go to Photos
2. Click on + Add
3. Select Upload Media

https://user-images.githubusercontent.com/59488153/189423509-27a2e3f6-28c8-4a68-b62f-45bf196e88ae.mp4

**Comment by skjnldsv** [comment]
Ahaha, guess we forgot to remove the placeholder while we add the final feature @artonge 
Sorry about that @andyxheli, thanks for the report.

The feature should be here next week!

**Comment by andyxheli** [comment]
@skjnldsv No problem at all! and You're welcome happy to help :) 

 Thank you!

**Comment by andyxheli** [comment]
HI @skjnldsv I'm running on NC 25 Beta 7 and now i don't see upload media anymore 

![image](https://user-images.githubusercontent.com/59488153/191090387-71b4fe0f-b362-49dd-8f14-3f2e7fc91d7e.png)

**Comment by skjnldsv** [comment]
> HI @skjnldsv I'm running on NC 25 Beta 7 and now i don't see upload media anymore
> 
> ![image](https://user-images.githubusercontent.com/59488153/191090387-71b4fe0f-b362-49dd-8f14-3f2e7fc91d7e.png)

Timeline is the last missing part :see_no_evil:

**Comment by andyxheli** [comment]
Thank you for the quick response :) Cant wait to test it out

**Comment by skjnldsv** [comment]
You should already be able to in Albums now though :)

**Comment by andyxheli** [comment]
Ahhh okay so go to albums tab at click add media not under photos > albums and add media ?
