### ISSUE TITLE
Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by blizzz** [nextcloud/photos#1260]
**Describe the bug**

An upgrade from latest 24 fails due to an Exception while Migration processing. May also happen on fresh installations.

**To Reproduce**
1. Upgrade from latest NC to latest build https://download.nextcloud.com/server/prereleases/nextcloud-25.0.0beta7.zip (not officially released)

**Expected behavior**
Upgrades runs through successfully

**Logs**

```
Updating <photos> ...
Exception: Database error when running migration 20001Date20220830131446 for app photos
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
Update failed
Maintenance mode is kept active
Resetting log level
    0/0 [--->------------------------]   0%
Error: Process completed with exit code 5.
```

from this automated build run https://github.com/nextcloud/updater_server/actions/runs/3083044439/jobs/4983518734

**Comment by nickvergessen** [comment]
Setting
https://github.com/nextcloud/photos/blob/master/lib/Migration/Version20001Date20220830131446.php#L72
to false should be enough, otherwise you need to specify a default value.

**Comment by PVince81** [comment]
a bit tricky, I'd expect "owner" to be always populated but we can't do during the migration

maybe for now we allow it to be null and @artonge can figure out a way to populate it or use a default value later

**Comment by PVince81** [comment]
PR for unblocking: https://github.com/nextcloud/photos/pull/1261

let's leave the issue open for further fixing
