### ISSUE TITLE
Unable to scroll down under add collaborators 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1271]
**To Reproduce**
1. Go to Photos
2. Click on Albums
3. Select the Share Icon on the right top
4. Click on Search people or group
![image](https://user-images.githubusercontent.com/59488153/191278227-acbb4c4f-4a79-4cbc-933d-85bd167286f0.png)

**Comment by andyxheli** [comment]
Still an issue on NC 25 RC2

**Comment by artonge** [comment]
Thanks for reporting @andyxheli,

May I ask you to try to add the CSS properties `height: 500px` and `overflow: scroll` to the pop-up content and reports if it is fixing your issue?
If so, could you make a PR ?

**Comment by artonge** [comment]
You would have to target this element: https://github.com/nextcloud/photos/blob/master/src/components/Albums/CollaboratorsSelectionForm.vue#L48
So adding the code here should work: https://github.com/nextcloud/photos/blob/master/src/components/Albums/CollaboratorsSelectionForm.vue#L352

**Comment by andyxheli** [comment]
Looks good. Please see below :) 

![image](https://user-images.githubusercontent.com/59488153/193638475-4f423c27-2d69-415f-b28f-249c00e4b7d7.png)

**Comment by artonge** [comment]
Thanks again for fixing it @andyxheli !!!

**Comment by andyxheli** [comment]
Thank you for your help !!!
