### ISSUE TITLE
Open sidebar unveils an empty panel

### ISSUE THREAD

**Issue by blizzz** [nextcloud/photos#1289]
**Describe the bug**

On NC 25, when clicking on "Open sidebar" only an empty panel appears.

**To Reproduce**
1. Go to Photos app
2. Click on a photo or video
3. Click on the ···-menu and then "Open sidebar"

**Expected behavior**

The sidebar, with contents similar as in the Files app, is being opened with an appropriate width.

**Screenshots**

![Screenshot_20220923_130502](https://user-images.githubusercontent.com/2184312/191947435-7fe29ce3-7372-426f-994c-2d39771fc293.png)

When closing the image (not the sidebar):

![Screenshot_20220923_130600](https://user-images.githubusercontent.com/2184312/191947615-d4d96c86-2998-46ed-9f62-59cfd84a1aa2.png)

A PROPFIND request that is being done results in a 404, leading JS errors about the failed request.

**Comment by HyCore** [comment]
i've the same issue right now on NC 25.0.0, my app photo version is 2.0.0
When i click on opening the lateral bar it doesn't  show anything, it only open it on the unfocused photo, and it's empty.
