### ISSUE TITLE
MOV files do not play in Firefox

### ISSUE THREAD

**Issue by meichthys** [nextcloud/photos#1293]
**Describe the bug**
This may be a Firefox issue, but I'm not able to play any .MOV files from Nextcloud (25RC):
![image](https://user-images.githubusercontent.com/10717998/192178184-8938ddbb-c188-4c6b-bdc3-18d6b08a7406.png)

Photos Version:  1.7.1

**To Reproduce**
1. [In Firefox] navigate to: Nextcloud > Photos > Videos
2. Click on a MOV video
3. Wait for video to play

**Expected behavior**
MOV files should play like any other video file.

**Screenshots**
![image](https://user-images.githubusercontent.com/10717998/192178340-d516a1ab-abf5-43f3-b6de-d23329b70443.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 105.0.1

**Browser log**
```
Media resource https://nextcloud.mydomain.com/remote.php/dav//files/me/Photos/22-09-04%2017-01-06%209170.mov could not be decoded. [photos](https://nextcloud.mydomain.com/apps/photos/)
Error loading /files/me/Photos/22-09-04 17-01-06 9170.mov 
error { target: div.plyr.plyr--full-ui.plyr--video.plyr--html5.plyr--fullscreen-enabled.plyr--paused.plyr--stopped.plyr__poster-enabled, isTrusted: false, detail: {…}, srcElement: div.plyr.plyr--full-ui.plyr--video.plyr--html5.plyr--fullscreen-enabled.plyr--paused.plyr--stopped.plyr__poster-enabled, eventPhase: 0, bubbles: true, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
```
<img width="1680" alt="Screen Shot 2022-09-25 at 9 51 43 PM" src="https://user-images.githubusercontent.com/10717998/192178627-cc39fb4a-f85f-45fc-a463-581a75753be8.png">

**Additional context**

**Comment by skjnldsv** [comment]
Hi, it depends on the codec used for your mov file.
You can see the yellow warning on your screenshot, your browser cannot handle this file :shrug:

**Comment by meichthys** [comment]
These `.mov` files are just the video portion of iOS live photos. I guess I'll try to be patient and wait for https://github.com/nextcloud/photos/issues/344

**Comment by skjnldsv** [comment]
There will never be anything we can do as long as your browser does not support decoding it unfortunately :/

**Comment by meichthys** [comment]
Mov files seem to play on other websites like Photoprism:
https://demo.photoprism.app/s/3bk3yga5vt/mov-test-in-firefox

**Comment by skjnldsv** [comment]
Move can contain multiple codecs. The issue is not about the mov format, but the codec used to record de video inside it :)

**Comment by lenaxia** [comment]
I don't think this is the case. The Memories plugin can readily play the exact same files. Can we reopen this and actually have some investigation as to why the playback fails for mov files?

Playback fails for all iOS generated videos, both live photos and regular videos
