### ISSUE TITLE
multiple errors when loading the photos app on NC25, RC1

### ISSUE THREAD

**Issue by szaimen** [nextcloud/photos#1296]
on c.nc.c (NC25, RC1):

![image](https://user-images.githubusercontent.com/42591237/192356357-18907e4d-bcc0-4bd3-82c2-a50948c32589.png)

**Comment by szaimen** [comment]
Also the first loading is very slow: takes around 20s or so to load the photos...

**Comment by skjnldsv** [comment]
Fixed
