### ISSUE TITLE
Does Photos Face Recognition interfere with Picasa/digiKams face recognition?

### ISSUE THREAD

**Issue by Id3aFly** [nextcloud/photos#1314]
Hi everybody,

this is not a bug report. I did not know where to ask this otherwise:
I just wanted to know, whether the new face recognition feature in photos 2.0 that was announced recently does interfere with the face recognition metadata saved by Digikam or Picasa  (I mean in a bad way, e.g. overwriting metadata automatically)?

Or can it even benefit from the tags stored by digikam/Picasa and reuse them?

Thank you

**Comment by Id3aFly** [comment]
Because it would be nice of course, if it would not overwrite data / add additional metadata, but instead reuses the already existing metadata of the image.

**Comment by marcelklehr** [comment]
The face recognition mechanism does not override nor take into account metadata in the image

**Comment by Id3aFly** [comment]
Where is the metadata stored? In a nextcloud DB or in separate Metadata?

**Comment by marcelklehr** [comment]
In the database for now, we may opt to store it in the metadata at some point

**Comment by Id3aFly** [comment]
Ok, thanks for the information! I would really love whether you could consider already existing metadata to be used so it integrates better with existing facetagging.
