### ISSUE TITLE
NC 25 RC3 Error Logging when selecting from Photos Folder

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1331]
**Describe the bug**

**To Reproduce**
1. Click on Photos
2. Select Folders
3. Click on the image

https://user-images.githubusercontent.com/59488153/195181757-6df63261-3667-4668-a1fd-f38992ca71e1.mp4

![image](https://user-images.githubusercontent.com/59488153/195181911-ea13fa5c-750f-4087-8e89-b406d2cc0e3f.png)

![image](https://user-images.githubusercontent.com/59488153/195182043-fca67145-36a2-4d91-a308-e49aab4256da.png)

**Comment by skjnldsv** [comment]
Fixed on RC4
