### ISSUE TITLE
.nomedia and .noimage have no effect in Photos and All Media

### ISSUE THREAD

**Issue by SimonCDalzell** [nextcloud/photos#1338]
**Describe the bug**
I have created .noimage and .nomedia files in several folders that I wish to have excluded from Photos. The images within those folders still appear within Photos. As far as I understand from reading the other .nomedia issues here, this should work.

**To Reproduce**
Create a .nomedia or .noimage file in a folder.

**Expected behavior**
Images in a folder or subfolder with a .nomedia file should not appear in Photos.

**Additional context**
Is there a way to force a re-scan? I tried occ files:scan --all but this did not work, and I could not find any reference to .nomedia in the Nextcloud documentation. 

Server version is 25.0.0 RC3

**Comment by mbnoimi** [comment]
This bug still occurs in `Nextcloud 25.0.2` :(

**Comment by szaimen** [comment]
Did you try 25.0.2 already?

**Comment by mbnoimi** [comment]
> Did you try 25.0.2 already?

1. Upgraded it to `25.0.2 `
2. run `sudo -u www-data php /var/www/nextcloud/occ files:scan --all`
The bug still occurs.

**Comment by mbnoimi** [comment]
I opened a new bug report https://github.com/nextcloud/photos/issues/1551 because no one reopened it as this bug still occurs and it's really annoying.
