### ISSUE TITLE
Photo Directory filter does not work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/photos#1344]
If I set this e.g.:
![image](https://user-images.githubusercontent.com/24530680/195857874-692aea84-657d-4c88-9b36-118875063b09.png)

Nevertheless all my photos are shown

**Comment by skjnldsv** [comment]
This is not a filter directory, this is the location your photos are going to be saved when you upload some

https://github.com/nextcloud/photos/issues/141
