### ISSUE TITLE
NC25 RC3 Photos Folder delay

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/photos#1354]
**Describe the bug**
Since RC4 Or RC5 I noticed that theres a big dealy when clicking on folders within the photos app @artonge is this normal ? 

**To Reproduce**
1. Go to Photos App
2. Click on  Folders
3. Wait 15 to 20 seconds
4. 

**Expected behavior**
Should load right away

**Comment by artonge** [comment]
I don't think we changed anything that could add delay here.

**Comment by andyxheli** [comment]
Hmmmm I tested the NC 24 and it comes up right away.

**Comment by artonge** [comment]
Could you try and compare the requests made to the server ?

**Comment by andyxheli** [comment]
Sorry for the delay guys my VM got corrupt and my backups didn't restore it and had to start all over and get a new NC Server going transfer files :(

**Comment by andyxheli** [comment]
Here you go @skjnldsv 

![image](https://user-images.githubusercontent.com/59488153/196486848-979d942b-9406-4503-94e7-deaa9950c7fe.png)

**Comment by andyxheli** [comment]
@skjnldsv @artonge Looks like it hangs under albumes "pending" files a while it load everything.
Just tested on NC 25.0.1 RC1
![image](https://user-images.githubusercontent.com/59488153/198395794-02b5e828-2864-4201-a68d-33ba2d0a55c1.png)

![image](https://user-images.githubusercontent.com/59488153/198395748-71ec82cc-c42f-47e5-b279-023f26e24680.png)

**Comment by szaimen** [comment]
Since the waiting is new with NC25, I think it is a regressino.

**Comment by andyxheli** [comment]
Still an issue on NC 25.0.3

**Comment by AndyXheli** [comment]
No longer an issue tested on NC 26.0.0
