### ISSUE TITLE
"Download all files" produces an empty TAR file

### ISSUE THREAD

**Issue by nicokaiser** [nextcloud/photos#1394]
**Describe the bug**
The "Download all files" feature does not work. An empty (1024 bytes, no contents) "download.tar" file is downloaded.

**To Reproduce**
1. Open Photos app
2. Navigate to any Album
3. Open the "..." menu
4. Click on "Download all files in album"

**Expected behavior**
A ZIP (not TAR) file should be downloaded with all files in the album.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Server:**
Nextcloud 25.0.0

I am using the Dockerfile from the nextcloud/docker master branch. Maybe this is fixed with the official Docker image, I will check this once it is uploaded to Docker Hub.

**Comment by skjnldsv** [comment]
@artonge :thinking: 

Btw @nicokaiser , thank yuo so much for your tickets!! :pray:

**Comment by nicokaiser** [comment]
> Btw @nicokaiser , thank you so much for your numerous tickets!! It truly helps 🙏

I am eagerly waiting for the Photos 2.0 app (not updated my production server to NC25), so I'm more than happy to help making it even more awesome! Especially the possibility to share albums (and make public links from albums) will be a very useful feature...

**Comment by Raemsna** [comment]
I confirm and 2nd this issues. 
See link above with additional information

**Comment by szaimen** [comment]
Can yoi try again with 25.0.1?

**Comment by nicokaiser** [comment]
Still the same with 25.0.1.

**Comment by BkSouX** [comment]
same issue here with Nextcloud Hub 3 (25.0.2) and Photos 2.0.1

**Comment by oswaldo-be** [comment]
and unfortunately really annoying when you think for hours it is a problem of the nextcloud itself or another component

**Comment by artonge** [comment]
The button was removed by https://github.com/nextcloud/photos/pull/1641 until a proper way to download albums' content comes

**Comment by jonesints** [comment]
I think the original bug report ""Download all files" produces an empty TAR" is related to library TarStreamer:

https://github.com/owncloud/TarStreamer

php8 isn't supported and I believe owncloud had a different roadmap regarding php8 support which might be causing this issue:

[https://github.com/owncloud/TarStreamer/issues/23#issue-1155236540](url)

[https://central.owncloud.org/t/owncloud-development-roadmap-future-of-owncloud-classic-versus-ocis/37633/2](url)

I still get corrupted tar files any time I try downloading anything larger than 4GB on a mac. (zipstreamer library, for windows clients works fine)

**Comment by joshtrichards** [comment]
nextcloud/server/issues/37745

**Comment by joshtrichards** [comment]
@oswaldo-be Your issue appears entirely unrelated to the Issue you're commenting on:
> `"GET","url":"/index.php/core/preview?fileId=831115&x=341&y=256&a=1","message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused"`

It looks like your database went offline. Check your database server logs for clues. If you're unable to resolve the problem on your own, please post over at https://help.nextcloud.com/ with details about your environment to get assistance with your installation/setup.
