### ISSUE TITLE
Albums should show photos from oldest to newest

### ISSUE THREAD

**Issue by darguez** [nextcloud/photos#1427]
When you see the photos in an album (think about a real printed album) you always want to start by the beginning. So the normal order should be from oldest photos to newest. Also the Slideshow should show oldest photos first.

**Comment by hansixxxx** [comment]
I don´t understand why it isn´t possible to add a sort mechanism to the photos app? Can someone explain the technical problem?

**Comment by artonge** [comment]
@hansixxxx There is no technical limitation for this issue. It is only human time limited. ;)

**Comment by artonge** [comment]
Duplicate of https://github.com/nextcloud/photos/issues/1424
