### ISSUE TITLE
Nextcloud 25 "Photos 2.0" : When there is no video, "No video in here" should be displayed, not "No photo in here".

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/photos#1428]
The wording to indicate that there is no media should be differentiated between photos and videos.
When there is no video, "No video in here" should be displayed, not "No photo in here".
Thanks !
![2022-10-26_13-40](https://user-images.githubusercontent.com/33763786/198017444-aa321a1e-14b0-468b-82eb-fab24006b8e3.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/blob/fe37e5ae559133437329a73a9550e6a4088facf5/src/views/Timeline.vue#L90

**Comment by artonge** [comment]
Would "No photos or videos in here" work ? It would make the fix much easier :D

**Comment by Jerome-Herbinet** [comment]
@artonge Why not, so I have a question ; how can I change this by my self ? Can you guide me a little ? 
I sometime want to change some English wordings because it's sometimes (rarely) not relevant (in order to, of course, after this, change translation in Transifex).

**Comment by artonge** [comment]
The English wordings are hard-coded in the source files.

In this case, you can find it here:

https://github.com/nextcloud/photos/blob/b0c31d73be94d55e27ffe96b0e144ec190407a72/src/views/Timeline.vue#L90

Note that this file, and therefore wording, is used by all the timeline views, so 'All media', 'Photos', 'Videos', 'Favorites', …

So if you want to change the wording, you have to open a pull request with the change so it can be reviewed.

Let me know if you need more information.

**Comment by Jerome-Herbinet** [comment]
@artonge ; done with #1445 Pull Request to approve.
