### ISSUE TITLE
Album Share via Public Link not working

### ISSUE THREAD

**Issue by BuJ1** [nextcloud/photos#1430]
Hi everyone,

thanks for the great work on Photos 2.0. I'd like to report a bug. After having created an album and filling it with some photos, I wanted to "Share via public link". However, the button doesn't do anything on my end. It seems like it was forgotten to connect the share function to the button.

Nextcloud version: 25.0
Photos version: 2.0.0

Cheers

**Comment by skjnldsv** [comment]
@artonge ?
We had that one before, no?

**Comment by BuJ1** [comment]
I just investigated a bit further. Some function seems to be connected to the button, actually. Not sure if this helps but the console of my browser yields:

```
{
    "message": "Request failed with status code 404",
    "name": "AxiosError",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "requesttoken": "<token-identifier>"
        },
        "method": "put",
        "url": "<my-cloud-url>"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 404
}
```

**Comment by artonge** [comment]
> @artonge ? We had that one before, no?

Once or twice yes:
https://github.com/nextcloud/photos/issues/1311
https://github.com/nextcloud/photos/issues/1404
https://github.com/nextcloud/photos/issues/1402

Thanks for the report anyway :)
