### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by andreasjacobsen93** [nextcloud/photos#144]
## Feature request

User type: All

User level: All

### Description

Implementation of OpenCV for face recognition to easily tag people in photos.
This would make it easy for people to manage their photos.
Their exists a wrapper for OpenCV in PHP, to allow the use of it (possibly v2 feature)

As a beginning (v1) we could integrate some sort of face detection on images, and allow users to tag people themselves. Then a menu link could bring up a face albums, as tagged by the user.

### Benefit / value

This would bring the NextCloud gallery on level with similar solutions, from Google, Apple and Microsoft.

**Comment by Henri2h** [comment]
Hi everyone,

Small idea for the future face recognition feature.

Some software like Digicam are already using face recognition. Digikam allow you to save the face position in the metadata of the file. With this, one can tag a face on a picture and see the tagged picture on another computer. 

(FEATURE) The nextcloud photos app could sync the recognised faces with the metadata which could allow users to tag a picture in Digikam for example and see it when using the photos app in nextcloud.

Thanks for all the work put in making this new app alive !! Can't wait trying the photo app once the nexcloud snap package will be updated to nextcloud 19 !!

**Comment by skjnldsv** [comment]
> Can't wait trying the photo app once the nexcloud snap package will be updated to nextcloud 19 !!

nextcloud hub is shipped with photos (18) :)

**Comment by burk80** [comment]
is it possible to make this into a docker usable install.. i know there is problems with this atm .. but it seems like you need to compile the whole system with pdlib and dblib into photos or maybe even into nextcloud core .. which isnt desirable ... so if there is a possibility to make a docker image for facial_recognition  so that you could link that in docker compose to nextcloud and or photos

**Comment by skjnldsv** [comment]
> is it possible to make this into a docker usable install.. i know there is problems with this atm .. but it seems like you need to compile the whole system with pdlib and dblib into photos or maybe even into nextcloud core .. which isnt desirable ... so if there is a possibility to make a docker image for facial_recognition so that you could link that in docker compose to nextcloud and or photos

Would be awesome yes :)

**Comment by agboom** [comment]
@burk80 @skjnldsv You might be interested in following this thread: https://github.com/matiasdelellis/facerecognition/issues/221

**Comment by averdecia** [comment]
Hi, @matiasdelellis have you considered remove the image processing from the NC web server, and create a different application instead? Communicate them between APIs. We have an almost-working solution with this scheme. 
The main problem with the face recognition app is that it cant scale. For big instances, it increases the upload time and the heavy writing operation son the database. It may be a good idea if you change the core to an external source. Also, the models could learn from some user changes.
A corn job is not a good solution for big instances, you may be able to see your grouped photos more than 1 week after you upload them

**Comment by matiasdelellis** [comment]
Hi @averdecia 
> Hi, @matiasdelellis have you considered remove the image processing from the NC web server, and create a different application instead?

In principle, I am always ready to listen to proposals.. 😉 

> Communicate them between APIs. We have an almost-working solution with this scheme.

Well.. Show me what API you are working on...
My proposal is to add virtual folders to NC core.. an api similar to the Unified Searchs, where my application registers, informs the virtual folders, and when Files or Photos requires the content, I send the results. 

> The main problem with the face recognition app is that it cant scale. For big instances, it increases the upload time and the heavy writing operation son the database.

We have a large consumption for photo analysis, but I honestly think there is no better API than the one we are using..
However it's perfectly controlled.. It just depends on the size of the temporary image. You want quality?, use a large image and it will be slow and consume more memory. Do you want it to be fast? Minimize the images and you will lose some faces. 

About how it scale, you may be right during clustering. But beyond the analysis (Which is the highest consumption but it is controlled), we have a single report which fails during clustering with 55,000 images consuming 2GB of ram.  https://github.com/matiasdelellis/facerecognition/issues/339

We can improve, but I think it is still acceptable.. 

> It may be a good idea if you change the core to an external source.

https://github.com/matiasdelellis/facerecognition-external-model ¿? 🤔 

> Also, the models could learn from some user changes.

Now we are focusing on automatic clustering, but of course we want to get there. 

> A corn job is not a good solution for big instances.

Why? Would you like it to be integrated into the nextcloud cron?

> you may be able to see your grouped photos more than 1 week after you upload them

Please try uploading 55,000 photos to google photos, and tell me how long it takes.. 😅 
Why do you think that the photos of your cell phone in google photos take time? Your cell phone does not do it, a server farm does the hard work and even takes time..

Please don't think we can do better than google .. hahaha 😅

**Comment by meichthys** [comment]
Is this issue resolved with the new "Recognize" App?

**Comment by matiasdelellis** [comment]
Yup.. Touche.. 😉

**Comment by meichthys** [comment]
@matiasdelellis Could you clarify the primary differences between FaceRecognition and Recognize when it comes to face recognition?

**Comment by matiasdelellis** [comment]
Hi @meichthys 
I don't want to make any controversy about this.

Regarding this report, recognize was officially integrated as a facial recognition solution for Nextcloud Photos, and Nextcloud Face recognition is still a third-party app... So, it can be closed.

**Comment by matiasdelellis** [comment]
Ok.. Sorry, being politically correct, I'm not helping... 😅 

The main difference, and the reason for the new development within Recognize, is that this application has a 100% automatic approach. Install and run as nextcloud cron.

The other application, Face Recognition, needs some external dependencies (pdlib) that some users find difficult to install.. and needs some initial configuration. Mainly how much memory you want to dedicate to the process, and the size of the images that basically defines the quality of the process.

Regarding the integration, recognize is integrated. There is no discussion about this.
Regarding the quality of the results, we are discussing an application that just added this feature, so it is not fair to compare, and honestly I can not be impartial about it.

**Comment by nacho-domatix** [comment]
@matiasdelellis  Seems like we're seeking the same thing. Small world xD

**Comment by jakobroehrl** [comment]
Should be solved with NC25 and github.com/nextcloud/recognize
