### ISSUE TITLE
Design of the main content view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/photos#145]
TL;DR:
A simplest start for the main view would be similar to Arcane Office: https://photos.arcaneoffice.com
![](https://cdn.arcaneoffice.com/img/i_photos_screen_2x.png)

Then eventually we can look into stuff like macOS Photos: https://www.apple.com/macos/photos/
![](https://www.apple.com/v/macos/photos/d/images/overview/icloud_photo_library_large.jpg)

## Layout

The current layout fills the screen from left to right, making for a very stuffed experience. Other platforms limit the width of the main photo display to fewer elements:
- Flickr does 3: https://www.flickr.com/photos/tags/sunset
- Arcane Photos does 5: https://photos.arcaneoffice.com
- macOS Photos does 6: https://www.apple.com/macos/photos

Both macOS Photos and Arcane Photos (and Instagram) show photos square, cropped. We should do this too.
(Note: In search, macOS Photos has a special view where it’s visible if a photo is portrait or landscape – we can think about that in the future as well.)

## Structure

Currently we show a folder structure in the main view the same way like the Files app. Other photos apps do not do this, and it’s very crowded.
Instead we should simply go with a chronological photo stream like macOS Photos and the like.
Especially since we now have a proper grid view in Files, the Gallery app can have a design better suited to viewing photos.

## Display

We show a lot of other filetypes like SVG icons, PNG screenshots, etc. We could think about limiting these so there’s less unrelated noise inbetween photos.

cc @nextcloud/designers @skjnldsv

**Comment by FrouxBY** [comment]
Its amazing that a rework of the gallery is in progress,

As for a small contribution, i remember this medium article (https://medium.com/google-design/google-photos-45b714dfbed1) that give some insight on getting a high performance scrollable page for the Google photos website,
thanks a lot for your work!

**Comment by dlauper** [comment]
Hi all, I'm also new here but I thought extensively about the needs in a photos app the last few 
I agree 100%, that an uncropped view of the photos looks much sleeker. The tiled square view of pictures can already be achieved in Files.
I actually started a discussion over at the [Nextcloud forum](https://help.nextcloud.com/t/ideas-for-revolutionary-photo-organization/89278)  so far by myself with a few ideas about the photos app including some visualization drafts, maybe one or the other finds some inspiration in it...

**Comment by jancborchardt** [comment]
Closing this as we now have the non-cropped layout: https://github.com/nextcloud/photos/pull/435

If there’s other leftovers, please open separate issues for them – and make sure to search beforehand to not create duplicate issues. Thanks! :)
