### ISSUE TITLE
[Bug] Viewer in public albums is broken

### ISSUE THREAD

**Issue by nicokaiser** [nextcloud/photos#1452]
**Describe the bug**
When clicking on a thumbnail in public album view, the image is not loaded, but an error message "Error loading ..." is displayed.

The console reveals that the app is trying to load something like

https://nextcloud.example.com/apps/files_sharing/publicpreview/null?file=/photospublic/G3gmrpTgqfRLI1GA6RRG1yoyLoIhGyVM/275392-myimage.jpg&fileId=275392&x=2560&y=1440&a=true

which returns a 404 error.

**To Reproduce**
1. Create an album
2. Create a public link
3. Open the link (in a fresh browser / incognito mode)
4. Click on a thumbnail

**Expected behavior**
The image should be displayed

**Screenshots**

**Server:**
 - Nextcloud 25.0.1

**Comment by ximmox** [comment]
Still the same on Nextcloud 25.0.2 released yesterday.

Sadly the long awaited "public albums" function for Photos is basically useless like this. 🙁

**Comment by ChristianHirsch** [comment]
I can confirm that it's still not working. In case you need a quick workaround and are using a nginx server, you can add the following to your Nextcloud nginx config:
```
location ~ ^/apps/files_sharing/publicpreview/null {
        if ($args ~ "^file=/photospublic/([a-zA-Z0-9]*)/([0-9]*).*$") {
                set $w1 $1;
                rewrite .* /apps/photos/api/v1/publicPreview/$arg_fileId?x=1080&y=1080&token=$w1? redirect;
        }
}
```

**Comment by DivineDominion** [comment]
Ran into this just today, too. Sharing a public link to an album shows the album just fine, but looking at the pictures requires HTTP BASIC AUTH.

**Comment by ProjektCamping** [comment]
to share Albums in Public is a really nice function. I am heading the same problem that if you click on the pic to get the full res. pic it is asking for a AUTH. Is there a workaround or solution?

**Comment by klauweg** [comment]
I can confirm this behaviour with 25.0.2. It's really a pitty that this long awaited feature is unusable.
Of course i can supply further information, logs etc. But since it is easy reproducible it may be not necessary anyway.

**Comment by XorgMC** [comment]
> I can confirm that it's still not working. In case you need a quick workaround and are using a nginx server, you can add the following to your Nextcloud nginx config:
> 
> ```
> location ~ ^/apps/files_sharing/publicpreview/null {
>         if ($args ~ "^file=/photospublic/([a-zA-Z0-9]*)/([0-9]*).*$") {
>                 set $w1 $1;
>                 rewrite .* /apps/photos/api/v1/publicPreview/$arg_fileId?x=1080&y=1080&token=$w1? redirect;
>         }
> }
> ```

When running in Docker (and/or with reverse proxy), I had to add `absolute_redirect off;` in the location block to prevent redirection to the internal port

**Comment by Draluy** [comment]
Same here using 25.0.2.

**Comment by avinashpudota** [comment]
> I can confirm that it's still not working. In case you need a quick workaround and are using a nginx server, you can add the following to your Nextcloud nginx config:
> 
Facing the same issue. Is there any workaround for Apache?
Thanks.

**Comment by bdevy** [comment]
Also hoping for a workaround in Apache.

**Comment by iamjameswalters** [comment]
Glad to find and +1 this bug. @XorgMC that looks promising, does this mean a PR is coming soon?

**Comment by ProjektCamping** [comment]
> absolute_redirect off

For me that workaround is not working. Still asking for the log in :/

**Comment by ProjektCamping** [comment]
> I can confirm that it's still not working. In case you need a quick workaround and are using a nginx server, you can add the following to your Nextcloud nginx config:
> 
> ```
> location ~ ^/apps/files_sharing/publicpreview/null {
>         if ($args ~ "^file=/photospublic/([a-zA-Z0-9]*)/([0-9]*).*$") {
>                 set $w1 $1;
>                 rewrite .* /apps/photos/api/v1/publicPreview/$arg_fileId?x=1080&y=1080&token=$w1? redirect;
>         }
> }
> ```

For me that workaround is not working. Still asking for the log in :/

**Comment by kovlo** [comment]
> For me that workaround is not working. Still asking for the log in :/

@ProjektCamping, in NGINX Proxy Manager I set the following and the proposed workaround works:

![image](https://user-images.githubusercontent.com/12111565/212201258-b0eb83a1-93e4-43e8-8b8d-17deb136543f.png)

**Comment by jdaviescoates** [comment]
Great there are workarounds flying about that seem to be working for some, but given this is a major new app shipped by default I can't help wondering why actually fixing it isn't a higher priority :thinking:

**Comment by darguez** [comment]
It seems the bug is still there in v25.0.3 😔

**Comment by nicokaiser** [comment]
Sorry to say it like this, but Nextcloud Photos seems to be completely abandoned. Features (like this one) are teased in press statements but do not work at all (not just in some rare edge cases), fixes are – if at all – included in the next major version (i.e. ~once a year).

[Memories](https://apps.nextcloud.com/apps/memories) seem to be maintained much much better, but also is very limited feature-wise. It requires Photos to be installed for some features and also does not support public album links (only public folder links, which then are displayed grouped by month).

**Comment by jdaviescoates** [comment]
> Sorry to say it like this, but Nextcloud Photos seems to be completely abandoned.

I'd agree that it is a bit crazy that a core feature in a new featured plugin just not working at all, and that it is really rather bad, but I'm not sure it's fair to say it's been completely abandoned given the last commit was only 7 hours ago.

**Comment by nicokaiser** [comment]
Yes, the last commit was only 7 hours ago, but these commits are likely to not land in the next release (25.0.x) or in any minor or patch release, but only in the next major version (Nextcloud 26).

I know it might be unfair to say this is abandoned (it is not). However it is frustrating to see new features being only released as non-working UI skeletons which never worked and neither are fixed ASAP in a patch release. E.g. the public album feature should never have made it into the UI, it would be totally okay if it was greyed out and disabled. But adding a half-baked feature which breaks in production and produces unintuitive error messages is not the correct way IMHO.

**Comment by jdaviescoates** [comment]
> But adding a half-baked feature which breaks in production and produces unintuitive error messages is not the correct way IMHO.

I'd have to agree with that.

**Comment by pulsejet** [comment]
> [Memories](https://apps.nextcloud.com/apps/memories) seem to be maintained much much better, but also is very limited feature-wise. It requires Photos to be installed for some features and also does not support public album links (only public folder links, which then are displayed grouped by month).

FYI: Memories supports public album links now (v4.10+).

**Comment by darguez** [comment]
OMG, this is really amazing @pulsejet!!! Thank you for your excellent work with Memories app!! 👏👏

**Comment by klauweg** [comment]
Yes, it looks promising. But as far as i can see the album feature in Memories depends on installed and activated Photos app. And so public shared album links do not work either.

**Comment by kampfflunder** [comment]
Nope, public albums work for me. Both photos and memories need to be activated.

**Comment by darguez** [comment]
Sharing albums via public link works like a charm for me with Memories v4.10+ and NC 25.0.3

**Comment by darguez** [comment]
BTW, @pulsejet how difficult would be to add a password to increase the security of sharing an album via public link? It would be nice to have an additional security layer when you share sensitive photos (e.g. children's albums)

**Comment by Draluy** [comment]
> BTW, @pulsejet how difficult would be to add a password to increase the security of sharing an album via public link? It would be nice to have an additional security layer when you share sensitive photos (e.g. children's albums)

Seconded, it would be nice :)

Btw, just tested public album sharing and it works perfectly, thanks.

**Comment by pulsejet** [comment]
> BTW, @pulsejet how difficult would be to add a password to increase the security of sharing an album via public link? It would be nice to have an additional security layer when you share sensitive photos (e.g. children's albums)

Opened an issue for this, but won't be trivial unless Photos supports this directly. Worst case we need yet another table to store the passwords; best case the hash can somehow be squeezed into the link token itself.

**Comment by devnull4242** [comment]
I can not understand why it can be a security issue. It is no problem to see the thumbnails but access the normal photos.  Why does the access work when sharing images via "Files" (one file or the directory). Where is the difference?

https://i.imgur.com/1Ax7qP6.png

**Comment by ventoux84** [comment]
I want to share an album, but Nextcloud wants the user to log in when using the shared public link.
The mozaic is displayed, but a password is required when clicking on a thumbnail.
Nextcloud 25.0.3 - Photo 2.0.1
With "Firefox -safe-mode" the error message is :
"Erreur au chargement de ..."

With Chromium, it asks for user name and password in a popup window "Se connecter".

**Comment by simonspa** [comment]
Hi @ventoux84 

Nextcloud 25.0.4 has been released yesterday, it contains the fix to correctly display public albums. :)

**Comment by ventoux84** [comment]
Thanks, it works after upgrade to 25.0.4.

**Comment by darguez** [comment]
Awesome! Thanks!

Is it planed to allow setting a password in a near future to increase security?

**Comment by stefan-franz** [comment]
I i share a link of an album via public link (NC 25.0.4) everyone can remove images. I think that is a bug.

**Comment by devnull4242** [comment]
Yes. I think also it is a bug or a feature. I wrote an issue: https://github.com/nextcloud/photos/issues/1655

**Comment by iamjameswalters** [comment]
Thanks so much to @starypatyk for working on this for us!

**Comment by starypatyk** [comment]
@iamjameswalters Doing this for selfish reasons. :wink:  I use Nextcloud myself...
