### ISSUE TITLE
Preview is not updated after editing a photo

### ISSUE THREAD

**Issue by jacotec** [nextcloud/photos#1458]
**Describe the bug**
Preview in "Photos" is not updated after editing

**To Reproduce**
1. Start the photos app
2. Search for a picture in wrong orientation
3. Edit this picture in the photos app and correct orientation
4. Go back into photos
5. The picture is still displayed in the wrong orientation in the overview. When you open the picture in detailed view, it's correct

**Expected behavior**
After editing a picture the preview of it in photos should be also updated

**Screenshots**
Preview:
![image](https://user-images.githubusercontent.com/3321655/199957785-5c8356c5-3454-4c07-8e9a-844e9c268dd0.png)

When I click on it, this is the edited version:
![image](https://user-images.githubusercontent.com/3321655/199957839-393556ea-25e7-49ef-9755-721c2848ea61.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 107.0.5304.88

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by andyxheli** [comment]
Also it would be nice to be able to select a photo for the cover on the album

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/photos/pull/1647 IIRC
