### ISSUE TITLE
Not always sorted by creation date 📆

### ISSUE THREAD

**Issue by jannisS98** [nextcloud/photos#1466]
The app "Photos" does not always sort the uploaded pictures and videos by creation date.

**Comment by darguez** [comment]
Here there is an awful, but effective workaround: #1424

**Comment by joshtrichards** [comment]
That's because it sorts by modification time. :-)

See #87 and #397. 

We should probably close this Issue in favor of those and to avoid confusion.

**Comment by joshtrichards** [comment]
Closing to consolidate into #397
