### ISSUE TITLE
Copy internal link to clipboard doesn't work 

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/photos#1499]
**Describe the bug**
Copy internal link to clipboard doesn't work 

**To Reproduce**
1. Go to 'photos
2. Select a photo
3. Open sidebar
4. Click on share-tab
5. Click on the clipboard image next to 'internal link'. A green tick appears (for a while)
6. BUG: There is no link on the clipboard

**Expected behavior**
A link on the clipboard, but the clipboard is empty (or still contains the previous content)

**Screenshots**
![image](https://user-images.githubusercontent.com/16174035/203861755-f784d506-cbcd-4301-b144-96044690529d.png)
![image](https://user-images.githubusercontent.com/16174035/203862317-f0095da0-3dd5-4ee0-bef2-270cceac4910.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [tried it on chrome and edge]
 - Version [nextcloud 25.0.1, photos 2.0.0]

**log**
No errors in the nextcloud log at the time I have clicked the copy-image.

**Additional context**
The external link does copy to the clipboard.

**Comment by szaimen** [comment]
Hi, do you access your instance via https or http?

**Comment by GHBLoos** [comment]
I am accessing through HTTPS.
I just tried it, and now it works on Edge (I can't test on chrome at the moment). I can't explain why it works. Since November there have been updates, so maybe it has been fixed. 
I will monitor it for a while. If it keeps working, I will close the issue.

**Comment by joshtrichards** [comment]
@GHBLoos It's been a few more months - how is this situation looking for you? Please close this Issue if you're no longer seeing the problem in your environment. Thanks!

**Comment by GHBLoos** [comment]
I can't reproduce the issue anymore. Maybe it's repaired. Closed the issue
