### ISSUE TITLE
I don't see the App in the Nextcloud App store.

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/photos#150]
I don't see the app in the Nextcloud App store.

https://apps.nextcloud.com/?order_by=name&ordering=asc&search=photo

**Comment by skjnldsv** [comment]
It is not. This is a shipped app :)

**Comment by psy0rz** [comment]
in which version of nextcloud? I dont see it in 17.

**Comment by DBJRdev** [comment]
@psy0rz : You need version 18.x, until NC 17.x it's the gallery app instead.
