### ISSUE TITLE
Invalid Date for photos added on nextcloud to nextcloud transfer

### ISSUE THREAD

**Issue by rougerouter** [nextcloud/photos#1508]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by gruda74** [comment]
I realized issues with date handling on Nextcloud Photos with images uploaded from my iPhone.
I hope my detailed description could help in fixing.

To Reproduce Steps:
1. Upload photos from iPhone (11 - iOS 16.02) to my self hosted Nextcloud (version 25.0.5 - running on Ubuntu 22.0.4)
2. Open photos with iPhone App (version 4.7.0.23) and select 'Sort by newest' option:
    Some photos taken in 12.2022 are shown as photos from 03.2023 while others are shown correctly in 12.2022.
    2/b.) When selecting the 'Sort by name (from Z to A)' option the order is correct.
3. Check the photos on the Nextcloud Photos web UI (Chrome and Edge behavior is the same):
    Some photos taken in 12.2022 are shown as photos from 03.2023 while others are shown correctly in 12.2022.
    3/b.) On the web UI there is no 'Sort by name (from Z to A)' option.

Some more details about two sample photos:

A.) Problematic photo from 12.2022 shown together with 03.2023 photos:
File name on iPhone: IMG_8292.JPG
File name on Nextcloud storage: '22-12-30 20-21-11 8292.jpg'
Exif Info:
File Modification Date/Time     : 2023:03:26 18:44:54+00:00
File Access Date/Time           : 2023:03:31 15:58:08+00:00
File Inode Change Date/Time     : 2023:03:31 15:31:24+00:00
...
Modify Date                     : 2022:12:30 20:21:11
Host Computer                   : iPhone 11
...
Date/Time Original              : 2022:12:30 20:21:11
Create Date                     : 2022:12:30 20:21:11
...


B.) Photo from 12.2022 shown correctly together with 12.2022 photos:
File name on iPhone: IMG_8277.JPG
File name on Nextcloud storage: '22-12-28 12-48-55 8277.jpg'
Exif Info:
File Modification Date/Time     : 2022:12:28 20:11:58+00:00
File Access Date/Time           : 2023:03:31 17:23:22+00:00
File Inode Change Date/Time     : 2023:03:31 15:30:30+00:00
...
Modify Date                     : 2022:12:28 12:48:55
Host Computer                   : iPhone 11
...
Date/Time Original              : 2022:12:28 12:48:55
Create Date                     : 2022:12:28 12:48:55
...


Conclusion:
1.) Nextcloud gets correctly the creation date and this information is written into the file name used by Nextcloud.
2.) Nextcloud is using the Exif info 'File Modification Date/Time' to time sort the images what is causing problem by modified images.

**Comment by joshtrichards** [comment]
Hi @rougerouter & @gruda74 - Thanks for your reports. This topic (if I'm understanding your respective reports) is already being tracked in #87 and #397. Please close out this Issue to avoid confusion / duplicate work (unless you have a good reason to keep it separate that I'm overlooking).
