### ISSUE TITLE
Unable to install photos on NC 17.0.2

### ISSUE THREAD

**Issue by icetear** [nextcloud/photos#151]
The photos app is not recognized by NC 17.0.2. So I cloned it from github as detailed on this page.
It now shows up but activation is not possible: "Server version 19 or higher is required."

I don't understand that error message. Can you please give more information or update the information on the photos page?

Thank you

**Comment by skjnldsv** [comment]
The photos app is for 18+ only :)
Sorry!

**Comment by psy0rz** [comment]
ah i see. please update the main readme page to reflect this. :)

**Comment by skjnldsv** [comment]
> ah i see. please update the main readme page to reflect this. :)

what exactly did you find misleading?

**Comment by psy0rz** [comment]
I would be handy if it says: "Photos app is only included in nextcloud v18 and higher" on the main page.

**Comment by skjnldsv** [comment]
Done, thanks for the help @psy0rz  :)
