### ISSUE TITLE
[Bug] Error 404, css/icons.css not found (successor of #1451)

### ISSUE THREAD

**Issue by nicokaiser** [nextcloud/photos#1525]
This bug has been reported before, see #1451, and has already been fixed in #1454.
However the (admittedly small) fix did not make it into the next stable release (Nextcloud 25.0.2). Is there anything I could have done better to make sure the fix will not only land in the development branch (master) for an upcoming release (i.e. wait for many months for it to be released)?

**Comment by artonge** [comment]
I have just backported it to v25. It should be included in the next minor release.

https://github.com/nextcloud/photos/pull/1533
