### ISSUE TITLE
Photos app not working

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1534]
NC 25.0.2
App 2.0.1
![image](https://user-images.githubusercontent.com/59488153/207108077-9204a759-2b65-49f7-bb39-df5561c4a7bd.png)

**Comment by andyxheli** [comment]
As soon as I turned off the Recognize app is started to work

**Comment by szaimen** [comment]
cc @marcelklehr

**Comment by marcelklehr** [comment]
Can't reproduce. Anything in the nextcloud logs?

**Comment by andyxheli** [comment]
Nothing under the logs that i can see just takes forever to load once the  Recognize app is abled and it did all of the face rec

**Comment by andyxheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/207909563-9a3f39bd-3ebc-4332-9a27-f00dc025d6e7.png)

**Comment by andyxheli** [comment]
I believe so yes because before it was working

**Comment by andyxheli** [comment]
If you want to do a remote session let me know or ping be on nextcloud system and i can show you

**Comment by andyxheli** [comment]
Hi all Happy New Year! just wanted to see if we had any idea what causing this delay

**Comment by hertznsk** [comment]
NC 25.0.2. I have 250 GB of photos on raspberry pi. And the request to /remote.php/dav/ by the SEARCH method is executed within 9 minutes. At this point, iotop shows that mariadb is reading data from disk at a speed of 50 MB/s. I am not an specialist on mariadb, but it seems that not an optimal database query is being performed or there is not enough index.

I executed all these commands, but it didn't help.
db:add-missing-columns
db:add-missing-indexes
db:add-missing-primary-keys

**Comment by marcelklehr** [comment]
Can you try enabling the slow query log to see which query is causing this delay?

**Comment by marcelklehr** [comment]
Found the culprit, I think. Missing index. Will do a release this weekend :)

**Comment by andyxheli** [comment]
Thank you very much!

**Comment by hertznsk** [comment]
> Can you try enabling the slow query log to see which query is causing this delay?

Interestingly, this is not one big request, but a series of small ones

[slow.log](https://github.com/nextcloud/photos/files/10362550/slow.log)

**Comment by marcelklehr** [comment]
Yep, for each file in the search result a non-index-using query is sent to the db.
