### ISSUE TITLE
Album photo count incorrect

### ISSUE THREAD

**Issue by stratacast** [nextcloud/photos#1535]
**Describe the bug**
When you delete a photo from an album that was added with "Add photos to this album", and then delete the photo from Files, Photos 2.0 does not correct the counter with the deleted photo. You also can't dereference the deleted file so the number is permanently incorrect.

**To Reproduce**
1. Create a new album
2. Add a photo that already exists on Nextcloud
3. Go to files and delete the photo
4. Go back to albums. The thumbnail for the deleted photo is still present, and the counter shows 1 photo, but it should be 0 since the only photo added to the album was deleted

**Expected behavior**
When deleting a photo in Files that is in an album, the photo should either be kept in the album and still accessible, or deleted entirely from the album

**Comment by stratacast** [comment]
This is still broken in 25.0.3. Deleting a photo in Files still makes the album contain a reference to the photo in the album. Also, deleting a photo in a shared album in Files breaks the collaborative album completely. It is frustrating that Nextcloud markets this feature so heavily and yet apparently no one has bothered to do something as simple as deleting a photo, over 1 month later.

**Comment by simonspa** [comment]
I can confirm this behavior, file changes do not seem to be propagated to the albums. Interestingly, for me the error only appears for the share recipient, the original album author can still open it for some reason.

**Comment by simonspa** [comment]
Furthermore, when unsharing an album, also the files added by that user are not removed but stay in the album. When clicking on one, an error is shown that the file is not accessible.

Album sharing seems to need some attention I would say...

@marcelklehr @artonge any chance you have some time to dedicate to this?
