### ISSUE TITLE
Not all subfolders are displayed depending on the scale of the page

### ISSUE THREAD

**Issue by skl256** [nextcloud/photos#1540]
**Describe the bug**
Not all subfolders are displayed depending on the scale of the page.
For example, in the folder "2021" we have 143 subfolders.
The Files app shows all 143 subfolders without issue.
In the Photos app, when you open the 2021 folder, only 77 subfolders are displayed (1920*1080 screen, 100% page zoom).
If you start zooming out of the page in the browser, then the missing folders will appear below.

**To Reproduce**
1. Create a folder.
2. Put there, for example, 150 folders, each of them should contain photos.
3. Go to NEXTCLOUD_DOMAIN/apps/photos/ in the left menu, select "Folders", open a folder that contains 150 photo folders inside.
4. Scroll down, you will see that not all folders are displayed.
5. "Play" with the scale of the page, you will see that the number of visible folders changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/111241000/207895015-1337b9c7-8eeb-4215-8144-645d654204a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version  108.0.5359.100

**Additional context**
The problem also occurs on other browsers, including mobile devices.

NC: 25.0.2-fpm

**Comment by medarion** [comment]
I can confirm this issue. It always happens for long lists of files/folders after scrolling a few pages. The scrollbar has the right length, so enough space is reserved, but the thumbnails are not displayed. Any action which changes the viewport size like zooming, resizing the browser or opening the developer sidebar causes the thumbnails to be loaded.
Im running Ubuntu and this happens both in Firefox and Chromium (recent versions).

**Comment by JoshuaPettus** [comment]
Confirmed as well on firefox. resizing does effect which photos or folders are loaded, but it still wont display all of them at once for me.  I just get a bunch of blank space before and after that never loads.    I hope this one can get fixed soon

**Comment by temotodochi** [comment]
Confirmed on firefox.

**Comment by htttito** [comment]
Confirmed on firefox

**Comment by joshtrichards** [comment]
A fix for this was made in #1695 and backported as far back as v25.0.6. Can you confirm it is fixed in your environment? If so, please close this Issue!

**Comment by medarion** [comment]
I can confirm the issue is fixed in 27.0.0.

**Comment by skl256** [comment]
Thanks @joshtrichards ! 
I check in my environment in 25.0.8 - fixed.
Tested in latest stable Chrome on Windows 11 and in Android 13 - OK. 150+ folders displayed without this problem.
