### ISSUE TITLE
Enable squared photos view not working

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/photos#1588]
**Describe the bug**

**To Reproduce**
1. Go to Photos 
2. Click on Photos Settings
3. Select Enable squared photos
4. Images don't change still showing the default view

**Expected behavior**
Should show in squared view

Server NC 25.0.2
Photos App  2.0.1

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/photos/issues/1573
