### ISSUE TITLE
This app cannot be installed because the following dependencies are not fulfilled: Server version 19 or higher is required.

### ISSUE THREAD

**Issue by userbradley** [nextcloud/photos#161]
When I have tried to isntall the app 'Photos' and enable it I get the error:
'This app cannot be installed because the following dependencies are not fulfilled:
Server version 19 or higher is required.'

I have isntalled it by running git clone https://github.com/nextcloud/photos.git in the /apps folder of nextcloud
I have set the correct permisions for the folder and all subfolders but still get the issue, even after isntalling php-gd and restarting apache2
I am running version 18 of nextcloud on Ubuntu 18.04.3 LTS
Any clue where I've gone wrong?

**Comment by skjnldsv** [comment]
Hey, the master branch is for nextcloud 19, you might want to check the stable18.
But you do not need to manually install it, this is shipped with nextcloud 18 and automatically updated alongside any nextcloud server update.

**Comment by userbradley** [comment]
Thanks! I have downloaded and tried the stable18 and it's now picked up the correct version. For some reason it was not installed with my nextcloud version :(

**Comment by userbradley** [comment]
Sorry. This can be closed.
I have installed viewer and set the permissions and this seemed to help:
git clone --branch stable18 https://github.com/nextcloud/viewer.git
root@nextcloud:/var/www/nextcloud/apps# chown www-data:www-data viewer/
root@nextcloud:/var/www/nextcloud/apps# chmod -R 755 viewer/
root@nextcloud:/var/www/nextcloud/apps# systemctl restart apache2
