### ISSUE TITLE
Dark mode issues (NC18)

### ISSUE THREAD

**Issue by moviuro** [nextcloud/photos#163]
Hi,

There are some issues with dark mode in the Photos app (tried with both Firefox and Chromium):

* [White screen while loading](https://sco.popho.be/s/nAJ9LSdJroeWiRo) Photos ; this seems to happen with any full refresh/change of the main view
* [White bottom of main view](https://sco.popho.be/s/gLkKsoWmpT8JHCx) when not full (same happens with "tagged photos")

Happy to give more info if I can.

(Links expire in 1 month)

**Comment by Dextroz** [comment]
Experiencing the same issue. I am also willing to provide more info if required.

**Comment by adi2k5** [comment]
This might be a problem with dark mode in general, I'm seeing the same problem with news app when scrolling down the articles and at some point nextcloud is waiting to load next batch of articles.

**Comment by moviuro** [comment]
Related to https://github.com/nextcloud/server/issues/21013 , certainly.

**Comment by moviuro** [comment]
Looks like NC19 fixed it! https://sco.popho.be/s/SiPLEbjLZYC88mo

**Comment by skjnldsv** [comment]
Great! :)
