### ISSUE TITLE
Share an Album doesn't work - Nextcloud wants to login

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/photos#1639]
I want to share an album, but Nextcloud wants the user to log in. What do i have to do?
Nextcloud 25.0.2 - newest Photo App.

**Comment by g-work** [comment]
Duplicate of https://github.com/nextcloud/photos/issues/1452 ?

**Comment by ventoux84** [comment]
I want to share an album, but Nextcloud wants the user to log in when he clicks on the shared link.
Nextcloud 25.0.3 - Photo 2.0.1

**Comment by g-work** [comment]
Again: Duplicate of #1452 ?

**Comment by ventoux84** [comment]
With "Firefox -safe-mode" the error message is :
"Erreur au chargement de ..."

With Chromium, it asks for  user name and password in a popup window "Se connecter".

**Comment by g-work** [comment]
@ventoux84 Please check, if your issue is already described in #1452

**Comment by ventoux84** [comment]
After a complete reading of the  #1452, i think that this is the same thing.
Yes it's a duplicate. It's the first i have found when looking for an eventual bug in Photos.

I put back my comment in #1452.

**Comment by simonspa** [comment]
Duplicate of #1452 which is solved with NC25.0.4
