### ISSUE TITLE
Public link with read-only instead of delete

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/photos#1655]
With Nextcloud 25.0.4 the public shares including single full images works fine. Thank you.
My acutal problem is that i want to share albums with people but they do not delete images from the album.
Can you include different sharing links (delete and read-only)? Thanks.

**Comment by GitWidi** [comment]
I can't reproduce that. 
[Here](https://cloud-test.fwidmann.net/apps/memories/a/31UPI8DoQ9zdkbuoBj5Hx5UzcFGsYYrx), I have a public link to a shared album and I can't find a way to delete the pictures. 
Probably it is the symtpom, which @stefan-franz also describes [here](https://github.com/nextcloud/photos/issues/1452#issuecomment-1445411808). 

Did you distinguish between sharing **albums** and sharing **folders**? 

Can you explain your steps to reproduce this symptom?

I'm still excited about the capabilities of the app Memories. In my opinion it is a big step forward compared to the app Photos.

Regards
Widi

**Comment by stefan-franz** [comment]
Here is test Album
https://nco.stefan-franz.de/index.php/apps/photos/public/qAJGb5a6ZO3g6zEply7kyW0Rzahu9Uw4

On every image i have the possibility to hook on and right top there is an option to remove of this album

I created a public link from an album in the Nextcloud / Photos App
![Albums - Sharing - Nextcloud Photos App](https://user-images.githubusercontent.com/96744684/221511788-00c89143-29fd-43dc-933a-be4e167e7bc2.jpg)

**Comment by DivineDominion** [comment]
Can confirm that sharing an album offers the "select picture" checkbox + the "Remove selection from album" affordance in the top-right menu:
![CleanShot 2023-02-27 at 09 27 36](https://user-images.githubusercontent.com/59080/221512187-1c136547-43a0-4422-9ccf-dc2526a34118.png)

**Comment by GitWidi** [comment]
Oh, sorry. I was wrong. 
I thought I was still at the list of issues for the App Memories.

/Widi

**Comment by kvn61** [comment]
For not create new issue.
It would be nice to have two types of albums: protected and not protected for deletion. Not only for the public link, but for Collaborative albums also

**Comment by ventoux84** [comment]
I confirm that sharing an album offers the "select picture" checkbox + the "Remove selection from album" affordance in the top-right menu.
So, it would be nice to have two types of albums: read-only and read-write. Not only for the public link, but for Collaborative albums also

**Comment by jeliebold** [comment]
Read-only, read-write, and write-only would be great. It would make sense to have an album type where collaborators can add their photos but are unable to delete your additions.
