### ISSUE TITLE
[BITV] 9.1.4.11/4.2 - "Create new album" Modal Dialog - Both input fields frames do not meet the contrast requirements for graphical user interface elements. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/photos#1670]
- [x] Fix

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v4-n2

</details>

**Comment by Pytal** [comment]
Fixed on `master`
