### ISSUE TITLE
[BITV] 9.3.2.1/4.1 - Modal dialog "Photos settings" - When the input field "Default Photos" receives keyboard focus, the dialog "Select the default location for your media" is automatically opened. However, the keyboard focus remains in the "Photos settings" dialog. This behavior is very confusing. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/photos#1676]
- [x] https://github.com/nextcloud/photos/pull/1828
- [x] https://github.com/nextcloud/server/pull/37780

![0e4660212b80e42b753b1adcc08a8370](https://user-images.githubusercontent.com/1315170/222545837-ef299f89-4df2-45f5-8034-edf6ac8179b9.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3ac86eea54-v4-n1

</details>

**Comment by Pytal** [comment]
Already done @Fenn-CS :)
