### ISSUE TITLE
Duplicate Thumbnails/Previews in gallery view

### ISSUE THREAD

**Issue by pajades** [nextcloud/photos#1680]
**Describe the bug**
Gallery/timeline view All media / Photos / Videos displays two of every image FOR ONLY ONE USER. 
Selecting one image makes both highlight. 
There is only one image file, but two "thumbnails."

**To Reproduce**
1. Click on 'Photos' app button on top menu.

**Expected behavior**
There should be only one thumbnail for each image file.

**Screenshots**
![Screenshot from 2023-03-05 20-27-38](https://user-images.githubusercontent.com/60847505/222999763-0cb49cf8-24c9-4e17-95b2-3db58501f0b6.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Vivaldi (5.7...), Brave (1.48...), Chrome, Firefox (110.0..)

**Smartphone (please complete the following information):**
 - Device: not applicable
 - OS: not applicable
 - Browser not applicable
 - Version not applicable

**Browser log**
globals.js:60 
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.

**Additional context**
Images are stored on External Storage, all users have access.
Only 1 user has this issue.  If I remove the External Storage share for that user, only one set of images appears (I would think NO images would appear.)
I've tried deleting the Preview folder and re-generating the previews, as well as performing  occ files:scan and files:scan-app-data

**Comment by EnricoVerzegnassi** [comment]
Do you have any update?
I have your same problem!

https://help.nextcloud.com/t/photo-and-preview-from-external-drive-seen-twice-in-the-media/169370

**Comment by joshtrichards** [comment]
Closing per https://help.nextcloud.com/t/photo-and-preview-from-external-drive-seen-twice-in-the-media/169370/3
