### ISSUE TITLE
UUID displayed when searching a user while sharing an album

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/photos#1714]
**Describe the bug**
- [ ] UUID displayed when searching a user while sharing an album
- [ ] UUID also displayed in received shared albums

**To Reproduce**
1. Go to web app
2. Go to photo app
3. Go to "Album" menu
4. Share an album
5. Search either by firstname+lastname or mail address

**Expected behavior**
Should display the firstname and lastname

**Screenshots**
![ezgif-4-2eaa97a371](https://user-images.githubusercontent.com/986878/229489181-602461e4-1a58-470e-9da5-8ae3f788dd1c.gif)

**Desktop (please complete the following information):**
 - Browser: Chrome/Firefox/Opera/Safari

**Comment by DanScharon** [comment]
can confirm with Nextcloud 25.0.5 / Photos 2.0.1

**Comment by marcelklehr** [comment]
:tada: Thanks @artonge
