### ISSUE TITLE
Photos / gallery loads only 10-15 rows

### ISSUE THREAD

**Issue by petrkr** [nextcloud/photos#1716]
When using Photos gallery --> folder --> photos

then thumbnails are shown, but only 10 or 15 rows are shown, on scrollbar I can scroll over whole white/empty page, so it knows about more photos there, but from some reason they are not loaded... If I will open last photo and continue "to do right/next on" it works, but it will NOT preload preview on squares.

I already tried
 - clear preview folder and update app data
 - clear browser app data
 - different browser (Chrome / Firefox, both latest)
 - pre-generate previews

There is not any error either in nextcloud.log nor browsers log

Nextcloud is latest stable in time of writing: 25.0.5, but I saw this issue on earlier version too, but unfortunately do not remember when I notice it first time as more I using filesystem synced folder and OS's photo viewer.

![image](https://user-images.githubusercontent.com/6428351/228366978-8959fc81-8dd8-4386-ba74-9147617de232.png)

**Comment by xigulor** [comment]
Hello,

I have the same issue. I just upgraded to nextcloud 26, issue is still there.

I've tried all the ./occ optioons, rebuild everything, changed php version (I use the fpm and apache2) from 8.1 to 8.2, increased the files limit in php, the memory for php-fpm, no lucks.

I have +2OK files inside a lot of folders. Nothing in the logs, no php error message, no apache errors, tried with full debug, same no infos

**Comment by szaimen** [comment]
This should be fixed with 25.0.6 and 26.0.1

**Comment by temotodochi** [comment]
25.0.5 still has this issue. It can be circumvented by changing the page zoom level in firefox. (ctrl + or -)

**Comment by petrkr** [comment]
I can confirm in 26.0.1 it works fine already. Ca not test 25.0.6 as I will NOT downgrading. Can you @temotodochi test it, if you already not updated also to 26.x. I want to close issue if it was fixed in 25 too

**Comment by temotodochi** [comment]
25.0.6 RC1 in use and it works as it should.

**Comment by petrkr** [comment]
Fixed then
