### ISSUE TITLE
Add ability to rotate images in 90-degree increments

### ISSUE THREAD

**Issue by Robert-Clever** [nextcloud/photos#1726]
I have the photos app on my Nextcloud instance, but it doesn't let you lock on rotating images in 90-degree increments. You have the slider, but it's hard to get it to rotate in 90-degree increments. Most photo apps have a single button that can rotate an image by 90-degrees.

![image](https://user-images.githubusercontent.com/59885439/229319387-83abdfa8-692e-4221-8cfc-669e5fc4c06b.png)

**Comment by joshtrichards** [comment]
As the image editor is actually provided by the NC Viewer app and not provided directly by the Photos app, I believe the correct place for this is Issue actually https://github.com/nextcloud/viewer.

**Comment by Robert-Clever** [comment]
> Hi @Robert-Clever - Thanks for the report! The image editor is provided by the `Viewer` app and not provided directly by Photos, The correct place for this is Issue https://github.com/nextcloud/viewer.
> 
> Please submit there and close this Issue out (I'd transfer it for you but I lack the privileges).

Ok, thanks for that information. I moved the issue over there. I'll close this one out.

Here is the link to the new issue...
https://github.com/nextcloud/viewer/issues/1846
