### ISSUE TITLE
PHP error: ReverseGeoCoderService.php on line 144

### ISSUE THREAD

**Issue by derwotograf** [nextcloud/photos#1733]
**Describe the bug**
as current knowledge, the php error is created about every 12 hours. I've checked the php memory limit settings several times and its set to 512MB.

**To Reproduce**
1. I updated NC from 25 to 26 once it was stable.
2. since then this error happens.

**Error output:**
`PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/.....netcup.net/..../apps/photos/lib/Service/ReverseGeoCoderService.php on line 144`

**Comment by szaimen** [comment]
cc @artonge

**Comment by joshtrichards** [comment]
Hi @derwotograf  - Sorry you're experiencing this behavior.

Please check your CLI PHP configuration. Your PHP `memory_limit` may be `512M` for the Web PHP, but it appears to be set to `128M` for your CLI PHP (per that error message) which is used by Cron. You'll need to fix your PHP configuration. 

If you get stuck trying to check for change this setting, visit the [Nextcloud Help Forum](https://help.nextcloud.com) and either search for solutions or post for assistance.

This isn't a Photos app bug. This issue can be closed out.

**Comment by szaimen** [comment]
> This isn't a Photos app bug. This issue can be closed out.
