### ISSUE TITLE
Enabling or disabling squared photos view requires a reload, which may not be expected by the user

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/photos#1742]
**Describe the bug**
The setting `Enable squared photos view` [needs a reload to be taken into account](https://github.com/nextcloud/photos/pull/1659). However, users may expect that enabling and disabling the setting is immediately reflected in the view, and think that the setting is broken if it does not happen.

A quick solution could be to replace `Enable squared photos view` with `Enable squared photos view (a reload is needed for this setting to take effect)` or something like that.

Another option would be to reload the view when the setting is changed, although that could be a bit _aggressive_.

**Comment by loeffelpan** [comment]
Does the setting work for you? As I metioned in #1573 it did not change anything (including reload) with 26.0.0 RC2 and even not with 26.0.2. Both were tested with AIO (docker).

**Comment by joshtrichards** [comment]
Hi @danxuliu & @loeffelpan - This feature works well for me in `master/2.4.0` (including instantly changing view when I toggle the setting - no reload required).

What browser(s) are you both using?

In you browser console, under Network, do you see a request for `croppedLayout` when you toggle the button?

**Comment by loeffelpan** [comment]
Hm, I tested with NC26.0.3 (AIO) and latest Edge and Safari (iPadOS). But my app list says photos would be 2.2.0. Is that correct? I thought that 26.0.3 would include 2.4.0, but I cannot resolve app versions to releases here on github, as there are only NC versions mapped in the tags.

**Comment by joshtrichards** [comment]
Yeah the versioning can get a little confusing. The stableXX tag in this repository can be cross-referenced with the appinfo/info.xml file to find the latest available for a given NC. For NC26 looks like the current latest is v2.2.0:

https://github.com/nextcloud/photos/blob/stable26/appinfo/info.xml

NC27 gets v2.3.0:

https://github.com/nextcloud/photos/blob/stable27/appinfo/info.xml

It's possible that some other NC vue component update addressed the reload, and maybe a bit more, beyond what #1659 addressed. And perhaps that mix doesn't come together until NC27+. I don't have my other test instances in front of me at the moment to comparison test.

**Comment by loeffelpan** [comment]
OK, got it. As of #1659 should be part of NC26.0.3. But as I said - not working for me.
I can see API PUT request for cropped layout with different payload (true/false) when toggling, but all my photos are squared/cropped anyway. Regardless of the aspect ratio.

**Comment by oddstr13** [comment]
I'm seeing square thumbnails for photos uploaded before I updated Nextcloud (from 24 via major releases up to 27), the photos uploaded afterwards have the correct aspect ratio in thumbnails.

The setting toggle that this issue is about takes effect instantly, while the settings window is still open.
(I'm currently regenerating all thumbnails by deleting them and running the previewgenerator, but that doestn't seem to help. Per photo preference somewhere, that isn't getting affected by just deleting the thumbnail files?)
