### ISSUE TITLE
All Media and Photos views are blank after upgrade to 26.0.1

### ISSUE THREAD

**Issue by ryester19** [nextcloud/photos#1753]
**Describe the bug**
Since upgrading to Nextcloud 26.0.1, the "Photos" and "All Media" views are blank

**To Reproduce**
1. Open Photos app
2. Click on 'All Media' or 'Photos' view

**Expected behavior**
All my uploaded image thumbnails should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/17807258/233397086-eb9bbea0-7a9f-42de-8590-446bf78862b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Librewolf (Firefox)
 - Version: 112.0.1-2

**Browser log**
```
10:32:00.867 JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
10:32:00.984 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.019 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.020 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.024 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.040 OCA.Files.Sidebar initialized Sidebar.js:36:10
10:32:01.040 OCA.Files.Sidebar initialized sidebar.js:39:8
10:32:01.144 Proxying an event bus of version 3.0.2 with 1.3.0 major.js:2:14
10:32:01.148 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.298 OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
10:32:01.298 OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
10:32:01.299 OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:33:10
10:32:01.318 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.372 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.373 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.381 OCA.Comments.View initialized comments-app.js:32:8
10:32:01.385 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:59:15
10:32:01.408 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:01.560 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.560 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:01.654 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: "viewer", uid: "ryester19", level: 2, ignoredMimes: (3) […] }
ConsoleLogger.js:56:18
10:32:01.664 OCA.Viewer initialized Viewer.js:52:25
10:32:01.750 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:6
10:32:01.919 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20 globals.js:59:15
10:32:02.179 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:02.183 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:02.825 session heartbeat polling started session-heartbeat.js:103:9
10:32:03.208 Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
10:32:03.219 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:59:15
10:32:03.219 Registering notifications container as a menu NotificationsApp.vue:220
10:32:03.219 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:59:15
10:32:03.220 Notifications permissions granted NotificationsApp.vue:454
10:32:03.225 Has notify_push enabled, slowing polling to 15 minutes NotificationsApp.vue:232
10:32:03.225 Polling interval updated to 900000 NotificationsApp.vue:414
10:32:03.226 Started background fetcher as session_keepalive is enabled NotificationsApp.vue:276
10:32:03.419 [ERROR] photos: Error fetching files 
Object { level: 2, app: "photos", uid: "ryester19", error: SyntaxError }
ConsoleLogger.js:46:10
10:32:03.421 SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    updateFiles files.js:2
    updateFiles files.js:2
    A vuex.esm.js:831
    commit vuex.esm.js:437
    commit vuex.esm.js:37
    _withCommit vuex.esm.js:601
    commit vuex.esm.js:36
    commit vuex.esm.js:394
    appendFiles files.js:142
    A vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    r FetchFilesMixin.js:98
    l FetchFilesMixin.js:2
    x FetchFilesMixin.js:2
    b FetchFilesMixin.js:2
    k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    promise callback*k FetchFilesMixin.js:2
    a FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    N FetchFilesMixin.js:2
    fetchFiles FetchFilesMixin.js:60
    getContent Timeline.vue:237
    VueJS 4
    needContent FilesListViewer.vue:244
    VueJS 4
    isNearBottom VirtualScrolling.vue:231
    VueJS 12
    resizeObserver VirtualScrolling.vue:260
    mounted VirtualScrolling.vue:257
    VueJS 18
    init vue-router.esm.js:2980
    init vue-router.esm.js:2978
FetchFilesMixin.js:114:12
10:32:03.450 Got notification data NotificationsApp.vue:377
10:32:03.450 Polling interval updated to 900000 NotificationsApp.vue:414
```

**Comment by AndyXheli** [comment]
Hmm im running NC 26.0.1 Ubuntu 22.0.4, PHP 8.1 & MySQL 10.6.12 and no issue so far

**Comment by DaleBCooper** [comment]
I can confirm this problem for NC 26.0.1 with PHP 8.2 after updating from 26.0.0.
"Videos" and "Folders" work, the rest shows blank pages.

**Comment by unknownuserisknown** [comment]
I can also confirmed. NC 26.0.1 PHP 8.1

**Comment by prairietree** [comment]
I just updated my Next Cloud in a docker container to version 26.0.1 and have the same issue. It works fine in one account that does not have much more then the default set of files. I have another account that has lots of files and it does not work in that account.

I see to errors in the browser console:

1. [ERROR] photos: Error fetching files
2. SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data


![image](https://user-images.githubusercontent.com/19625784/233500975-3c652913-bb8a-4041-9419-beb559826ebe.png)

![image](https://user-images.githubusercontent.com/19625784/233501118-d5c107c0-82f5-48ed-9884-7ac0b7117e49.png)

I looked through all the json network calls and did not see any thing that looked like it was bad formatting. 

I pulled the file from photos-main.js?v=f4c0f6df-0. The browser can download it ok but when I try to past it into Kate or Writer they freeze up.

**Comment by szaimen** [comment]
Cc @artonge

**Comment by AzureInformatique** [comment]
I can also confirm. NC 26.0.1 PHP 8.2

**Comment by NobodyO815** [comment]
me to, but only with photos on Externam SMB Share - local Photos are no problem.
NC26 
PHP8.1.2

**Comment by WebOscar** [comment]
Same here. Debian 11.6, MariaDB. Tested with PHP 8.1 and 8.2.

`include(): Failed opening '/installationpath/apps/theming/lib//ImageManager.php' for inclusion (include_path='/installationpath/3rdparty/pear/archive_tar:/installationpath/3rdparty/pear/console_getopt:/installationpath/3rdparty/pear/pear-core-minimal/src:/installationpath/3rdparty/pear/pear_exception:/installationpath/files/apps') at /installationpath/lib/composer/composer/ClassLoader.php#578`
and
`Exception: Class "OCA\Theming\ImageManager" not found in file '/installationpath/lib/private/Server.php' line 1215`

**Comment by Hiyoal** [comment]
Getting the same using latest Docker 26.0.1 on Debian.
26.0.0 no issues.

**Comment by nicrame** [comment]
Same here on RHEL, nginx, PHP 8.2, Firefox or Chrome.

**Comment by hugalafutro** [comment]
I can confirm the same, few things I noticed:
- the media view started working on android app for me where it was always empty before, however I've no idea if it's related and would much prefer it working on browser
- as for individual tabs they all work, I can dig through the Folders tab, Tags work, Videos work etc, Photos / All media tabs remain empty
- I have spun a fresh test instance of nextcloud aio on hetzner cloud vps, updated it to 26.0.1 and there it works, All media tab shows the default Nextcloud hub video along the default photos

The last point confuses me though as the AIO installed as 25.0.1 (? i'm getting lost in the numbers, stable 25), then I updated it to stable 26.0.1 via occ, which is exactly the same thing I did on my local installation, where I also use imaginary as preview generator.

**Comment by prairietree** [comment]
@hugalafutro It might have to do with the number of photos in the account its self. I think this because I have access to two accounts that have little more then the default set of photos and the both work fine. But a third account on the same server that has many thousands of photos does not work. 

So it may be possible that there is some json string getting clipped off when it gets to long.

Can someone else verify with they are seeing the same thing?

**Comment by Psy-Virus** [comment]
> @hugalafutro It might have to do with the number of photos in the account its self. I think this because I have access to two accounts that have little more then the default set of photos and the both work fine. But a third account on the same server that has many thousands of photos does not work.
> 
> So it may be possible that there is some json string getting clipped off when it gets to long.
> 
> Can someone else verify with they are seeing the same thing?

For me all existing users, even if they're old basic setup users, with only the default file set, have the photos issue. But a newly created user doesn't have the issue.

**Comment by maxdcy** [comment]
Same issue here. selfhosted and updated to 26.0.1. was working abit on mozilla but stopped too :)

please please fix it

**Comment by Dymirt** [comment]
same issue JSON Parse error: Unexpected EOF
NC 26.0.1
PHP 8.2

**Comment by ozhound** [comment]
i see that this has been "fixed" but ive just installed a new instance of AIO and this is happening to me. Im on 26.0.1 using a fresh debian container on proxmox as the host

**Comment by plandreisepp** [comment]
> @hugalafutro It might have to do with the number of photos in the account its self. I think this because I have access to two accounts that have little more then the default set of photos and the both work fine. But a third account on the same server that has many thousands of photos does not work.
> 
> So it may be possible that there is some json string getting clipped off when it gets to long.
> 
> Can someone else verify with they are seeing the same thing?

I can confirm that. I have the same problem with my private account with just over 400 pictures. With another account that only contains the standard images, the problem does not occur. So it really is related to the number of pictures. By the way, I don't have any heic pictures stored in my private account.
Nextcloud 26.0.1, Photos 2.2.0

**Comment by hugalafutro** [comment]
I tried uploading .heic image to the test aio instance that works and it absolutely cannot display it. I tried changing the config.php preview config to the values I have on my main instance (where heic works), but fresh aio instance still fails to display it.

OffTopic:
I know I am just a layman who contributed nothing towards the software, but inability to display the most prevalent modern high efficiency image format in latest stable version, along with inability to display large photo albums, compounded by the fact that android notifications have been broken without any resolution for literal years is sadly why I can never recommend NC to any of my friends and I have to tell them to use onedrive or google drive, because they don't have the will and/or know-how/time to "make it work" or chase issues on github.

I just hope it is actually better for the folks who pay for the enterprise grade support, because if they're in the same boat, then what are they paying for ?

**Comment by ozhound** [comment]
@hugalafutro I agree with your sentiments, Nextcloud is broken for me. Photos don't show, I can't create new documents without it showing an error, full text search doesn't work. It all amounts to a super user-unfriendly solution that wouldn't be anywhere near suitable for general use.

**Comment by JanisPlayer** [comment]
@hugalafutro so heic works for me without problems with Imaginary and the Standard Generator.
If you want it to work with the default generator you have to enable it in the config:
```
  'enabledPreviewProviders' => 
  array (
    12 => 'OC\\Preview\\HEIC',
```
And yes, the image recognition quickly overloads the DB when there are too many images.
And I also think the operation of the photo app can be improved and would like to contribute something, but since I have no experience with this type of development, I do not know if I can improve it, even if it is simple at first glance.
But this photo app here, where you just write, it has rather its quirks concerning the handling of large albums, a few things can actually be improved.
Scrolling, HQ previews cache for short views with zoom, original image.
The Android APP is quite terrible in terms of function with many photos, have also had before the last updates only crashes and the gallery is still only half loaded.
I'm glad I got the WebP support for Nextcloud previews, let's see if it makes it into the main project.
In any case, the developers are cool that they give you the opportunity to change something yourself and also support you to some extent.

But hope that now HEIC images are converted with you.

**Comment by umgfoin** [comment]
The [memories](https://apps.nextcloud.com/apps/memories) app seems to be unaffected by recent breaking changes in nextcloud-stable 26.0.1.
IMHO it's an equal, in some respects better, replacement for the _photos_ app.

**Comment by hugalafutro** [comment]
@umgfoin that app looks great, gonna give it a go thanks for the suggestion!

**Comment by JanisPlayer** [comment]
@umgfoin wau almost everything I wanted, even if the at the beginning takes the database neatly ran, it is later from the condition better.
Thanks for the recommendation.

**Comment by jjasoncool** [comment]
@artonge can we have a new release to fix this issue????

Issue is closed, but still not release.

We can't view our photos by date, please.

**Comment by artonge** [comment]
The bug is about 26.0.1, the next release, 26.0.2, will contain the fix, which is expected on the 25 of May.
For more details on our release schedule, you can refer to: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by jjasoncool** [comment]
> The bug is about 26.0.1, the next release, 26.0.2, will contain the fix, which is expected on the 25 of May. For more details on our release schedule, you can refer to: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Thanks for the information.

**Comment by DaleBCooper** [comment]
For those who cannot wait: install "memories" mentioned in https://github.com/nextcloud/photos/issues/1753#issuecomment-1545369978
https://apps.nextcloud.com/apps/memories

**Comment by JackDinn** [comment]
> > The bug is about 26.0.1, the next release, 26.0.2, will contain the fix, which is expected on the 25 of May. For more details on our release schedule, you can refer to: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
> 
> Thanks for the information.

Just installed, this was the first thing i noticed. I can't imagine how this went past unnoticed by the dev :-/  
However, its the 25th, how do i update it to fix this. thx.

**Comment by NobodyO815** [comment]
> > > The bug is about 26.0.1, the next release, 26.0.2, will contain the fix, which is expected on the 25 of May. For more details on our release schedule, you can refer to: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
> > 
> > 
> > Thanks for the information.
> 
> Just installed, this was the first thing i noticed. I can't imagine how this went past unnoticed by the dev :-/ However, its the 25th, how do i update it to fix this. thx.

just update NC To 26.0.2

**Comment by hugalafutro** [comment]
@NobodyO815 yes, but imagine you're new user who just discovered Nextcloud. It looks fantastic, like it would allow you to ditch google, so you install the latest STABLE version, and right out of the box a LOT of things very important to everyday folks like photos and notifications don't work, other things need tinkering and editing files in cli - and at this point the everyday person is uninstalling and returning to one of the big boys like google or microsoft.

This issue (imho) has become more about where the focus of devs lies (adding useless ai features just because "it's so hot right now") then about the issue with photos themselves. It's like the devs themselves do not use their software. If I had the programming knowledge and was responsible for pushing out builds of NC and a serious bug like photos not working would appear, I'd stay up until a build where it works was pushed out regardless of how much caffeine it would require.

Just my opinion, I know it's free and it's working exactly as well as how much I paid for it.

**Comment by JackDinn** [comment]
> just update NC To 26.0.2

Im trying. 

Does have an app updates available for "Talk" but nothing showing for the app "Photos"

NC in a jail on Truenas is still showing that its up to date at 26.0.1

![image](https://github.com/nextcloud/photos/assets/5557560/1a517d43-5ad3-4610-addf-8d50f2533fbe)

**Comment by hugalafutro** [comment]
@JackDinn switch to beta, refresh page, update to 26.0.2RC or w/e it's called, switch back to stable, photos work

**Comment by JackDinn** [comment]
> switch to beta,

This is a genuine response? Why would anyone be asked to "switch to beta". Anyhow, it says there fix is released today. I shall wait i prefer a stable platform for all my most important files etc.



> This issue (imho) has become more about where the focus of devs lies (adding useless ai features just because "it's so hot right now") then about the issue with photos themselves. It's like the devs themselves do not use their software. If I had the programming knowledge and was responsible for pushing out builds of NC and a serious bug like photos not working would appear, I'd stay up until a build where it works was pushed out regardless of how much caffeine it would require.
> 
> Just my opinion, I know it's free and it's working exactly as well as how much I paid for it.

You are spot on my friend. I am a noob really but i would not have the space to list all the really blindingly obvious errors that iv come across. 

Just this one screenshot might just about sum up what im talking about:-

This is in the "Security" section, yea the security section. Not only is it laughable as it is "Confirm/Yes" But it does not even matter what you type in as it looks like it accepts anything or nothing at all.

How secure are my "life files" ?

![Screenshot_20230524_214747](https://github.com/nextcloud/photos/assets/5557560/84c24ed5-d72e-460f-b022-10bae57181f5)

**Comment by hugalafutro** [comment]
@JackDinn 
> How secure are my "life files" ?

For this I do not trust nextcloud (or any other cloud provider for that matter) and either upload the files encypted by myself (truenas cloudsync) or store files on encrypted zfs volume on truenas mounted as external storage into NC.

**Comment by NobodyO815** [comment]
@hugalafutro & @JackDinn ,
Yes, ur right some way - even for me it's sometimes frustrating, but they "need" AI because everything with it is hip and only hip things go further, ask the smart kids out there :-| but plz stay at topic.
With Beta, you get 26.0.2 and this fixes the problem, after that switch to stable.

**Comment by JackDinn** [comment]
Thx. Im asking how you update to the stable 26.0.2 because according to the release info page it's released today? I don't see it.

**Comment by artonge** [comment]
Hey folks, locking the conversation here, is it going off-topic and the issue is resolved.

For community support, you can go to the forum.
