### ISSUE TITLE
Portrait oriented photos display in Landscape when viewed

### ISSUE THREAD

**Issue by JoshuaPettus** [nextcloud/photos#176]
This is odd, especially as the thumbnail orients them correctly, only to have them sideways when viewed.  The regular photo viewer in nextcloud displays them correctly.

**Comment by JoshuaPettus** [comment]
[https://cloud.joshpettus.com/s/A79MCtd77XddmoJ/preview](url)

Here is an example I don't mind sharing.  It actually displays upside down in photos.

**Comment by JoshuaPettus** [comment]
Here is an example I don't mind sharing.  It actually displays upside down in the photos app.  I'm sure it's the same issue.

[Image](https://cloud.joshpettus.com/s/A79MCtd77XddmoJ/preview)

**Comment by skjnldsv** [comment]
Hum, I can not reproduce your issue with your image! :confused: 
That is a very interesting bug :grin: 

Can you screenshot the interface when it's misbehaving please?

**Comment by JoshuaPettus** [comment]
Dang, that will sure make it harder to pin down. :(  It really is weird.
Sure, happens on multiple clients, windows, linux, whatever, any browser Ive tried, firefox, edge, chromium.

Here is a screenshot
![image](https://user-images.githubusercontent.com/5043172/73934112-c9c59c80-48ab-11ea-9f76-d120d9049bb1.png)

**Comment by skjnldsv** [comment]
What the hell :p
If you upload the same image into a different name/folder, can you reproduce the same issue?

**Comment by JoshuaPettus** [comment]
Just tried that when you said loading it to your nextcloud didn't have that result.  Unfortunately that didn't work

But I just found the way a I shared it forced you to make a copy and that copy oriented correctly.  Let me try sharing it this way.

![20191109_154305](https://user-images.githubusercontent.com/5043172/73934800-32614900-48ad-11ea-94e9-a5c5c35ec7ce.jpg)

**Comment by skjnldsv** [comment]
Wow :grin: 
SO even github is displaying it in reverse, but opening in a new tab works :)

I'm guessing your image is bisbehaving

**Comment by JoshuaPettus** [comment]
haha wow!

**Comment by JoshuaPettus** [comment]
Ok, well I can fix that myself then

**Comment by skjnldsv** [comment]
In your exif:
```
exiftool 20191109_154305.jpg 
ExifTool Version Number         : 11.85
File Name                       : 20191109_154305.jpg
Directory                       : .
File Size                       : 2.4 MB
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Orientation                     : Rotate 180
```

**Comment by skjnldsv** [comment]
Orientation : Rotate 180, this is most likely the issue, so a camera bug I guess?

**Comment by JoshuaPettus** [comment]
Must have been, Funny how it's been ignored up until now by a lot of other software

**Comment by skjnldsv** [comment]
Thanks for the feedback!
