### ISSUE TITLE
Photos not showing coordinates

### ISSUE THREAD

**Issue by tuxArg** [nextcloud/photos#1795]
Hi,

I can't see the gps coordinates of any photo. They aren't displayed on memories, photos, maps, android photos app, etc.
I can check than gps coordinates of the photos are there using exif command line tool or php exif_read_data function:

GPS Tag Version     |2.2.0.0
North or South Latit|S
Latitude            |34, XX, 34.36
East or West Longitu|W
Longitude           |58, YY, 39.53
Altitude Reference  |Sea level
Altitude            |43

I run these commands with no errors:
occ files:scan --generate-metadata --all
occ maps:scan-photos --now
occ memories:index

I can see that other metadata is shown like Manufacturer/Model, just no coordinates shown.

Thanks
![Screenshot at 2023-05-12 13-46-42](https://github.com/nextcloud/photos/assets/42143259/c05d78a7-0519-4a9b-a959-76a38d767493)

**Comment by tuxArg** [comment]
Just solved!
Solution was:
occ photos:update-1000-cities
occ photos:map-media-to-place

**Comment by jwilleke** [comment]
Obviously, anytime you  need an "occ" command it is not a fix at most a workaround.
