### ISSUE TITLE
Dynamic Album Based on Tags

### ISSUE THREAD

**Issue by da3dsoul** [nextcloud/photos#184]
The title says it all, I think. You add a photo with a tag, it's automatically added to an album, and from that album it can be shared and viewed.

**Comment by skjnldsv** [comment]
Hey! Thanks for your suggestion :)
You mean "fake" albums? Or like copying the file to a dedicated folder album?

**Comment by da3dsoul** [comment]
I was under the impression that albums were merely groupings by nature. Unlike just using tags, you save albums for viewing later, sharing, etc. Tags allow for quick identification and searching, and not all tags are relevant to be an album. For example, I have a collection of pictures of my cat. I have a collection of pictures of my vacation to Lappland. I'm a special person that takes his cat to Lappland for vacation, so several pictures belong in both albums. All of this is fictional, but the example stands.

**Comment by da3dsoul** [comment]
I might be wrong in my assumption of the implementation...but that's how it should be....

**Comment by skjnldsv** [comment]
No no, no worries! It's always interesting to hear from other's ideas/visions!! :hugs: 

So, how is that different than the current tags view in photos? :)

**Comment by da3dsoul** [comment]
It works? It's a separate issue, but my tags view just says, "an error occurred." Ideally, I could save and share a Tag Collection for anonymous access

**Comment by skjnldsv** [comment]
> It works? It's a separate issue, but my tags view just says, "an error occurred."

Yeah, it displays tags and all images associated with those tags :)

Please open a new issue and follow the bug issue template so we can have all the data we want (logs, browser console...)
Also please add a screenshot of your network requests to it.

Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)
