### ISSUE TITLE
SQL error unexisting column owner_id in nextcloud log files

### ISSUE THREAD

**Issue by shk3bq4d** [nextcloud/photos#1842]
**Describe the bug**
Hello,

I've got errors showing up the log files for unspecified activities generated by one or more of my users.

While my bug description is not very good, I believe it's going to be pretty easy to fix a a git blame lead to https://github.com/nextcloud/photos/commit/732193590 and @artonge . I have to assume that the correct column is `owner` instead of `owner_id`.

Edit: now that I'm looking further in git history, it probably is fixed by 8a410adc25 (@kesselb)

```
An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"owner_id\" does not exist\nLINE 1: ...T \"album_id\" FROM \"oc_photos_albums_files\" WHERE (\"owner_id\"...\n
```

**To Reproduce**
Not sure, I don't use nextcloud a lot, though I administer it for a few years

**Expected behavior**
as an admin, I am not expecting to see SQL errors in the log file

**backend version**
I just upgrade nextcloud from 24.0.12 to 25.0.7, the photos built-in app is listed as being 2.0.1

**Comment by shk3bq4d** [comment]
it is currently been addressed in #1837

**Comment by artonge** [comment]
Will be fixed by https://github.com/nextcloud/photos/pull/1837

**Comment by nickvergessen** [comment]
Also having this in our log, but photos is shipped, so can't release it, right?
