### ISSUE TITLE
ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by yunter** [nextcloud/photos#1884]
**Describe the bug**
When updated to 27.0, get JS error caches is not defined .
`ReferenceError: caches is not defined
    t PreviewService.js:32`
![image](https://github.com/nextcloud/photos/assets/164930/e6f83200-27bd-443b-a7c2-201fcef82a2c)

Browser:Safari、Chrome、Firefox

**Comment by joshtrichards** [comment]
See if this helps: https://github.com/nextcloud/photos/issues/1885#issuecomment-1593082767

You didn't provide any context or reproduction steps. This makes it challenging to resolve a bug or provide assistance. In the future, please fill out the entire bug report form. :-)

**Comment by artonge** [comment]
Some browsers do not have cache, as the error says.
The issue was fixed and will be available in the next major: https://github.com/nextcloud/photos/pull/1826/commits/1d8058a50c4c78f635e6c4d511f6e7bbc28c7233
