### ISSUE TITLE
No media images shown in Nextcloud 27.0.0 dashboard

### ISSUE THREAD

**Issue by jameswill** [nextcloud/photos#1885]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I have installed a fresh installation of Nextcloud 27.0.0 on my testing server with PHP 8.1 and Mysql 8.0

The installation went successful and when I visit the admin dashboard I can not see the default media images. (screenshot attached)

![nextcloud](https://github.com/nextcloud/server/assets/6368036/69166910-1d2e-4f2b-a124-885100b890e7)

What is causing this ? Is this a bug in the new version ?

### Steps to reproduce

1. Install the nextcloud 27.0.0 version
2. Login into the Admin panel.
3. No default media images are seen.

### Expected behavior

Default media and new uploaded images should be seen.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Cc @artonge

**Comment by artonge** [comment]
Can you check if there is any relevant logs in the browser and in the server?
Is preview generation working? Do you have previews in the Files app?

**Comment by maxcco** [comment]
I have the same issue but following an upgrade from 26.0.2

The previews are all there in the files app, and when clicking on gray thumbnails on photos it opens the picture as usual

**Comment by maxcco** [comment]
@artonge Looks like all thumbnails are creating error like this :
![image](https://github.com/nextcloud/photos/assets/67231536/e5d0b149-837a-421c-8d2c-a87af75c12bc)

If you need more tell me where to look ;)

**Comment by artonge** [comment]
@maxcco can you share your browser version and whether you are using SSL?

**Comment by maxcco** [comment]
of course here are the details 

Firefox 114.0.1 as snap package on ubuntu
ssl active and provided by let's encrypt

**Comment by artonge** [comment]
I think that accessing cache without SSL can cause this kind of issue.
A solution would be to wrap the logic in a try/catch.

Would one of you be up for the task ?

**Comment by baer1** [comment]
@artonge that was it! i have enabled ssl and its fine now.

**Comment by maxcco** [comment]
> I think that accessing cache without SSL can cause this kind of issue. For @maxcco it might be something else, but I suspect that not all of the files are served thought https. A solution would be to wrap the logic in a try/catch.
> 
> Would one of you be up for the task ?

@artonge Do you want me to open a new issue then to be able to track efficiently?

**Comment by artonge** [comment]
No that's fine.

Would it be possible for you to share an album with me so I can experience the issue myself? If so, you can send the link to louis.chemineau [at] nextcloud [dot] com

**Comment by artonge** [comment]
Images are loading properly for me on two different browsers. So it might be something with your browser's settings or extensions.

**Comment by maxcco** [comment]
@artonge I'm able to reproduce on 3 different computer (1 ubuntu 2 windows) using different network each time latest firefox (no extension and in private mode)

strangely in loads ok when using photos app but going in the folder view :confused:

**Comment by artonge** [comment]
> strangely in loads ok when using photos app but going in the folder view confused

Yes, not the same rendering logic.

**Comment by maxcco** [comment]
Everything is working fine again

Difference is for unrelated reason I needed to change subdomain and ended up renewing the ssl certificate.

**Comment by mehturt** [comment]
Apologies for commenting on a closed ticket; but is this a browser issue then? I recently upgrade one of my instances to 27.0.2 and I can't see the preview in Firefox 102 (Debian 11) but can see them in latest Chromium. I'm using SSL. Thanks.

**Comment by siccovansas** [comment]
I'm also running into this issue and I'd like to see it re-opened. I can add that the problem only happens on Firefox (currently 116.0.2) while using a private window. (I'm using valid SSL through Let's Encrypt, so I'm not sure if that is related in any way.)
