### ISSUE TITLE
When I upload certain specific photos, scrolling photos stops loading

### ISSUE THREAD

**Issue by Ador-able** [nextcloud/photos#1899]
When the above two photos appear in scrolling, due to nextcloud's inability to generate thumbnails, the console displays 404. After scrolling down for a short period, it will be found that the photos have stopped loading. After continuous attempts, I have determined that as long as these two images are removed, they can be loaded normally and uninterrupted during scrolling

My nextcloud version is 26.0.3

![软件架构设计思维导图](https://github.com/nextcloud/photos/assets/17660606/49e5b8dd-bc2b-4f71-b66e-e0ea8ff0f24c)
![计算机组成](https://github.com/nextcloud/photos/assets/17660606/7b7a51d3-446e-4b1c-a96a-f5684a7de25c)

**Comment by joshtrichards** [comment]
Hi @Ador-able - Thanks for the report. Can you provide the corresponded stack trace entry from your `nextcloud.log` for these 404s?

**Comment by Ador-able** [comment]
@joshtrichards This error cannot be replicated when I upgrade Nextcloud to 27.0.0
