### ISSUE TITLE
NC 18 JPG Images not loading when opened in a directory with special chars

### ISSUE THREAD

**Issue by tk7936** [nextcloud/photos#190]
NC 18.01 RC2
Photos 1.0

When i open a jpg within a directory that contains NO special chars for example " ", "(", ")". "~" ect,
the image opens, if it DOES contain special chars the image viewer opens and just loads for ever without displaying the image.

**Comment by Kourai** [comment]
Yep, same here, although I'm not sure if it trigger by " ", "(", ")". "~", or maybe by accent ("é", "è", "à" and all the lovely accent we french people use a lot!)

**Comment by Boki4d** [comment]
I've reported an similar issue here:
https://github.com/nextcloud/photos/issues/301

**Comment by skjnldsv** [comment]
We're talking about opening an image, right? Not browsing the photos in the Photos app, correct?

**Comment by tk7936** [comment]
yes exactly

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/viewer/issues/415
