### ISSUE TITLE
Unable to select photos if under the folders tab

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/photos#1943]
**Describe the bug**

**To Reproduce**
1. Go to Photos app
2. Click on  Folders
3. Select the folder that has the photos you want
4. No option to select photos or all photos

**Expected behavior**
![image](https://github.com/nextcloud/photos/assets/59488153/a4f6ee63-301e-4b49-96b7-93488b8dea60)

Server NC 27.0.0
Photos APP 2.3.0

**Comment by joshtrichards** [comment]
Reproduced in `master/2.4.0` although I think this is an enhancement request rather than a bug. Even in the old (1.x) Photos app this wasn't possible.
