### ISSUE TITLE
Fallo con las imágenes que se llaman igual.

### ISSUE THREAD

**Issue by David-Rodriguez-cabrera** [nextcloud/photos#2018]
Si en tu nextcloud tienes una imagen en un sitio y en otro, que se llamen igual, si te vas a fotos, y abres última que subiste, se abrirá la primera que subiste, y además si la descargas estando abierta, se descargará también la primera que subiste, y si la descargas sin abrirla, o se intenta descargar un archivo php, o se descarga la imagen que es aunque le pone una _ delante.

Pasos a reproducir:
1. Sube dos o más imágenes con el nombre y extensión iguales a nextcloud.
2. Ve a la aplicación fotos.
3. Abre la última imagen que acabas de subir con el nombre igual a otras.
4. Verás como se abre la primera imagen y no la segunda.
5. Intenta descargarla y se descargará la primera imágen.
6. Intenta descargarla sin abrirla y verás que o intenta descargar un archivo php, o se descargará la imágenes que es con una _ delante.

Versiones:
Nextcloud: 27.0.1
Photos: 2.3.0

**Comment by miaulalala** [comment]
Hi David, can you please rewrite this in English? Not everyone at our company speaks Spanish. Thanks!

**Comment by David-Rodriguez-cabrera** [comment]
I'm going to do it with google translate.

If in your nextcloud you have an image on one site and on another, that have the same name, if you go to photos, and open the last one you uploaded, the first one you uploaded will open, and also if you download it while it is open, it will also download the The first one you uploaded, and if you download it without opening it, either you try to download a php file, or you download the image that it is even if you put a _ in front of it.

Steps to reproduce:

1. Upload two or more images with the name and extension equal to nextcloud.
2. Go to the photos app.
3. Open the last image you just uploaded with the same name as others.
4. You will see how the first image opens and not the second.
5. Try to download it and the first image will be downloaded.
6. Try to download it without opening it and you will see that either it tries to download a php file, or it will download the images that are with a _ in front of them.

Versions:
Nextcloud: 27.0.1
Photos: 2.3.0

**Comment by kesselb** [comment]
Hi,

As you already figured, likely a duplicate of https://github.com/nextcloud/viewer/issues/484
