### ISSUE TITLE
Wrong orientation of images when selecting "Your albums" or "Shared albums"

### ISSUE THREAD

**Issue by kitzler-walli** [nextcloud/photos#202]
### Steps to reproduce
Clicking an image with orientation information (taken on iPhone) within " Your albums" or "Shared albums" shows the image with the wron orientation.
The preview of the image is correct - the bug shows when clicking the image.
When selecting the same image in "Your photos" the orientation is correct.

### Expected behaviour
The image should show the correct orientation in every part of the gallery.

### Actual behaviour
"Your albums" and "Shared albums" show image with wrong orientation despite preview being correct.

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, redis, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_antivirus: 2.2.1
 - files_fulltextsearch: 1.4.1
 - files_pdfviewer: 1.7.0
 - files_reader: 1.2.3
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.4
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_external
 - files_mindmap
 - notes
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**Comment by skjnldsv** [comment]
Hey!
This is not an issue with the app but most likely with the photo itself :)
Could you check the issue #176 and see if this is behaving like you?

**Comment by kitzler-walli** [comment]
When selecting the same image in "Your photos" the orientation is correct.
So it's an issue with the photos app.

**Comment by skjnldsv** [comment]
Thanks for the help :)
Could you share screenshots?

**Comment by kitzler-walli** [comment]
![Screenshot 2020-02-24 at 10 26 29](https://user-images.githubusercontent.com/1926992/75140999-51a30780-56f0-11ea-8658-4513eed1bfca.png)
Left is "Your Photos" - right is "Your albums"

**Comment by skjnldsv** [comment]
I'll admit this is a really intriguing bug :)
Could you share the image with me?

**Comment by kitzler-walli** [comment]
Here's the link to the file: https://kwnext.hopto.me/s/jBBSjRTEPowxHBo
(funny - even the public link shows it with correct orientation - link expires tomorrow)

**Comment by skjnldsv** [comment]
Got it, Thanks!

**Comment by skjnldsv** [comment]
SO thius is because the albums is loading the file directly from dav while the timeline is properly loading the preview

**Comment by GreatEmerald** [comment]
I ran into this bug as well. For any EXIF-rotated image, Photos shows it in the incorrect orientation, but the preview image is correct, and if at the sidebar you copy the internal link and open it (so it opens with the Files app), the orientation there is also fine.

Here's an example:
![20190604_181803](https://user-images.githubusercontent.com/726893/79242806-11047680-7e75-11ea-91b8-f94d770f24f6.jpg)

Indeed as in #176 GitHub shows it incorrectly, while opening it in a new tab shows it correctly. That just shows that GitHub also has this bug... The metadata is correct, it should be software-rotated 90°, as per `exiftool`:
```
Orientation                     : Rotate 90 CW
```

**Comment by koarlmichael** [comment]
Also have the problem with photos from my Olympus EM 10 II. The photos are displayed correctly in the viewer and in the preview. In the full screen of the photo app, however, they are not displayed in portrait format. Enclosed the photo with the Exif data.

**Comment by koarlmichael** [comment]
![PA050017](https://user-images.githubusercontent.com/22660247/80092221-adf49d00-8562-11ea-8880-c537e87052a4.JPG)

**Comment by zdleaf** [comment]
I have the same issue. Photo shows with correct orientation when viewed from Your Photos, and also in the image previews in Your Albums. However when clicking to view from Your Albums, somes images are incorrectly rotated.

**Comment by koarlmichael** [comment]
Issue is also in version NC 19 RC3. As I said, in the normal photo view everything is ok. As soon as you go into the albums, the portrait pictures are in landscape format.

**Comment by skjnldsv** [comment]
Please use the github reactions

**Comment by skjnldsv** [comment]
See instead, this is the same root cause https://github.com/nextcloud/photos/issues/260

**Comment by kitzler-walli** [comment]
How are these two issues linked?? One deals with download of an image, this one here deals with the wrong orientation of images, which was correctly shown a few versions back.

**Comment by skjnldsv** [comment]
Loading directly the images in browser ignores the EXIF properties within it, while our preview generation automatically takes it into account and correct it.
