### ISSUE TITLE
Honor .nomedia file or similar

### ISSUE THREAD

**Issue by newhinton** [nextcloud/photos#203]
Currently (afaik) all images are beeing shown. That leads to some images beeing shown twice when they are in a thumbnail folder. There could be a way to automatically hide folders/images that are in a folder beginning with a dot (.thumbnails) or if the folder contains a .nomedia file. This could be toggleable, like with 'show hidden files' in the files app. 

A more elaborate way would be to manage exclusions via gui so that a user could choose a folder to be excluded, but imho honoring a nomedia file or the preceeding dot should suffice.

**Comment by skjnldsv** [comment]
This is already there #159
