### ISSUE TITLE
Cannot Load Tag View

### ISSUE THREAD

**Issue by da3dsoul** [nextcloud/photos#204]
**Describe the bug**
Tags View is Broken (An Error Occurred)

**To Reproduce**
1. Have tags and images
2. Open Photos
3. Click Tagged Photos
4. Watch it not work....

**Expected behavior**
IDK it working? I don't really know what it's supposed to look like.

**Screenshots**
![chrome_2020-02-24_07-01-59](https://user-images.githubusercontent.com/5205810/75151106-e1868880-56d3-11ea-9439-671b2b0966dd.png)

**Desktop (please complete the following information):**
 Version and platform agnostic. I tried on Chrome for Windows, Android, and Firefox on Windows.
**Browser log**
```
| (anonymous) | @ | Tags.vue:199
-- | -- | -- | --
| c | @ | Multiselect.js:119
| (anonymous) | @ | Multiselect.js:119
| forEach.t.<computed> | @ | Multiselect.js:119
| Fn | @ | photos.js?v=4491e646-4:487
| a | @ | photos.js?v=4491e646-4:487
| Promise.then (async) |   |  
| Fn | @ | photos.js?v=4491e646-4:487
| a | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | Tags.vue:176
| (anonymous) | @ | Tags.vue:167
| c | @ | Multiselect.js:119
| (anonymous) | @ | Multiselect.js:119
| forEach.t.<computed> | @ | Multiselect.js:119
| Fn | @ | photos.js?v=4491e646-4:487
| a | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | photos.js?v=4491e646-4:487
| (anonymous) | @ | Tags.vue:77
| zt | @ | vue.runtime.esm.js:1854
| en | @ | vue.runtime.esm.js:4219
| t | @ | vue.runtime.esm.js:4043
| In.$mount | @ | vue.runtime.esm.js:8415
| init | @ | vue.runtime.esm.js:3118
| n | @ | vue.runtime.esm.js:3301
| (anonymous) | @ | vue.runtime.esm.js:5978
| l | @ | vue.runtime.esm.js:5925
| p | @ | vue.runtime.esm.js:6053
| l | @ | vue.runtime.esm.js:5954
| Show 45 more frames
```

**Additional context**
I have a reverse proxy with nginx, but I see no errors related to it. The nextcloud log has nothing about the attempt to load the tag view.

**Comment by da3dsoul** [comment]
Here's the response of /systemtags. I prettified it to be easier to open, as it came in only 2 lines for all 7MB of XML. The response header looks like:
```
HTTP/1.1 207 Multi-Status
Server: nginx/1.14.0 (Ubuntu)
Date: Mon, 24 Feb 2020 12:37:11 GMT
Content-Type: application/xml; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';
Vary: Brief,Prefer
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, nc-calendar-search, nc-enable-birthday-calendar
Referrer-Policy: strict-origin
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
```
[systemtag-response.txt](https://github.com/nextcloud/photos/files/4244586/systemtag-response.txt)

**Comment by skjnldsv** [comment]
Thanks a lot :)
Are you familiar with javascript debugging on browsers?

**Comment by da3dsoul** [comment]
I'm not familiar, but I am a programmer (just not a webdev). If you can point me in the right direction, I can follow some instructions.

**Comment by skjnldsv** [comment]
Great!
When clicking the fileUtils:96 link on your browser console, you will see the source file.
Clicking the like where it throw the error will add a breakpoint
![image](https://user-images.githubusercontent.com/14975046/75161329-e2dba380-571b-11ea-8030-6503946f6ef9.png)


Refresh the page and the script will hang on exception at this line.
You will be able to go to the console and hover/get the fileInfo1 & fileInfo2 objects that trigger the error.
![Capture d’écran_2020-02-24_15-40-37](https://user-images.githubusercontent.com/14975046/75161419-11597e80-571c-11ea-8b46-0ecd0e44fb84.png)

Now, you can save them as variable by right clicking the local scope on the right
![Capture d’écran_2020-02-24_15-42-07](https://user-images.githubusercontent.com/14975046/75161546-4534a400-571c-11ea-90f5-65ca1d3459ae.png)
Then you will be able to copy them and paste them here please
![image](https://user-images.githubusercontent.com/14975046/75161625-65fcf980-571c-11ea-87f8-1c6a5b421467.png)

**Comment by da3dsoul** [comment]
Will do. Busy at the very moment, but will get to it today.

**Comment by skjnldsv** [comment]
@da3dsoul it can wait a few days, do not worry :)

**Comment by da3dsoul** [comment]
Better Tag Views and Sharing are features that I've wanted since before I first heard of nextcloud. If this gets me closer to it without needing to try to learn a huge new code base and js and vue.js and whatever else this uses, then yeah I'll do whatever I can.

**Comment by da3dsoul** [comment]
```
temp1
{filename: "/systemtags/23079", basename: 23079, lastmod: undefined, size: 0, type: "file", …}filename: "/systemtags/23079"basename: 23079lastmod: undefinedsize: 0type: "file"etag: nullmime: ""id: 23079displayName: "+15"userVisible: trueuserAssignable: truecanAssign: true__proto__: constructor: ƒ Object()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()hasOwnProperty: ƒ hasOwnProperty()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toString: ƒ toString()valueOf: ƒ valueOf()toLocaleString: ƒ toLocaleString()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
temp2
{filename: "/systemtags/24372", basename: 24372, lastmod: undefined, size: 0, type: "file", …}filename: "/systemtags/24372"basename: 24372lastmod: undefinedsize: 0type: "file"etag: nullmime: ""id: 24372displayName: "#"userVisible: trueuserAssignable: truecanAssign: true__proto__: Object
```

**Comment by skjnldsv** [comment]
can you screenshot me the local scope like my screenshot too?

**Comment by skjnldsv** [comment]
> EDIT: It looks like it only serializes things that I expanded. They both have the proto stuff in the top one.

You can use JSON.stringify to have the full object as string and paste it here if you want :)

**Comment by da3dsoul** [comment]
All of the info is the same, just more nicely organized
```
JSON.stringify(temp1)
"{"filename":"/systemtags/23079","basename":23079,"size":0,"type":"file","etag":null,"mime":"","id":23079,"displayName":"+15","userVisible":true,"userAssignable":true,"canAssign":true}"
JSON.stringify(temp2)
"{"filename":"/systemtags/24372","basename":24372,"size":0,"type":"file","etag":null,"mime":"","id":24372,"displayName":"#","userVisible":true,"userAssignable":true,"canAssign":true}"
```
The code being executed reads `fileInfo1[key].localeCompare(fileInfo2[key], OC.getLanguage())` and this returns properly:
```
> temp1["displayName"].localeCompare(temp2["displayName"])
  1
> OC.getLanguage()
  "en"
> temp1["displayName"].localeCompare(temp2["displayName"], "en")
  1
```
key = "displayName", so that should be working as far as I can tell. I don't know if javascript has extension methods or something that might not be loaded, thereby throwing a MethodNotFoundException on localCompare. If it was C#, that would be first guess here.

**Comment by da3dsoul** [comment]
It occurs to me that those are just the first variables in an enumerable, not the ones that threw the exception. I don't know how I can stop it there without editing the source, and after looking into it, due to minification and other optimization BS, it's not happening. With javascript being a dynamically typed language, it's hard to say what the actual variables are. In C#, you'd just null check it once you know that everything else is working. I don't know where to go from here.

**Comment by skjnldsv** [comment]
> It occurs to me that those are just the first values in an enumerable, not the ones that threw the exception.

Right, you have quite a lot of tags, so just doing step by step is going to take forever.
Maybe the caught on exception will work
Disable the previous inline breakpoint and use this 
![Capture d’écran_2020-02-27_10-59-42](https://user-images.githubusercontent.com/14975046/75433567-6f6ea780-5950-11ea-9438-66f905886ae7.png)

It should breakpoint on the exception. Same process after that

**Comment by skjnldsv** [comment]
Though there might be multiple exception coming from other scripts, you can pass the current exception if this is not the one you're looking for with the "resume" button
![Capture d’écran_2020-02-27_11-02-25](https://user-images.githubusercontent.com/14975046/75433699-a9d84480-5950-11ea-8c49-8633f57d9b89.png)

**Comment by skjnldsv** [comment]
Well, after thoughts, it's probably going to throw tons of stuff from all over the place. Let me think of a better solution

**Comment by skjnldsv** [comment]
@da3dsoul can you try this debug release?
[photos.tar.gz](https://github.com/nextcloud/photos/files/4260967/photos.tar.gz)

It should load the tag view but output some data on the console on error.
Make sure all debug level are enabled
![Capture d’écran_2020-02-27_11-11-05](https://user-images.githubusercontent.com/14975046/75434473-e0fb2580-5951-11ea-8b53-13a8a8ec1998.png)

**Comment by da3dsoul** [comment]
It appears to be truncating the object. It doesn't have the name of the tag...or the name doesn't exist on the object, which would definitely cause the error.
[da3dsoul.shokoanime.com-1582920437002.log](https://github.com/nextcloud/photos/files/4268937/da3dsoul.shokoanime.com-1582920437002.log)

**Comment by skjnldsv** [comment]
> It appears to be truncating the object.

you can expend the object by clicking on it :)
This is making progress, it indeed seems like some tags are broken, let's see :thinking: 

Please only share the part where it display the error and the debug line just above:

```js
fileUtils.js:100 displayName {filename: "/systemtags/14234", basename: 14234, lastmod: undefined, size: 0, type: "file", …} {filename: "/systemtags/24066", basename: 24066, lastmod: undefined, size: 0, type: "file", …}
fileUtils.js:99 TypeError: fileInfo1[key].localeCompare is not a function
    at sortCompare (fileUtils.js:97)
    at systemtags.js:39
    at Array.sort (<anonymous>)
    at Store.updateTags (systemtags.js:38)
    at wrappedMutationHandler (vuex.esm.js:740)
    at commitIterator (vuex.esm.js:392)
    at Array.forEach (<anonymous>)
    at vuex.esm.js:391
    at Store._withCommit (vuex.esm.js:522)
    at Store.commit (vuex.esm.js:390)

```

**Comment by skjnldsv** [comment]
> EDIT: Also idk if there was an error in your quick debugging code, but I need to kill chrome when running that, or it'll think about something forever and chrome won't close the tab.

Probably outputting too much data than your system can handle, sorry about that!
Thanks a lot for the help :)

**Comment by da3dsoul** [comment]
I shared the full console log with verbose enabled. There is no more.

**Comment by skjnldsv** [comment]
Yes, but the console is interractive, you can expand the truncated objects.
But I might have found the issue. I'll see that on monday :)

**Comment by da3dsoul** [comment]
I'll try that.

**Comment by skjnldsv** [comment]
Can you try this one? [photos.tar.gz](https://github.com/nextcloud/photos/files/4270518/photos.tar.gz)

**Comment by da3dsoul** [comment]
Haven't tried that one yet, as I just saw it.
I couldn't expand the console any more, but I could put a better breakpoint in now. I think I see the issue, as well.

Note that displayName is an integer for some reason. My guess is that an automatic cast happened somewhere, as the tag is a string representation of the number. Gotta love dynamic typing \</sarcasm\>.
![chrome_1hsuF58at5](https://user-images.githubusercontent.com/5205810/75610671-46315100-5ae1-11ea-9129-14e35b0f6619.png)

**Comment by skjnldsv** [comment]
> Note that displayName is an integer for some reason. My guess is that an automatic cast happened somewhere, as the tag is a string representation of the number

Yes, this is what I assumed too, this is what the test archive above was built for :)

**Comment by da3dsoul** [comment]
I have a perpetual spinning circle and chrome asks to close or wait. I said wait several times, but it shows no intention of ever finishing. I don't know how it's set up, but I have over 30,000 images with several thousand tags.... Lazy loading and subdirectories of some kind are necessary for that amount of data.

**Comment by da3dsoul** [comment]
I don't know if this is related, but it could be https://github.com/nextcloud/server/issues/17499

**Comment by skjnldsv** [comment]
Well, it should not be that hard to load anyway :thinking:

**Comment by da3dsoul** [comment]
Okay... So I can't load the performance profiler. Once it starts, the only thing I can see about it is that the call to system tags finished. I can interact with the profiler, but it never loads a recorded profile from the page, and I can't save it to try again without the page trying to load in the background. I don't even know what to try. Can you put it back to not having the try/catch, but still forcing displayName to string? Maybe that'll work better.
Another thing you could try is to limit the list to 500 items for the sake of testing, then if it works, we'll see about loading all of them.

**Comment by skjnldsv** [comment]
Hum, the test release doesn't have the try catch.
Have you cleared your cache?

**Comment by da3dsoul** [comment]
Oh. I didn't look. I just assumed it was still there.... Well, then that second option might be a way to see what's going on....

**Comment by skjnldsv** [comment]
Damn, that is strange.
I guessed you tried without the console opened?

**Comment by da3dsoul** [comment]
Tried both, yeah. Made sure verbose logging was off. Checked Chrome's CPU and Memory usage, and it rises to 400MB, garbage collects, then rises again. At least one thread is always at 100%, but never more than 2 threads.

**Comment by skjnldsv** [comment]
And it doesn't display, right?
No errors in the console?

**Comment by da3dsoul** [comment]
It does show nextcloud, but the main area has a spinning circle. None of the other parts of the page respond while it's trying to load. No errors

**Comment by skjnldsv** [comment]
Damn!
Okay, I'll try to see what I can do here

**Comment by Mikescops** [comment]
This is likely fixed with the current master, cc @skjnldsv.

Please reopen after N21 release if it's still here for you.
