### ISSUE TITLE
--local --dst_bootimg vendor_boot-debug.img \         --ramdisk_add file1:path/in/dst_bootimg/file1 \         --ramdisk_add file2:path/in/dst_bootimg/file2 u0_a320@localhost ~> repack_bootimg -h--local --dst_bootimg vendor_boot-debug.img \         --ramdisk_add file1:path/in/dst_bootimg/file1 \         --ramdisk_add file2:path/in/dst_bootimg/file2 u0_a320@localhost ~> repack_bootimg -h

### ISSUE THREAD

**Issue by Ra7aal0000** [nextcloud/photos#2048]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by joshtrichards** [comment]
What's this? A mistaken submission? Closing for now. Feel free to follow-up and update your submission if it was meant to be legitimate.
