### ISSUE TITLE
Can not accees to Your Albums

### ISSUE THREAD

**Issue by poltrian** [nextcloud/photos#210]
If got an error when i click to Your Albums. it shows an error occurred. If have upgraded form Nextcloud 17.0.3 to 18.01

Cloud someone help me please?

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by poltrian** [comment]
Hi John,

I found the reason. With external storage i have had add a webdav folder, If i deleted the Connection it works. Seems its a Problem with external drives

**Comment by skjnldsv** [comment]
Ah, yes, there is a fix for it here #207 that will ignore failed ext storages

**Comment by skjnldsv** [comment]
Thanks for your help @poltrian :)
