### ISSUE TITLE
Details icon seems under-sized

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/photos#2140]
In 28beta3 the Details icon seems too small...
![Screenshot_20231120_162857 (2)](https://github.com/nextcloud/photos/assets/551757/393bd675-70ac-434e-bfce-97662e593510)

**Comment by artonge** [comment]
It is the icon chosen by @nextcloud/designers: https://pictogrammers.com/library/mdi/icon/information-slab-symbol/
The can recommend another one if needed.

**Comment by nimishavijay** [comment]
Ah I think the icon itself is too small... we could go with the [info outline](https://fonts.google.com/icons?selected=Material%20Icons%3Ainfo_outline%3A) MDI icon, since it's the official Google MDI icon there shouldn't be any discrepancies with sizes :)
