### ISSUE TITLE
Dynamic load of photos on scroll

### ISSUE THREAD

**Issue by pedrxd** [nextcloud/photos#215]
**Is your feature request related to a problem? Please describe.**
On large folder up to 1000 Photos the app tries to load all photos. The first problem is the overload of the navegator when trying to render a webpage with a "infinite" scroll bar. The second problem is the heavy load to the server trying to generate all thumbnails. The server get full of work and petitions like click on a photo keep freezing until a worker is available, server seem to be down. But is generating thumbnails!.

**Describe the solution you'd like**
A good solution was like the older gallery. Only the first N pictures will be load, if the user still scrolling, the app will load more photos.

**Comment by skjnldsv** [comment]
Hey :)

So, the app isn't really trying to load all photos. I'm guessing you're talking about the timeline view, right?
We have a pagination enabled and we only load as many rows your screen can fit + 1 extra (after that once the last loaded row has reached the bottom, it load the next xx rows) https://github.com/nextcloud/photos/blob/30be4e6d18e4fb121f3035aced004323fad221e0/src/components/VirtualGrid.vue#L156-L157



> The second problem is the heavy load to the server trying to generate all thumbnails

This is can indeed be an issue. Which is also present on the files app.
We strongly suggest you setup a preview pre-generation with the previewgenerator app (there are tutorials for this)



> The first problem is the overload of the navegator when trying to render a webpage with a "infinite" scroll bar

I'm concern about this. Could you detail your system? (Server and client)
Performance is one of the trickiest part of such apps and we definitely have room for improvements, which I'd gladely love to do :rocket:

**Comment by TomG736** [comment]
I have this too, I sync my photos from my phone to nextcloud. As such I have 1277 images in one folder. When I open the folder in photos (https://files.domain.com/apps/photos/albums/InstantUpload%2FCamera), a request is made for all 1277 previews. As I'm running this on a Pi 4 the server instantly gets swamped and stops responding. 
![image](https://user-images.githubusercontent.com/1608920/75634222-aa4c3600-5c03-11ea-97c2-fe938cb570b6.png)

**Comment by skjnldsv** [comment]
Ah right, the albums view doesn't have the virtual grid :)
Let's see what we can do here

**Comment by pedrxd** [comment]
Yes, I forgot said that the problem is only on album. The main viewer work correctly.

**Comment by Mardiie** [comment]
I was just looking for a topic about this issue. 
I'm experiencing the same thing.
A fix would be epic!
Thanks.

**Comment by Mikescops** [comment]
This is fixed by #480.
