### ISSUE TITLE
NC 28 Photos not showing up

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/photos#2188]
**Describe the bug**
Upgraded to NC28 RC4 from NC27 and looks like the photos app is broken for me. It will not show all the photos in the default location photos folder. I changed the default location from /Photos to / since i have photos outside of the /Phone folder and still nothing. 

**To Reproduce**
1. Go to 'Photos'
2. Click on 'All Media'

**Expected behavior**
Should show all photos
**Screenshots**
![image](https://github.com/nextcloud/photos/assets/59488153/fdcd7472-9b70-4377-8f0e-58d3fed06396)
.

**Comment by ovcacikt** [comment]
I have similar issue with Photos after the upgrade to NC28. Seems like the the app picks only photos from /Photos. I changed to / directory, but the app still shows only photos placed in /Photos.

![image](https://github.com/nextcloud/photos/assets/153866016/ab4b5d85-5a02-4443-bc1e-82ef6951761b)

**Comment by AndyXheli** [comment]
Closing can't replicate issue anymore
