### ISSUE TITLE
Incomplete results on loading up latest version

### ISSUE THREAD

**Issue by valdearg** [nextcloud/photos#2195]
**Describe the bug**
When loading the Photos tab, this would typically load the most recently added photos to the system. In version 2.4.0 with NextCloud 28.0.0.0 however, a lot of older results are coming up, e.g. items from 2022.

**To Reproduce**
1. Go to Photos
2. Wait for the page to load.
3. Check if recent items are there.

**Expected behavior**
A selection of images, ordered by recently added. 

**Screenshots**
![image](https://github.com/nextcloud/photos/assets/2789033/8c59d819-b94e-40ab-baa2-232ae05eee29)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox and Edge
 - Version: 120.0.1

**Browser log**
```Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. rc2Contentscript.js:247:10
TypeError: document.body is null rc2Contentscript.js:249:77
TypeError: document.body is null 2 rc2Contentscript.js:249:77
JQMIGRATE: Migrate is installed, version 3.4.1 jquery-migrate.min.js:2:980
Global search initialized! GlobalSearch.vue:51
OCA.Files.Sidebar initialized Sidebar.js:36:10
OCA.Comments.View initialized comments-app.js:32:8
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:33:10
[WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: "viewer", uid: "valdearg", level: 2, ignoredMimes: (2) […] }
ConsoleLogger.js:71:18
OCA.Viewer initialized Viewer.js:81:10
session heartbeat polling started session-heartbeat.js:103:9
Search providers 
Array(5) [ {…}, {…}, {…}, {…}, {…} ]
GlobalSearchModal.vue:243
Contacts 
Array []
GlobalSearchModal.vue:247
Proxying an event bus of version 3.1.0 with 1.3.0 index.es.js:2337:14
Registering notifications container as a menu NotificationsApp.vue:219
Notifications permissions granted NotificationsApp.vue:453
Polling interval updated to 30000 NotificationsApp.vue:416
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:275
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34
```

**Additional context**
The results seem to be different each time, selecting a different set of images each time the browser cache is refreshed.

```<?xml version="1.0" encoding="UTF-8"?>
			<d:searchrequest xmlns:d="DAV:"
				xmlns:oc="http://owncloud.org/ns"
				xmlns:nc="http://nextcloud.org/ns"
				xmlns:ns="https://github.com/icewind1991/SearchDAV/ns"
				xmlns:ocs="http://open-collaboration-services.org/ns">
				<d:basicsearch>
					<d:select>
						<d:prop>
							
	<d:getcontentlength />
	<d:getcontenttype />
	<d:getetag />
	<d:getlastmodified />
	<d:resourcetype />
	<nc:face-detections />
	<nc:face-preview-image />
	<nc:metadata-photos-size />
	<nc:metadata-photos-original_date_time />
	<nc:metadata-files-live-photo />
	<nc:has-preview />
	<nc:realpath />
	<nc:hidden />
	<oc:favorite />
	<oc:fileid />
	<oc:permissions />
	<nc:nbItems />

						</d:prop>
					</d:select>
					<d:from>
						<d:scope>
							<d:href>/files/valdearg/</d:href>
							<d:depth>infinity</d:depth>
						</d:scope>
					</d:from>
					<d:where>
						<d:and>
							<d:or>
								
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/png</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/jpeg</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/heic</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/webp</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>video/mp4</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>video/quicktime</d:literal>
		</d:eq>
	
							</d:or>
							
							
						</d:and>
					</d:where>
					<d:orderby>
						<d:order>
							<d:prop><nc:metadata-photos-original_date_time/></d:prop>
							<d:descending/>
						</d:order>
					</d:orderby>
					<d:limit>
						<d:nresults>200</d:nresults>
						<ns:firstresult>0</ns:firstresult>
					</d:limit>
				</d:basicsearch>
			</d:searchrequest>
```

The following are the dates of the files in the response

```Fri, 26 Mar 2021 21:59:05 GMT
Sat, 27 Oct 2018 11:56:51 GMT
Sat, 27 Oct 2018 11:47:12 GMT
Sat, 27 Oct 2018 11:01:05 GMT
Sat, 27 Oct 2018 10:37:37 GMT
Sat, 27 Oct 2018 08:55:19 GMT
Sat, 27 Oct 2018 08:47:25 GMT
Sat, 27 Oct 2018 08:38:28 GMT
Sat, 27 Oct 2018 07:46:05 GMT
Sat, 27 Oct 2018 06:48:24 GMT
Sat, 27 Oct 2018 06:48:23 GMT
Sat, 27 Oct 2018 06:48:22 GMT
Sat, 27 Oct 2018 05:26:47 GMT
Fri, 26 Oct 2018 22:35:44 GMT
Fri, 26 Oct 2018 19:32:52 GMT
Fri, 26 Oct 2018 19:12:34 GMT
Fri, 26 Oct 2018 18:35:29 GMT
Fri, 26 Oct 2018 15:00:09 GMT
Fri, 26 Oct 2018 15:00:08 GMT
Fri, 26 Mar 2021 21:59:11 GMT
Mon, 12 Apr 2021 13:44:53 GMT
Fri, 26 Oct 2018 15:00:08 GMT
Fri, 26 Oct 2018 15:00:07 GMT
Fri, 26 Oct 2018 15:00:05 GMT
Fri, 26 Oct 2018 15:00:04 GMT
Fri, 26 Oct 2018 15:00:04 GMT
Fri, 26 Oct 2018 15:00:02 GMT
Fri, 26 Oct 2018 14:30:26 GMT
Fri, 26 Oct 2018 14:30:26 GMT
Fri, 26 Oct 2018 13:49:39 GMT
Fri, 26 Oct 2018 12:18:30 GMT
Fri, 26 Oct 2018 12:17:12 GMT
Fri, 26 Oct 2018 12:16:37 GMT
Fri, 26 Oct 2018 12:14:57 GMT
Fri, 26 Oct 2018 12:12:41 GMT
Fri, 26 Oct 2018 10:03:00 GMT
Fri, 26 Oct 2018 08:45:48 GMT
Fri, 26 Oct 2018 08:44:27 GMT
Fri, 23 Sep 2022 18:09:55 GMT
Sun, 21 Feb 2021 23:20:11 GMT
Thu, 25 Oct 2018 21:50:43 GMT
Thu, 25 Oct 2018 21:43:07 GMT
Thu, 25 Oct 2018 21:42:31 GMT
Thu, 25 Oct 2018 20:02:14 GMT
Thu, 25 Oct 2018 20:01:26 GMT
Thu, 25 Oct 2018 19:13:25 GMT
Thu, 25 Oct 2018 10:23:03 GMT
Thu, 25 Oct 2018 09:01:43 GMT
Thu, 25 Oct 2018 07:38:33 GMT
Thu, 25 Oct 2018 07:38:05 GMT
Thu, 25 Oct 2018 07:36:32 GMT
Thu, 25 Oct 2018 02:05:53 GMT
Wed, 24 Oct 2018 19:54:25 GMT
Wed, 24 Oct 2018 19:33:31 GMT
Wed, 24 Oct 2018 19:33:29 GMT
Wed, 24 Oct 2018 19:31:15 GMT
Wed, 24 Oct 2018 18:10:02 GMT
Wed, 24 Oct 2018 17:41:42 GMT
Wed, 24 Oct 2018 17:41:42 GMT
Wed, 24 Oct 2018 17:41:42 GMT
Tue, 28 Jun 2022 16:47:29 GMT
Fri, 16 Apr 2021 03:39:16 GMT
Wed, 24 Oct 2018 17:41:42 GMT
Wed, 24 Oct 2018 17:22:33 GMT
Wed, 24 Oct 2018 17:22:33 GMT
Wed, 24 Oct 2018 17:22:33 GMT
Wed, 24 Oct 2018 17:22:33 GMT
Wed, 24 Oct 2018 17:06:24 GMT
Wed, 24 Oct 2018 16:42:16 GMT
Wed, 24 Oct 2018 16:42:16 GMT
Wed, 24 Oct 2018 16:42:02 GMT
Wed, 24 Oct 2018 16:41:56 GMT
Wed, 24 Oct 2018 16:41:55 GMT
Wed, 24 Oct 2018 16:41:26 GMT
Wed, 24 Oct 2018 16:41:00 GMT
Wed, 24 Oct 2018 16:39:59 GMT
Wed, 24 Oct 2018 16:39:18 GMT
Wed, 24 Oct 2018 16:39:16 GMT
Wed, 24 Oct 2018 16:38:50 GMT
Wed, 24 Oct 2018 16:38:48 GMT
Mon, 06 Sep 2021 18:17:44 GMT
Fri, 26 Mar 2021 21:59:49 GMT
Wed, 24 Oct 2018 16:38:20 GMT
Wed, 24 Oct 2018 16:38:05 GMT
Wed, 24 Oct 2018 16:37:34 GMT
Wed, 24 Oct 2018 16:37:26 GMT
Wed, 24 Oct 2018 16:37:18 GMT
Wed, 24 Oct 2018 16:36:55 GMT
Wed, 24 Oct 2018 16:36:48 GMT
Wed, 24 Oct 2018 16:36:46 GMT
Sun, 20 Nov 2022 10:09:15 GMT
Wed, 24 Oct 2018 16:36:43 GMT
Wed, 24 Oct 2018 16:36:35 GMT
Wed, 24 Oct 2018 16:36:34 GMT
Wed, 24 Oct 2018 16:36:28 GMT
Wed, 24 Oct 2018 16:36:24 GMT
Wed, 24 Oct 2018 16:36:16 GMT
Wed, 24 Oct 2018 16:36:06 GMT
Fri, 26 Mar 2021 21:59:56 GMT
Wed, 24 Oct 2018 16:34:06 GMT
Wed, 24 Oct 2018 16:33:44 GMT
Wed, 24 Oct 2018 16:33:42 GMT
Fri, 23 Sep 2022 18:09:55 GMT
Sat, 10 Jul 2021 11:50:42 GMT
Fri, 26 Mar 2021 22:00:03 GMT
Sun, 21 Feb 2021 17:47:27 GMT
Mon, 15 Feb 2021 03:18:30 GMT
Sat, 20 Feb 2021 18:15:40 GMT
Sat, 20 Feb 2021 01:57:55 GMT
Sat, 13 Feb 2021 20:27:41 GMT
Sat, 20 Feb 2021 01:57:55 GMT
Fri, 19 Feb 2021 19:17:43 GMT
Fri, 19 Feb 2021 02:46:58 GMT
Wed, 24 Oct 2018 16:33:08 GMT
Wed, 24 Oct 2018 16:32:50 GMT
Wed, 24 Oct 2018 16:32:50 GMT
Sat, 13 Feb 2021 03:23:36 GMT
Wed, 24 Oct 2018 16:32:48 GMT
Wed, 24 Oct 2018 16:32:47 GMT
Wed, 24 Oct 2018 16:32:46 GMT
Wed, 24 Oct 2018 16:32:45 GMT
Wed, 24 Oct 2018 16:32:44 GMT
Wed, 24 Oct 2018 16:24:14 GMT
Wed, 24 Oct 2018 16:23:42 GMT
Wed, 24 Oct 2018 15:53:45 GMT
Wed, 24 Oct 2018 15:49:16 GMT
Wed, 24 Oct 2018 15:49:16 GMT
Wed, 24 Oct 2018 14:46:59 GMT
Wed, 24 Oct 2018 14:35:46 GMT
Wed, 24 Oct 2018 11:12:11 GMT
Tue, 28 Jun 2022 16:47:29 GMT
Fri, 23 Sep 2022 18:09:55 GMT
Fri, 26 Mar 2021 22:00:09 GMT
Wed, 24 Oct 2018 11:12:11 GMT
Wed, 24 Oct 2018 09:11:30 GMT
Wed, 24 Oct 2018 09:11:30 GMT
Wed, 24 Oct 2018 09:11:30 GMT
Wed, 24 Oct 2018 09:11:30 GMT
Fri, 26 Mar 2021 22:00:16 GMT
Wed, 24 Oct 2018 06:52:49 GMT
Wed, 24 Oct 2018 06:33:49 GMT
Wed, 24 Oct 2018 06:27:09 GMT
Tue, 23 Oct 2018 19:43:27 GMT
Tue, 23 Oct 2018 17:46:54 GMT
Tue, 23 Oct 2018 13:02:47 GMT
Tue, 23 Oct 2018 05:44:44 GMT
Tue, 23 Oct 2018 04:06:42 GMT
Mon, 22 Oct 2018 19:47:41 GMT
Mon, 22 Oct 2018 19:47:25 GMT
Mon, 22 Oct 2018 19:47:04 GMT
Thu, 24 Feb 2022 21:14:34 GMT
Sun, 20 Nov 2022 10:09:15 GMT
Fri, 26 Mar 2021 22:00:22 GMT
Mon, 22 Oct 2018 19:46:21 GMT
Mon, 22 Oct 2018 18:57:44 GMT
Mon, 22 Oct 2018 18:49:47 GMT
Mon, 22 Oct 2018 16:30:02 GMT
Mon, 22 Oct 2018 15:42:24 GMT
Mon, 22 Oct 2018 15:36:32 GMT
Mon, 22 Oct 2018 15:13:28 GMT
Mon, 22 Oct 2018 14:33:11 GMT
Mon, 22 Oct 2018 14:14:04 GMT
Mon, 22 Oct 2018 11:50:54 GMT
Mon, 22 Oct 2018 09:58:20 GMT
Mon, 22 Oct 2018 09:06:34 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Tue, 28 Jun 2022 16:47:29 GMT
Fri, 26 Mar 2021 22:00:28 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:17:25 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Fri, 26 Mar 2021 22:00:35 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Mon, 22 Oct 2018 07:13:40 GMT
Mon, 22 Oct 2018 06:50:27 GMT
Mon, 22 Oct 2018 05:21:23 GMT
Mon, 22 Oct 2018 02:14:36 GMT
Sun, 21 Oct 2018 20:02:28 GMT
Sun, 21 Oct 2018 20:02:23 GMT
Sun, 21 Oct 2018 20:02:11 GMT
Sun, 21 Oct 2018 16:12:57 GMT
Mon, 23 Aug 2021 12:28:27 GMT
Wed, 21 Apr 2021 16:47:57 GMT
Fri, 26 Mar 2021 22:00:41 GMT
Sun, 21 Oct 2018 14:12:06 GMT
Sun, 21 Oct 2018 14:12:00 GMT
Sun, 21 Oct 2018 14:07:54 GMT
Sun, 21 Oct 2018 14:07:51 GMT
Sun, 21 Oct 2018 14:07:47 GMT
Mon, 15 Feb 2021 03:18:30 GMT
```

**Comment by dr-br** [comment]
Also affects me. Very annoying.  
Videos, however, seem to be shown correctly.

**Comment by j-eissler** [comment]
@dr-br Videos are also affected in my Nextcloud instance.

NC: 28.0.0.11
Photos: 2.4.0
Docker install

**Comment by dr-br** [comment]
Additional information: The Android app for Nextcloud shows media previews correctly. So obviously this is not a server-side issue, but the bug is clearly in the Photos app.

**Comment by dr-br** [comment]
- NC: 28.0.1.1
- Photos: 2.4.0

Now, everything works as expected.

**Comment by nicrame** [comment]
I can confirm same problem with NC 28.0.1.1, on my own install (tested using nginx and Apache web servers, PHP 8.2 (PHP-FPM) under RHEL 9).

**Comment by dr-br** [comment]
@nicrame in case you run a Docker-ized NC: Did you `docker compose down`? In my case all problems vanished with 28.0.1.1

**Comment by nicrame** [comment]
> @nicrame in case you run a Docker-ized NC: Did you `docker compose down`? In my case all problems vanished with 28.0.1.1

I do not use docker.

**Comment by smartbyte** [comment]
Hi guys,

thanks for working on the photos App!

Since the new version 28. ... I have a problem: Only a few of my photos showing up for this month, (although there should be thousands). Looking at the browser log, this line made me curious: "<d:prop><nc:metadata-photos-original_date_time/></d:prop>" ... I checked my file metadata, and I think because I have an S3 backend, I do not have any metadata against my photos, esp. not the exif metadata. The metadata app does not show me any information, and because of the S3 storage, I cannot update the metadata (4TB Photo Storage!).
I think because I only have a file date and not a modified/taken date, the photos app shows random files in my photos app. It shows some, but not just the latest ones.

I checked the code myself, and it looks like it does use a fallback on the file date, but not for the search request. :-/

I don't know how to describe this in detail, but I think you get the point: It does not seem to work if there is no metadata. :-/

Thanks,
Joern.

**Comment by smartbyte** [comment]
Hi guys,

FOUND IT! @artonge this change breaks the photo app for everybody with external (complete nc) storage:
![image](https://github.com/nextcloud/photos/assets/169243/bcb7af24-4e17-4efa-898c-9bcf765edab4)

I am not talking about "External Storage" here. My complete NC Storage is in S3!

Can I please ask for a fix? (not pushing here, just asking. :-) )

Kind regards,
Joern.

**Comment by valdearg** [comment]
Nice sleuthing there! Just built a dev version of the plugin and it's working correctly with your change in!

In my experience this is something that you can submit as a pull request if you're familiar with the process.

**Comment by artonge** [comment]
> Nice sleuthing there! Just built a dev version of the plugin and it's working correctly with your change in!

Could you try with the following and report if it matches the expected behavior?

```xml
<d:orderby>
	<d:order>
		<d:prop><nc:metadata-photos-original_date_time/></d:prop>
		<d:descending/>
	</d:order>
	<d:order>
		<d:prop><d:getlastmodified/></d:prop>
		<d:descending/>
	</d:order>
</d:orderby>
```

**Comment by artonge** [comment]
PR pending: https://github.com/nextcloud/photos/pull/2226
Can one of you test the fix and report back?

**Comment by valdearg** [comment]
So that one gives results from 31st December at 13:18. The mobile app seems to be picking up newer ones which is interesting. I wonder if that uses a different prop?

**Comment by smartbyte** [comment]
1. Sorry I missed this trail as I am in 'Straja (=Australia) and sleeping.
2. I am not a developer, so I replaced the "nc:metadata-photos-original_date_time" with "d:getlastmodified" via "sed" in the *.js files and that then worked. I don't know how to test your fix, as I don't compile Nextcloud. :-(

Never the less it looks like this fix might solve my problem, so thanks for fixing it!

**Comment by nicrame** [comment]
Still same problem with NC 28.0.2 rc3.

**Comment by smartbyte** [comment]
Hi, I confirm that, 
... although as I moved from local storage to S3, I have old pictures with MetaData an new ones without.
With the new code it looks like the system "builds" a list based on the MetaData and _then_ adds a new list based upon lastmodified date. We would need the system to create ONE list, basically merging the two different dates into one and then sort by this (new) date. A simple sort does not solve the issue :-(

**Comment by nicrame** [comment]
> Hi, I confirm that, ... although as I moved from local storage to S3, I have old pictures with MetaData an new ones without. With the new code it looks like the system "builds" a list based on the MetaData and _then_ adds a new list based upon lastmodified date. We would need the system to create ONE list, basically merging the two different dates into one and then sort by this (new) date. A simple sort does not solve the issue :-(

I even do not use any kind of external data place. It's all locally, and just get broken with NC 28. IT's kind of funny when topics like that are closed without any verification if fix is there :)
![Zrzut ekranu (1188)](https://github.com/nextcloud/photos/assets/5872054/4332c2ca-babc-40fa-b59b-30f8d379b8fb)

**Comment by panos-konstantellos** [comment]
I am leaving this note for people who might experience the same situation.

If you copy photos to the Photos folder (using the cp command), you must explicitly generate metadata for those files using the occ command. Otherwise, sorting will not work correctly.

`occ files:scan --generate-metadata --all`

If you are using the maps feature also, you must run this command aswell

`./occ maps:scan-photos --verbose`
