### ISSUE TITLE
Viewer adjustments

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/photos#22]
![grafik](https://user-images.githubusercontent.com/24530680/70233267-81c8b300-175e-11ea-813f-b90134039c36.png)

- [x] Close Icon is wrong, should be a x
- [x] Can't open the sidebar: 
TypeError: Cannot read property 'fileList' of undefined
    at showSidebar (Viewer.vue:569)

**Comment by skjnldsv** [comment]
Close button: https://github.com/nextcloud/nextcloud-vue/pull/757

**Comment by skjnldsv** [comment]
the sidebar open is a quick fix in https://github.com/nextcloud/viewer/blob/2ee76c5e48b1b0517de420169573f60b2841e94a/src/views/Viewer.vue#L569 (you need to use the new OCA.FIles.SIdebar.open function :)

**Comment by jakobroehrl** [comment]
Tried "OCA.Files.Sidebar.open()" instead of
"OCA.Files.App.fileList.showDetailsView(this.currentFile.basename)"

Now I get
TypeError: Cannot read property 'offsetWidth' of null
    at VueComponent.showAppsSidebar (Viewer.vue?a0e8:610)
    at VueComponent.showSidebar (Viewer.vue?a0e8:589)
    at VueComponent.execFirstAction (Modal.js:1099)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js:6911)

**Comment by skjnldsv** [comment]
@jakobroehrl yes, we need to adapt the script that handle the sidebar width and stuff :)

**Comment by jakobroehrl** [comment]
OK, can I do this? 
How hard is that?

**Comment by skjnldsv** [comment]
I'm on it already ;)
