### ISSUE TITLE
Details/sidebar not refreshed in slideshow

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/photos#221]
**To Reproduce**
1. Go to photos
2. Click on a picture to open slideshow
3. open details sidebar
4. click the "next picture" arrow

**Issue**
on the left a new picture is shown, but the details are still from the first picture.
**Workaround**
to get the details from current picture, details view has to be closed and opened again.

**Expected behavior**
Details of picture shown on the left is displayed. Going to next picture also refreshes details view.

**Desktop**
 - Version 18

**Comment by skjnldsv** [comment]
Fixed by https://github.com/nextcloud/viewer/pull/405
