### ISSUE TITLE
Upgrade to latest versions of nextcloud-upload

### ISSUE THREAD

**Issue by lukasm91** [nextcloud/photos#2210]
**Describe the bug**
I wonder if there is a reason why we are still stuck with nextcload-upload version 1.0.0-beta.8? Is there a chance to update to v1.0.4 or a timeline to do this?

The reason for this is because Version v1.0.4 brought some changes that make Photos actually work on my hoster (due to https://github.com/nextcloud-libraries/nextcloud-upload/pull/1002). Hosters tend to turn on some security measures checking the headers, and if the wrong content-type is in a request, it might just block all requests, so the upload functionality is broken on such a hoster.

Also let me know if there is anything I can help with. At this point, I just created a branch of nextcload-upload that cherry picked that one commit.

**Comment by artonge** [comment]
No reason, just time and priorities :)
Would be fixed by https://github.com/nextcloud/photos/pull/2199

**Comment by joshtrichards** [comment]
Fixed in #2256
