### ISSUE TITLE
Large images are not displayed

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/photos#223]
Large images are not shown in the photos app.

Steps to reproduce:

Upload 1200 dpi scanned image. 150MB in size. Dimensions 12917 x 9916.

PNG and TIFF are not displayed in photos. PNG works fine on normal file sizes and dimensions.

It's a bug. I know it's not the normal use case but I'm sure some artists and photographers have similar archives.

Specifications:

NC 18.0.1
PHP 7.4-fpm
Primary S3 storage multibucket (works fine on 20GB+ uploads)
Mariadb

**Comment by skjnldsv** [comment]
Hi, thanks for your report! :)
What file type is it then?
Could you provide the file so I can try?

**Comment by Dragon988** [comment]
I'm in the middle of backing up and moving over to postgresql so just fair warning this may or may not work by the time you get to it.

Here is a crappy doodle that has the problem mentioned in OP.

TIFF (preview visible in file viewer but not photos):

https://drive.irex.me/s/C4LtQYDx48PNg3G

PNG (preview not visible in either photos or file viewer)

https://drive.irex.me/s/Q7W32gTC4dd4QLW

Direct download in nextcloud works on the above image, use:

https://drive.irex.me/s/Q7W32gTC4dd4QLW/download

**Comment by skjnldsv** [comment]
> PNG (preview not visible in either photos or file viewer)

So, we don't support png in photos, so that would be a problem for https://github.com/nextcloud/viewer, right?

Same goes for tiff :)

**Comment by skjnldsv** [comment]
Regardign png in photos https://github.com/nextcloud/photos/issues/208

**Comment by Dragon988** [comment]
> we don't support png in photos

Well that's disappointing. So photos is not aimed at any artists or people who need high quality images?

I'll go ahead and open a bug report on viewer.

**Comment by Dragon988** [comment]
This would also fall under scanned photographs from people who are backing up film negatives or backing up photos. Certainly don't want those saved in jpeg.

**Comment by skjnldsv** [comment]
Let's move to #208 then :)

**Comment by Skip75** [comment]
Both issues are closed, the fix seems merged, but I'm still having an issue with a .png file size of 85,6MB which is not displayed. Am I the only one here ?

**Comment by Vibeshibe** [comment]
Also still experiencing said issue.

**Comment by AndreKoepke** [comment]
Same here. I also noticed this behavior with JPG-images (size 12.000x9.000, 15MB).
![image](https://user-images.githubusercontent.com/15613049/204138846-be53b3db-ea36-4f9d-a7b4-851281714fa0.png)

@skjnldsv can we reopen this?

**Comment by pulsejet** [comment]
You're likely missing some configuration https://github.com/nextcloud/server/issues/34877#issuecomment-1296175634

```php
'preview_max_memory' => 4096,
'preview_max_filesize_image' => 256,
```

Might need even more memory for an 85MB image.

**Comment by AndreKoepke** [comment]
@pulsejet perfect it works. Thank you very much. :)
