### ISSUE TITLE
[BITV]: Ensures [role="img"] elements have alternate text or hide it from a11y tree

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/photos#2240]
Go to the index.php/apps/photos/folders and create a folder.

Please add `aria-hidden="true"` to this `<span>`

![Screenshot from 2024-01-08 18-37-42](https://github.com/nextcloud/photos/assets/6078378/3bfc594e-528d-43ec-99d5-aaee07b98a6c)

**Comment by JuliaKirschenheuter** [comment]
@artonge confirmed i can remove `role="img"`

**Comment by ChristophWurst** [comment]
Dropping the attribute is all there is to do?

**Comment by JuliaKirschenheuter** [comment]
> Please add `aria-hidden="true"` to this `<span>`

Please add aria-hidden="true" to this <span>

**Comment by JuliaKirschenheuter** [comment]
> Dropping the attribute is all there is to do?

Please add aria-hidden="true" to this <span>

**Comment by susnux** [comment]
0dc150b434b4337bd42f7d001c2ab0a6513a4135

**Comment by szaimen** [comment]
I am not sure if this implementation is completely correct:
![image](https://github.com/nextcloud/photos/assets/42591237/dbf2ecfa-c8f8-4760-b5d1-c4c4d011c5be)
Also see what happens on focus-visible and mouse focus:
![image](https://github.com/nextcloud/photos/assets/42591237/b8967184-ad81-4a8e-ba69-8d1ab76d890f)

https://github.com/nextcloud/photos/assets/42591237/79c07d94-5430-4273-844c-df4dc030964c

**Comment by GretaD** [comment]
i will have another look

**Comment by JuliaKirschenheuter** [comment]
still need a backport to stable28: https://github.com/nextcloud/photos/pull/2274

**Comment by JuliaKirschenheuter** [comment]
> i will have another look

Thanks, but this is already done
