### ISSUE TITLE
Browse images by EXIF-tag

### ISSUE THREAD

**Issue by rikmeijer** [nextcloud/photos#225]
**Is your feature request related to a problem? Please describe.**
I use shotwell to organize and tag my photos. Once uploaded to my nextcloud instance I am unable to see the tags set under 'Tagged photos'

**Describe the solution you'd like**
I would like to be able to browse my photos using the tags set by shotwell (stored in EXIF-data)

**Describe alternatives you've considered**
None, since this feature seems unavailable

**Additional context**
See attachement for an example with (nested) tags

![naamloos-7827](https://user-images.githubusercontent.com/448159/76069236-d7497180-5f92-11ea-8c02-67f6f4e7b4b1.jpg)

**Comment by skjnldsv** [comment]
Imported https://github.com/nextcloud/gallery/issues/204 into https://github.com/nextcloud/photos/issues/226
