### ISSUE TITLE
New albums picker in albums broken

### ISSUE THREAD

**Issue by szaimen** [nextcloud/photos#2258]
See 
![image](https://github.com/nextcloud/photos/assets/42591237/922b9881-a54a-43ec-a1d3-232a68aec42e)

**Comment by szaimen** [comment]
So in best case transfer all ncmodal into ncdialog. So rather bigger change then...

**Comment by ShGKme** [comment]
Just replacing with `NcDialog` with no other changes

![image](https://github.com/nextcloud/photos/assets/25978914/131fedb6-66b1-4071-b485-aa1bfe2b695d)
