### ISSUE TITLE
[Bug]: Not possible to add any media to the album

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/photos#2286]
**Describe the bug**
Not possible to add any media to the album.

**To Reproduce**
1. Go to apps/photos/albums
2. Click to "New album"
1. Go to apps/photos/albums/_new album_
4. Click on "+ Add"
5. Click on "Add" inside of the dialog
6.  Select some image / video
7. See that an upload was not successful 

PUT request is not successful.

**Expected behavior**
PUT request is successful.

**Desktop (please complete the following information):**
 - Browser Chrome Version 120

**Browser log**
```
Request Method: PUT
Status Code: 404 Not Found
```

**Comment by MaximeMaW** [comment]
Hi @JuliaKirschenheuter I might be experiencing a similar issue, do you have a "Photos" folder at the root of your documents ? See #2050.

**Comment by JuliaKirschenheuter** [comment]
closing as a duplicate of https://github.com/nextcloud/photos/issues/2050
