### ISSUE TITLE
[BITV] Modal close button overlaps content

### ISSUE THREAD

**Issue by Pytal** [nextcloud/photos#2294]
There are still some modal close buttons which overlap the content

File picker | Edit album | Rename person
--- | --- | ---
![image](https://github.com/nextcloud/photos/assets/24800714/67b7a6c0-ac40-4031-a13b-6e2570577386) | ![image](https://github.com/nextcloud/photos/assets/24800714/153bd110-9a43-4d70-a8ad-0681b5ae91b7) | ![image](https://github.com/nextcloud/photos/assets/24800714/2dec4565-1409-4983-84cc-e50cf6493a3d)

**Comment by Pytal** [comment]
❕ File picker was already drafted but addressed in https://github.com/nextcloud/photos/issues/2287, thanks @susnux!

Handling other modals here

**Comment by susnux** [comment]
Yeah saw them too but decided to first only migrate the photos picker, see #2296
