### ISSUE TITLE
Scrolling of already loaded photos is not smooth, previews get unloaded

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/photos#232]
**Describe the bug**
Scrolling up and down through the list is not smooth as previews of previously loaded pictures get unloaded. The image filetype icon is shown and the preview is loaded again, leading to flickering.

**To Reproduce**
1. Go to any view
2. Scroll down
3. Scroll back up again, and down, and up

**Expected behavior**
Scrolling is nice and smooth, you ideally never see any picture preview loading – but especially not for ones which you already scrolled past and are scrolling back up to.

**Screenshots**
Here’s a gif:
![Photos scrolling jank](https://user-images.githubusercontent.com/925062/76505624-60bddf80-647c-11ea-8547-3437dd544c6f.gif)

Using latest Photos app master.

**Comment by skjnldsv** [comment]
Do you have the dev tools opened?

**Comment by jancborchardt** [comment]
> Do you have the dev tools opened?

It happens with dev tools closed and opened, either way. What’s your question? ;)

**Comment by skjnldsv** [comment]
> It happens with dev tools closed and opened, either way. What’s your question? ;)

if dev tools opened = cache disabled = force fetch all photos every time ;)

**Comment by Mikescops** [comment]
@jancborchardt can you confirm that it is no more the case with the latest master?

**Comment by skjnldsv** [comment]
Btw, nice mustachio @jancborchardt 
![Capture d’écran_2020-10-15_13-58-40](https://user-images.githubusercontent.com/14975046/96120285-92a19380-0eee-11eb-9e01-0deaac09f77c.png)

**Comment by jancborchardt** [comment]
> @jancborchardt can you confirm that it is no more the case with the latest master?

@Mikescops no, seems this still exists – here’s another gif of me scrolling up and down quickly:
![Peek 2020-10-15 17-34](https://user-images.githubusercontent.com/925062/96152358-c1c6fd80-0f0c-11eb-9cdc-4133631e5959.gif)

**Comment by Mikescops** [comment]
@skjnldsv I bet this is our caching problem with N21

**Comment by skjnldsv** [comment]
@Mikescops seems so yeah

**Comment by Mikescops** [comment]
@skjnldsv to be honest i have removed the @loaded again and this issue is nearly unvisible, but I think we will need the worker cache as you suggested.

**Comment by skjnldsv** [comment]
> but I think we will need the worker cache as you suggested.

https://github.com/mdn/sw-test/

**Comment by Mikescops** [comment]
I think I will use Google Workbox, seems to be the most reliable implementation and has webpack support.

**Comment by skjnldsv** [comment]
Nice!
Remember the cache buster is the etag :)

**Comment by axheli** [comment]
Yup i have the same issue when loading photos as @jancborchardt

**Comment by ntimo** [comment]
Is there a change this gets backported to NC20?

**Comment by Mikescops** [comment]
Nope, this is for NC21 only due to the new grid we implemented.
