### ISSUE TITLE
Title issues on mobile

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/photos#233]
Several issues on mobile / narrow screens:
- [ ] The title is not indented anymore to account for the navigation menu icon:
   ![Photos mobile no title indent](https://user-images.githubusercontent.com/925062/76505879-c9a55780-647c-11ea-886a-dff43436ea59.png)
- [ ] In subfolders of albums, the "Back" button overlays the menu icon. It should replace it, and the icons should not show at the same time.
- [ ] There is a horizontal scrollbar
- [ ] Tapping on a navigation entry does not close the navigation
   ![Photos mobile](https://user-images.githubusercontent.com/925062/76505889-d033cf00-647c-11ea-9024-268228289d2e.png)

**Comment by skjnldsv** [comment]
> * Tapping on a navigation entry does not close the navigation

Probably for @nextcloud/vue

**Comment by Mikescops** [comment]
This is fixed already.

**Comment by jancborchardt** [comment]
> Tapping on a navigation entry does not close the navigation

^ That one is still the case @skjnldsv @Mikescops

**Comment by jancborchardt** [comment]
Ah ok, saw @skjnldsv remark that it’s for the Vue components. @skjnldsv is that being handled there then? :)

**Comment by Mikescops** [comment]
Ah yes sorry!
