### ISSUE TITLE
Add Support to additional folders by changing reworking "Choose another folder" to "Add folder"

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/photos#2343]
Enhancement to #141 

Reference: https://github.com/nextcloud/photos/issues/141#issuecomment-1929117412

**Comment by artonge** [comment]
Quoting from the PR:
> It is currently not possible to make a search on multiple folders with WebDAV. This limitation should be removed by https://github.com/nextcloud/server/issues/42915.

**Comment by artonge** [comment]
Server PR: https://github.com/nextcloud/photos/issues/2343
Photos PR: https://github.com/nextcloud/photos/pull/2426
