### ISSUE TITLE
i18n: Need context and improving source string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/photos#2357]
From my understanding the string is not correct english and context is needed

https://github.com/nextcloud/photos/blob/3350af4d40ce45ae599b16e122ad721f3c85b4c1/src/components/Settings/PhotosSourceLocationsSettings.vue#L37

Is "Choose a Photos source for the timelines" correct?

**Comment by artonge** [comment]
That's correct, but I would phrase it the other way. The timelines only show photos from the selected folder.
