### ISSUE TITLE
Folders in Group folders don't appear un folder view

### ISSUE THREAD

**Issue by vbelloir** [nextcloud/photos#2366]
**Describe the bug**
Photos are stored in group folder, shared with familly users.
There are several folder in that group folder. 
Photos are correctly indexed and shown in `Photos` view, but folder don't appear in `Folders` view. 
Folders and sub-folders that contain pictures in user root directory appear correctly in `Folders` view.

**To Reproduce**
1. Create a group Folder
2. Create one or more sub-folder in group folder, filled with photos
3. Assign one user to this group folder, 
4. launch indexation for this user `occ files:scan -- username`
5. check that photos appear in `Photos` view
6. check that folders don't appear in `Folders` view

**Expected behavior**
Folder should appear in `Folders` view

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - OS: Nextcloud 28.0.2 installed on ubuntu server 22.04
 - Browser : Firefox 122.0.1

**Smartphone (please complete the following information):**
NA

**Browser log**
NA

**Additional context**
NA

**Comment by lildadou** [comment]
![image](https://github.com/nextcloud/photos/assets/433604/979e1a0e-c439-4d04-8710-f5fc6512cfd4)
Group folders photos are in the "Shared with you" section.

**Comment by vbelloir** [comment]
Ho thanks Daniel, 
I feel so idiot....
