### ISSUE TITLE
Clicking on picture in Folders does not open viewer

### ISSUE THREAD

**Issue by szaimen** [nextcloud/photos#2381]
Just tested on nc29.0.0b1

Clickin on a picture in the folders view does not open the viewer. Also no multiselect checkbox is shown?
See 

https://github.com/nextcloud/photos/assets/42591237/05b05a5e-cc67-4daa-a9a2-9b3533e9e361

**Comment by claushviid** [comment]
Exacly the the same problem in nextcloud 28.0.4

**Comment by PaulosV** [comment]
Same problem in Nextcloud 28.0.4.

Browser console output:

```
[INFO] viewer: Opening viewer for fileInfo  
Object { app: "viewer", uid: "paulos", level: 1, fileInfo: {…} }
[ConsoleLogger.js:68:18](webpack:///viewer/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
TypeError: e.includes is not a function
    canEdit Viewer.vue:395
    VueJS 3
    xe Viewer.vue:1
    VueJS 13
    open Viewer.js:301
    openViewer FileLegacy.vue:107
    click FileLegacy.vue:3
    VueJS 3
```

**Comment by mlsxlist** [comment]
Happens also for **People**
![Screenshot_20240405_075640](https://github.com/nextcloud/photos/assets/6071818/34cd9fa7-1d0a-4ecc-9a61-1c44043b0f5e)

**Comment by shmelevsky** [comment]
Same problem in 28.04
![Screenshot from 2024-04-03 15-56-15](https://github.com/nextcloud/photos/assets/17156362/b5f21fc6-819d-4815-babb-7f44e12ef330)
