### ISSUE TITLE
The tabs on the sidebar are restricted to a few.

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/photos#243]
**Describe the bug**
The tabs on the sidebar are restricted to "Chat" and "Shared" and i would like to see all the tabs.. 
In my case, I want to see the people tab of FaceRecognition, but the rest are equally useful.

**To Reproduce**
1. Go to files app
2. Click on some photo.
3. Open the viewer, click "Open lateral pane".
4. Here see all tabs.. :smile: 
5. Go to photos app
6. Click on some photo.
7. Open the viewer, click "Open lateral pane".
8. Here see just "Chat" and "Shared" tabs. :disappointed: 

**Expected behavior**
I want to see all the tabs in in photos. 

**Screenshots**

All tabs on files:
![imagen](https://user-images.githubusercontent.com/733715/76760256-14202000-676c-11ea-8da4-98db3eb402c5.png)

Tabs on photos:
![imagen](https://user-images.githubusercontent.com/733715/76760206-ff438c80-676b-11ea-96cf-34f79be30e84.png)

**Desktop (please complete the following information):**
`It is a feature that is not restricted by the browser.`

**Smartphone (please complete the following information):**
`It is a feature that is not restricted by the browser.`

**Browser log**
```
I don't see anything relevant. :disappointed: 
```

**Comment by skjnldsv** [comment]
Yes, see https://github.com/nextcloud/server/issues/20020
