### ISSUE TITLE
External Sotrage Support 

### ISSUE THREAD

**Issue by dassio** [nextcloud/photos#244]
currently the photos app does not support external storage,  and it highly unlikely someone put all the photos in the local storage, Gallery App support  this, please  bring it back .

**Comment by skjnldsv** [comment]
see #154

**Comment by dassio** [comment]
i know that issue, but that one is closed,  that's why i reopened it here

**Comment by skjnldsv** [comment]
Please continue there then, let's not open 10 issues for the same discussion as no one will be able to follow :)
Thanks for your help!

**Comment by dassio** [comment]
can we reopen that issue ?
