### ISSUE TITLE
.noimage .nomedia has no effect

### ISSUE THREAD

**Issue by bendschs** [nextcloud/photos#245]
images in folders or subfolders with .noimage or .nomedia files are still shown in the gallery.

Nextcloud 18.0.2
Same behaviour in various browsers and in the IOS-app.

**Comment by skjnldsv** [comment]
Hey :)
Please do a research before posting https://github.com/nextcloud/photos/issues/234 https://github.com/nextcloud/photos/pull/159 https://github.com/nextcloud/photos/issues/75

**Comment by bendschs** [comment]
ok, so no fix yet?
