### ISSUE TITLE
Empty boxes in tiled viewer

### ISSUE THREAD

**Issue by beardhatcode** [nextcloud/photos#2492]
**Describe the bug**
When scrolling in the photo view, sometimes one or more lines of photos are not shown.
Clicking on the empty boxes does open the viewer with the right photo. 
By scrolling up and down a bit the photo sometimes shows up again but other rows disappear. 

Problem occurs for square and non-square preview

There are no (relevant) errors or warnings in the console. The empty boxes do not have an `img` tag with the preview.

**To Reproduce**
1. Go to photos
3. Scroll down till a row of empty boxes is shown

**Expected behavior**
All previews to show

**Screenshots**
![image](https://github.com/nextcloud/photos/assets/662538/d94066b1-074b-486c-987c-ab7aa064f4fb)

**Server:**
Server: NC 29.0.1 (from nixpkgs)

**Desktop:**
 - OS: Linux (NixOS)
 - Browser: Firefox 126 (also happens in chromium 125)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: Lineage 21
 - Browser: Firefox
 - Version: 125.3.0

**Browser log**

<details><summary>Uninteresting logs</summary>
<pre><code>10:07:08.886 GET
https://&lt;redacted&gt;/apps/photos/
[HTTP/2 200  101ms]

10:07:09.355 GET
https://&lt;redacted&gt;/core/css/server.css?v=581e58fc-17
[HTTP/2 200  34ms]

10:07:09.360 GET
https://&lt;redacted&gt;/apps/activity/css/style.css?v=b3ab1609-17
[HTTP/2 200  72ms]

10:07:09.361 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/css/files_downloadlimit-main.css?v=d233662f-17
[HTTP/2 200  72ms]

10:07:09.362 GET
https://&lt;redacted&gt;/apps/viewer/css/viewer-main.css?v=70e2b24f-17
[HTTP/2 200  71ms]

10:07:09.362 GET
https://&lt;redacted&gt;/nix-apps/notes/css/global.css?v=16eb4d7a-17
[HTTP/2 200  106ms]

10:07:09.366 GET
https://&lt;redacted&gt;/dist/core-common.js?v=581e58fc-17
[HTTP/2 200  103ms]

10:07:09.366 GET
https://&lt;redacted&gt;/dist/core-main.js?v=581e58fc-17
[HTTP/2 200  953ms]

10:07:09.367 GET
https://&lt;redacted&gt;/apps/activity/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1138ms]

10:07:09.368 GET
https://&lt;redacted&gt;/apps/activity/js/activity-api.mjs?v=581e58fc-17
[HTTP/2 200  1138ms]

10:07:09.369 GET
https://&lt;redacted&gt;/apps/updatenotification/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1144ms]

10:07:09.369 GET
https://&lt;redacted&gt;/dist/updatenotification-init.js?v=581e58fc-17
[HTTP/2 200  1153ms]

10:07:09.370 GET
https://&lt;redacted&gt;/dist/core-files_fileinfo.js?v=581e58fc-17
[HTTP/2 200  1153ms]

10:07:09.370 GET
https://&lt;redacted&gt;/dist/core-files_client.js?v=581e58fc-17
[HTTP/2 200  1152ms]

10:07:09.370 GET
https://&lt;redacted&gt;/js/core/merged-template-prepend.js?v=581e58fc-17
[HTTP/2 200  1648ms]

10:07:09.371 GET
https://&lt;redacted&gt;/dist/core-unsupported-browser-redirect.js?v=581e58fc-17
[HTTP/2 200  1152ms]

10:07:09.372 GET
https://&lt;redacted&gt;/core/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1151ms]

10:07:09.372 GET
https://&lt;redacted&gt;/dist/core-unified-search.js?v=581e58fc-17
[HTTP/2 200  1157ms]

10:07:09.373 GET
https://&lt;redacted&gt;/apps/files/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1170ms]

10:07:09.373 GET
https://&lt;redacted&gt;/dist/files-sidebar.js?v=581e58fc-17
[HTTP/2 200  1175ms]

10:07:09.373 GET
https://&lt;redacted&gt;/apps/files/js/fileinfomodel.js?v=581e58fc-17
[HTTP/2 200  1191ms]

10:07:09.373 GET
https://&lt;redacted&gt;/dist/files-reference-files.js?v=581e58fc-17
[HTTP/2 200  1191ms]

10:07:09.374 GET
https://&lt;redacted&gt;/apps/activity/js/activity-sidebar.mjs?v=581e58fc-17
[HTTP/2 200  1191ms]

10:07:09.377 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1191ms]

10:07:09.377 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/js/files_downloadlimit-main.mjs?v=581e58fc-17
[HTTP/2 200  1190ms]

10:07:09.378 GET
https://&lt;redacted&gt;/apps/files_versions/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1190ms]

10:07:09.378 GET
https://&lt;redacted&gt;/dist/files_versions-files_versions.js?v=581e58fc-17
[HTTP/2 200  1195ms]

10:07:09.379 GET
https://&lt;redacted&gt;/nix-apps/maps/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1206ms]

10:07:09.379 GET
https://&lt;redacted&gt;/nix-apps/maps/js/maps-track-metadata-tab.js?v=581e58fc-17
[HTTP/2 200  1225ms]

10:07:09.379 GET
https://&lt;redacted&gt;/nix-apps/maps/js/maps-copy-map-link.js?v=581e58fc-17
[HTTP/2 200  1430ms]

10:07:09.379 GET
https://&lt;redacted&gt;/apps/photos/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1430ms]

10:07:09.380 GET
https://&lt;redacted&gt;/apps/photos/js/photos-sidebar.js?v=581e58fc-17
[HTTP/2 200  1429ms]

10:07:09.380 GET
https://&lt;redacted&gt;/apps/photos/js/photos-main.js?v=581e58fc-17
[HTTP/2 200  1429ms]

10:07:09.381 GET
https://&lt;redacted&gt;/apps/related_resources/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1451ms]

10:07:09.381 GET
https://&lt;redacted&gt;/apps/related_resources/js/related_resources.js?v=581e58fc-17
[HTTP/2 200  1429ms]

10:07:09.381 GET
https://&lt;redacted&gt;/apps/files_sharing/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1428ms]

10:07:09.382 GET
https://&lt;redacted&gt;/dist/files_sharing-files_sharing_tab.js?v=581e58fc-17
[HTTP/2 200  1428ms]

10:07:09.382 GET
https://&lt;redacted&gt;/dist/files_sharing-main.js?v=581e58fc-17
[HTTP/2 200  1428ms]

10:07:09.382 GET
https://&lt;redacted&gt;/apps/viewer/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1428ms]

10:07:09.382 GET
https://&lt;redacted&gt;/apps/viewer/js/viewer-main.mjs?v=581e58fc-17
[HTTP/2 200  1428ms]

10:07:09.383 GET
https://&lt;redacted&gt;/apps/files_pdfviewer/js/files_pdfviewer-main.js?v=581e58fc-17
[HTTP/2 200  1427ms]

10:07:09.383 GET
https://&lt;redacted&gt;/apps/text/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1427ms]

10:07:09.383 GET
https://&lt;redacted&gt;/apps/text/js/text-viewer.js?v=581e58fc-17
[HTTP/2 200  1427ms]

10:07:09.383 GET
https://&lt;redacted&gt;/nix-apps/calendar/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.384 GET
https://&lt;redacted&gt;/nix-apps/calendar/js/calendar-reference.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.384 GET
https://&lt;redacted&gt;/apps/notifications/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.384 GET
https://&lt;redacted&gt;/apps/notifications/js/notifications-main.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.384 GET
https://&lt;redacted&gt;/apps/theming/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.384 GET
https://&lt;redacted&gt;/apps/theming/js/theming.js?v=581e58fc-17
[HTTP/2 200  1502ms]

10:07:09.385 GET
https://&lt;redacted&gt;/nix-apps/recognize/l10n/nl.js?v=581e58fc-17
[HTTP/2 200  1426ms]

10:07:09.385 GET
https://&lt;redacted&gt;/apps/theming/theme/default.css?plain=1&amp;v=0a9818c4
[HTTP/2 200  1425ms]

10:07:09.385 GET
https://&lt;redacted&gt;/apps/theming/theme/light.css?plain=1&amp;v=0a9818c4
[HTTP/2 200  1425ms]

10:07:09.385 GET
https://&lt;redacted&gt;/apps/theming/theme/light.css?plain=0&amp;v=0a9818c4
[HTTP/2 200  1428ms]

10:07:09.386 GET
https://&lt;redacted&gt;/apps/theming/theme/dark.css?plain=0&amp;v=0a9818c4
[HTTP/2 200  1425ms]

10:07:09.386 GET
https://&lt;redacted&gt;/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=0a9818c4
[HTTP/2 200  1425ms]

10:07:09.386 GET
https://&lt;redacted&gt;/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=0a9818c4
[HTTP/2 200  1427ms]

10:07:09.386 GET
https://&lt;redacted&gt;/apps/theming/theme/opendyslexic.css?plain=0&amp;v=0a9818c4
[HTTP/2 200  1427ms]

10:07:09.448 GET
https://&lt;redacted&gt;/dist/icons.css
[HTTP/2 200  1351ms]

10:07:09.675 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:401:1
10:07:10.625 GET
https://&lt;redacted&gt;/apps/activity/js/api-BKkaSPgn.mjs
[HTTP/2 200  841ms]

10:07:10.626 GET
https://&lt;redacted&gt;/apps/activity/js/logger-BVTvLOjn.mjs
[HTTP/2 200  841ms]

10:07:10.626 GET
https://&lt;redacted&gt;/apps/activity/js/index-LkGPsUV3.mjs
[HTTP/2 200  841ms]

10:07:10.631 GET
https://&lt;redacted&gt;/apps/activity/js/index-BY5PybuZ.mjs
[HTTP/2 200  835ms]

10:07:10.632 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/js/purify.es-FFFEAyv8.mjs
[HTTP/2 200  835ms]

10:07:10.633 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/js/_plugin-vue2_normalizer-BeFqqCsd.mjs
[HTTP/2 200  835ms]

10:07:10.635 GET
https://&lt;redacted&gt;/apps/files_downloadlimit/js/logger-CXFbCWgq.mjs
[HTTP/2 200  831ms]

10:07:11.218 GET
https://&lt;redacted&gt;/apps/theming/theme/dark.css?plain=1&amp;v=0a9818c4
[HTTP/2 200  814ms]

10:07:11.229 GET
https://&lt;redacted&gt;/core/img/logo/logo.svg
[HTTP/2 200  802ms]

10:07:11.617 Unified search initialized! UnifiedSearch.vue:54
10:07:11.630 XHRGET
https://&lt;redacted&gt;/ocs/v2.php/search/providers?from=/apps/photos/
[HTTP/2 200  571ms]

10:07:11.631 XHRPOST
https://&lt;redacted&gt;/contactsmenu/contacts
[HTTP/2 200  571ms]

10:07:11.644 OCA.Files.Sidebar initialized Sidebar.js:36:10
10:07:12.174 OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
10:07:12.174 OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
10:07:12.174 OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:33:10
10:07:12.252 GET
https://&lt;redacted&gt;/apps/photos/js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_blurhash_dist_esm_index_js--bc3bd7.js?v=ba5b97909f3f6a50d9ed
[HTTP/2 200  37ms]

10:07:12.253 GET
https://&lt;redacted&gt;/apps/photos/js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js?v=043159e94cc23a1fb765
[HTTP/2 200  40ms]

10:07:12.253 GET
https://&lt;redacted&gt;/apps/photos/js/photos-src_services_collectionFetcher_js-src_components_HeaderNavigation_vue.js?v=22ac83219184132552b5
[HTTP/2 200  40ms]

10:07:12.255 GET
https://&lt;redacted&gt;/apps/photos/js/photos-src_components_Albums_AlbumForm_vue.js?v=7c186dbf39042696303c
[HTTP/2 200  40ms]

10:07:12.255 GET
https://&lt;redacted&gt;/apps/photos/js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_Timeline_vue.js?v=a546c61d13750c359889
[HTTP/2 200  40ms]

10:07:12.269 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. photos
10:07:12.531 GET
https://&lt;redacted&gt;/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=0a9818c4
[HTTP/2 200  62ms]

10:07:12.532 GET
https://&lt;redacted&gt;/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=0a9818c4
[HTTP/2 200  62ms]

10:07:12.627 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config 
Object { app: &quot;viewer&quot;, uid: &quot;beardhatcode&quot;, level: 2, ignoredMimes: (2) […] }
viewer-main.mjs:44:184714
10:07:12.628 OCA.Viewer initialized viewer-main.mjs:2187:581
10:07:12.689 GET
https://&lt;redacted&gt;/apps/notifications/js/notifications-vendors-node_modules_nextcloud_auth_dist_index_cjs-node_modules_nextcloud_l10n_dist_index_mjs-eb6d62.js?v=7f32b8f427ca93297723
[HTTP/2 200  35ms]

10:07:12.690 GET
https://&lt;redacted&gt;/apps/notifications/js/notifications-vendors-node_modules_nextcloud_browser-storage_dist_index_js-node_modules_nextcloud_notify_pu-148966.js?v=e0805c8b3eae9dcac813
[HTTP/2 200  83ms]

10:07:12.691 GET
https://&lt;redacted&gt;/apps/notifications/js/notifications-src_NotificationsApp_vue.js?v=6fe06abb48601a97bae1
[HTTP/2 200  196ms]

10:07:12.761 session heartbeat polling started session-heartbeat.js:103:9
10:07:12.803 GET
https://&lt;redacted&gt;/avatar/beardhatcode/64?v=1

10:07:12.945 GET
https://&lt;redacted&gt;/apps/theming/img/accessibility-dark.svg?v=581e58fc
[HTTP/2 200  34ms]

10:07:12.945 GET
https://&lt;redacted&gt;/apps/settings/img/admin.svg?v=581e58fc
[HTTP/2 200  34ms]

10:07:12.946 GET
https://&lt;redacted&gt;/apps/settings/img/help.svg?v=581e58fc
[HTTP/2 200  34ms]

10:07:12.946 GET
https://&lt;redacted&gt;/core/img/actions/logout.svg?v=581e58fc
[HTTP/2 200  34ms]

10:07:12.946 GET
https://&lt;redacted&gt;/apps/files/img/app.svg
[HTTP/2 200  34ms]

10:07:12.947 GET
https://&lt;redacted&gt;/apps/photos/img/photos.svg
[HTTP/2 200  34ms]

10:07:12.947 GET
https://&lt;redacted&gt;/nix-apps/notes/img/notes.svg
[HTTP/2 200  34ms]

10:07:12.947 GET
https://&lt;redacted&gt;/nix-apps/tasks/img/tasks.svg
[HTTP/2 200  34ms]

10:07:12.948 GET
https://&lt;redacted&gt;/nix-apps/calendar/img/calendar.svg
[HTTP/2 200  38ms]

10:07:12.948 GET
https://&lt;redacted&gt;/nix-apps/contacts/img/app.svg
[HTTP/2 200  38ms]

10:07:12.948 GET
https://&lt;redacted&gt;/nix-apps/phonetrack/img/app.svg
[HTTP/2 200  38ms]

10:07:12.949 GET
https://&lt;redacted&gt;/apps/activity/img/activity.svg
[HTTP/2 200  38ms]

10:07:12.949 GET
https://&lt;redacted&gt;/nix-apps/maps/img/app.svg
[HTTP/2 200  64ms]

10:07:12.949 GET
https://&lt;redacted&gt;/nix-apps/forms/img/forms.svg
[HTTP/2 200  64ms]

10:07:12.950 GET
https://&lt;redacted&gt;/avatar/beardhatcode/64?v=1
[HTTP/2 200  262ms]

10:07:12.950 GET
https://&lt;redacted&gt;/dist/7883-7883.js?v=6f810f49801545cbae33
[HTTP/2 200  66ms]

10:07:12.951 GET
https://&lt;redacted&gt;/apps/activity/js/ActivityTab-B5jIlo4R.mjs
[HTTP/2 200  71ms]

10:07:12.951 GET
https://&lt;redacted&gt;/apps/activity/js/NcCheckboxRadioSwitch-hel9-sAH-DWj7ZO5U.mjs
[HTTP/2 200  71ms]

10:07:12.952 GET
https://&lt;redacted&gt;/apps/activity/js/Activity-Dojq2ncI.mjs
[HTTP/2 200  71ms]

10:07:12.954 GET
https://&lt;redacted&gt;/apps/photos/js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_leaflet-defaulticon-compatib-1c7d79.js?v=618204cece32605b64f3
[HTTP/2 200  103ms]

10:07:12.957 GET
https://&lt;redacted&gt;/apps/photos/js/photos-node_modules_moment_locale_sync_recursive_-src_views_PhotosTab_vue.js?v=85f72d0833d0b6cd7ae7
[HTTP/2 200  158ms]

10:07:12.964 GET
https://&lt;redacted&gt;/apps/related_resources/js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_mjs.related_resources.js
[HTTP/2 200  169ms]

10:07:13.086 GET
https://&lt;redacted&gt;/core/img/logo/logo.svg
[HTTP/1.1 200 OK 0ms]

10:07:13.199 Search providers 
Array(8) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
UnifiedSearchModal.vue:275
10:07:13.378 Registering notifications container as a menu NotificationsApp.vue:219
10:07:13.378 Notifications permissions granted NotificationsApp.vue:453
10:07:13.380 Polling interval updated to 30000 NotificationsApp.vue:416
10:07:13.380 Started background fetcher as session_keepalive is enabled NotificationsApp.vue:275
10:07:13.434 Contacts 
Array(26) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
UnifiedSearchModal.vue:279
10:07:13.616 XHRSEARCH
https://&lt;redacted&gt;/remote.php/dav/
[HTTP/2 207  409ms]

10:07:13.617 GET
https://&lt;redacted&gt;/apps/activity/js/activity-sidebar.mjs
[HTTP/2 200  39ms]

10:07:13.617 XHRGET
https://&lt;redacted&gt;/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/2 200  65ms]

10:07:13.849 GET
https://&lt;redacted&gt;/apps/theming/icon/photos?v=0a9818c4
[HTTP/2 200  70ms]

10:07:13.850 GET
https://&lt;redacted&gt;/apps/theming/favicon/photos?v=0a9818c4
[HTTP/2 200  73ms]

10:07:14.028 Got notification data, restoring default polling interval. NotificationsApp.vue:376
10:07:15.045 XHRSEARCH
https://&lt;redacted&gt;/remote.php/dav/
[HTTP/2 207  431ms]

10:07:15.608 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5890768?etag=16bdace6b2e930c675231816f81cb441&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.610 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5890739?etag=a9d07c89aa4409716a5949ae33c4d10b&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.613 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5888999?etag=df626a43d5666f970d068a1d462263df&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.615 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5888989?etag=a10c0fe736e17e48e4236ef97c8b90b0&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.631 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887854?etag=8f08059ba36839a7b402fd9a1f060e6e&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.644 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887780?etag=33a4f897f4f5f06c692ed71ab024c2b9&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.646 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887788?etag=60fb39389ca2f1fd2b53afeb1f00c4e7&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.653 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887767?etag=b268634f6a33594d3f1632dd8faa61ae&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.657 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887706?etag=a81bbede7753d663e8c44ff9ac144abd&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.661 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887712?etag=9548859a5b21e8e2671209d46290e3bc&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.663 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887734?etag=7540fa972a08c30903c4b4bcb919293c&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.664 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5887698?etag=fe464d5f8271e0ed4cbe5b49101bd533&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.671 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886766?etag=0cc5a2fd02be03c20c17fc0fc5a1698b&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.672 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886748?etag=60089449d8f119550986d5dc3d050719&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.672 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886765?etag=37f6509cbc7ee1ed6c67a6c48f0e702e&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.674 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886729?etag=f5e4a3bdd2b16e2a2252195680157e76&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.675 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886741?etag=b159f93dcc1a90b36d39ed6974a5a034&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.677 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886717?etag=3fb6371d91104060e4323265bc088568&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.678 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886674?etag=00dd10a5e24b6bbbfc35e3fad1cc3aef&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.679 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886633?etag=65d1a718efb4e0ed1772917780006411&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.679 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886648?etag=1e2a228122089e4de943b3f930de97e2&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.681 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886667?etag=57a5e7ae3516be852f9174371fe51825&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.681 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886634?etag=ab5af4ed46941bc0b88cc6a16c1f4147&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.683 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886655?etag=97be545a013f8c20262a3d72293f0676&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.684 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886641?etag=e288f467797d8bb713e029bdb03f698f&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.686 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5886328?etag=b23ff61a3c444d5064521c3f8704cfa9&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.687 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5884297?etag=0d8b90fca774b95c4677366b3add70a8&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.687 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5884839?etag=c26fc3ea276ab7e99c079afd80eb9475&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.697 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5884290?etag=f99ef444408f783a6133c83ef551332c&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.706 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5884375?etag=fcb51ebfe166e33e068c662af0b85f8b&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.708 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883777?etag=f00d4d0b0e2260d664f3fa55414964f2&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.710 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883784?etag=d8ed2b4a8cab3b625c558ab5bfcfaee1&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.718 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883755?etag=a9fcdb6fdfcfab300eec520ee8f8f3c9&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.720 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883749?etag=9a8b5b05e0e3782fe1125cc2c9280d60&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.727 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883742?etag=c56fb2e3e77698b0b82b91b996637d64&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.733 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883730?etag=be4ca9a346a26e2bf3f591444bffc14b&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.741 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883717?etag=353abcf34f22fe3adca10e3511e36fb1&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.743 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883700?etag=e8b912be8ce759bd7a240e0093634491&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.745 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883693?etag=00816f0cd830685e3419eeb437b67597&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:15.747 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883666?etag=3348bd7aff3dcb7ff29b5a9fd37a659f&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:18.854 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883627?etag=4b98cccac15c545960b4650e323666af&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:18.955 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5883608?etag=bc6f25b9247d10256227f84c1e2070bc&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:18.957 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882413?etag=9bd79428f58524d99d379c8ac4ea9559&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:18.964 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882420?etag=b085a340a200fb893bf3c62166d8d906&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.613 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882252?etag=7d30ad357b9f51eeba60d302836deb01&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.617 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882228?etag=96dcca788119e1f3f67fe5ed7c4d2ce1&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.644 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882235?etag=d6bb406d7a5e882bbde63bd3637bb703&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.683 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5882216?etag=83c28868ccfe6eb6f5c701fa9f44be0b&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.686 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881896?etag=cadc565880d28ae92e0c7c8dec60121c&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.687 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881911?etag=c5e1c6d974e523e349c4ad3ba96a4800&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.689 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881903?etag=80d6508df7dadf8cb138ab41a1e091b9&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.690 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881334?etag=88915b82b16d82e426d4532beccf77bf&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.892 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881322?etag=6af96c6896145645d9f65be9546ab074&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.893 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881310?etag=9414e780bd769526b14ed181ab88dbdf&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.894 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881288?etag=f76929b0f2ce92dccbdf77a4db7640ee&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]

10:07:20.897 GET
https://&lt;redacted&gt;/apps/photos/api/v1/preview/5881281?etag=9cf35407b3d41288dacb21f464d33d22&amp;x=512&amp;y=512
[HTTP/1.1 200  0ms]</code></pre>

</details>

**Have the same problem, please thumbs up :+1:  and leave a comment with your server version and the clients you are using**

**Comment by mf-in-mun** [comment]
Same problem here.

Server: NC 29.0.1 using Podman pods on Almalinux 9.4
Desktop 1: HP Notebook, Win 11 23h2, Vivaldi Browser 6.7
Desktop 2: Samsung Galaxy Tab S7, Android 13, Vivaldi Browser 6.7

**Comment by koarlmichael** [comment]
Same:
Server: NC 29.0.2, Debian GNU/Linux 12, Apache2
Desktop: Debian Testing, Firefox 126.0.1 also in Chromium
Laptop: MacBook Air M1, Firefox 126.0.1

**Comment by avignat** [comment]
Same here
Debian 12, nginx, PHP-FPM
Nextcloud 29.0.3

**Comment by mf-in-mun** [comment]
I've just updated to NC 29.0.04 this morning.

It seemed to be fixed. I will check it furthermore.

Thank you very much to the maintainers 👍👍👍👍👍

**Comment by beardhatcode** [comment]
Ah yes, indeed, nice! Thanks
