### ISSUE TITLE
[Bug]: Unable to access "ALBAUM" in Nextcloud 29.0.x

### ISSUE THREAD

**Issue by nikitakothari06** [nextcloud/photos#2493]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have installed Nextcloud 29.0.1 on my test server with PHP 8.0 & Mysql 8.0 When I first create the albaum from "Photos --> +Add --> Add new albaum" the albaum gets created. However When I upload any image in it, it throws the following error. 
**Failed to add xxxx.jpg to collection /photos/[[username]]/albums/[[albaum]]**

And after that when I visit "Albaum" section from left side menu it throws the "**An error occurred**" error.

I am attaching the nextcloud.log file for the reference.

[nextcloud.log](https://github.com/user-attachments/files/15514251/nextcloud.log)

![image](https://github.com/nextcloud/server/assets/100770244/e0f3273b-29fa-4278-9bc7-c25b1068a37e)

### Steps to reproduce

1. Login to the admin panel.
2. Visit the "**Photos**" section from right top section.
3. Create the new albaum.
4. Upload a new file in the created albaum. and it will throw the **Failed to add xxxx.jpg to collection /photos/[[username]]/albums/[[albaum]]** error.
5. Try to visit "Albaum" section again and it will throw "**An error occurred**" error.

### Expected behavior

The new albaum should created without any error and in that albaum, user should be able to upload the files.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Altahrim** [comment]
There is a setting for that in PDO: [ATTR_STRINGIFY_FETCHES](https://www.php.net/manual/fr/pdo.constants.php#pdo.constants.attr-stringify-fetches)
I recall something changed about this, but I couldn't find what…

**Comment by artonge** [comment]
> Is there any ETA for the next version with these changes ?

Should be in the next releases: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
