### ISSUE TITLE
Photo can not be uploaded in Newly created albaum

### ISSUE THREAD

**Issue by nikitakothari06** [nextcloud/photos#2496]
**Describe the bug**
Photo can not be uploaded in Newly created albaum and no logs gets generated.

**To Reproduce**
1. Login to the admin panel
2. Go to 'Photos' and create a new albaum.
3. Go into the new albaum and click on '+add'
4. A pop up will ask to upload '+New' or select from the existing one.
5. When I click on '+New' and upload the photo it neither show any error nor upload the file.

**Expected behavior**
New photo should get uploaded directly

**Screenshots**
![img_20240604](https://github.com/nextcloud/photos/assets/100770244/50ed23d1-bbf6-4cf6-bbb9-a71763cc01ce)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 126.0.1

**Browser log**
![image](https://github.com/nextcloud/photos/assets/100770244/68597182-1c5e-4c8b-9de8-bbb460754480)

**Comment by artonge** [comment]
Fixed by https://github.com/nextcloud/photos/pull/2494
