### ISSUE TITLE
occ app:enable photos not work with Database error

### ISSUE THREAD

**Issue by ralfi** [nextcloud/photos#2555]
Hi,

after playing around with photos and memories and what related both apps to albums i can not enable photos because this error appear:

`Database error when running migration 3000Date20240417075404 for app photos
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'papa-photos-photosSourceFolders' for key 'PRIMARY'`

My question:

How can i fix this with mariadb-client?
Is there a way to remove 'shipped' apps like photos to reinstall this app?

Thanks a lot!
Regards

**Comment by kesselb** [comment]
`select * from oc_preferences where configkey = 'photosSourceFolder'`

The failing migration changes  photosSourceFolder (single value) to photosSourceFolder**s** (multiple values). 

Try to look at the above query result and delete the duplicate row.

**Comment by ralfi** [comment]
![image](https://github.com/user-attachments/assets/de51fcb1-1723-4ea8-bbcf-8021274f1e3c)

configvalue `/Meins` is a shared folder and included in folder `/` from user `papa`

How can i modify the relative value or how can i set set configvalue?

**Comment by ralfi** [comment]
Hi @kesselb can you please take a look ... Thanks

**Comment by kesselb** [comment]
I would try to delete the existing rows in oc_preferences with appid = photos and configkey = photosSourceFolders

Then the migration will hopefully run through.

**Comment by ralfi** [comment]
Works, great. Thank you!

**Comment by ralfi** [comment]
close

**Comment by AndyScherzinger** [comment]
Beta4 of 30.0.0 ships a fix in the DB migrations for this. Thanks for reporting 👍
