### ISSUE TITLE
Nextcloud 18.0.2 could NOT get image preview screen

### ISSUE THREAD

**Issue by JKNgo** [nextcloud/photos#259]
**Describe the bug**
I clicked to any images and Preview popup not loading data and keep hanging.
My environments:
NextCloud: 18.0.2-apache
PHP: v7.3.16
I use helm chart from https://github.com/helm/charts/tree/master/stable/nextcloud
Additionally, videos and pdf preview worked well.
When I clicked Slide show in Photo, I can see image preview but with single image can NOT.

**Expected behavior**
Preview loads data and works well.

**Screenshots**
![1](https://user-images.githubusercontent.com/15956180/77342152-58aa4d80-6d62-11ea-984e-827ca9470525.png)
![2](https://user-images.githubusercontent.com/15956180/77342164-5ea02e80-6d62-11ea-9348-13782e40b897.png)
![3](https://user-images.githubusercontent.com/15956180/77342174-61028880-6d62-11ea-9d0a-33552c6a38d3.png)

**Comment by skjnldsv** [comment]
Please share your nextcloud log, especially with an error 500

**Comment by JKNgo** [comment]
Here is my nextcloud.log

[nextcloud.log](https://github.com/nextcloud/photos/files/4372865/nextcloud.log)

**Comment by skjnldsv** [comment]
Sorry, the file you provided is far too long :(
Please clear the file, trigger the error and send it again so we can at least narrow what is happening :)

I'll suggest just copying the file to nextcloud.old.log or something ;)

**Comment by JKNgo** [comment]
Actually it didn't raise any logs for that errors. I used nextcloud helm chart, so maybe there are some logs in somewhere? Do you know how to get the detailed logs?

**Comment by skjnldsv** [comment]
Well, if there is a 500 error, there is definitely an issue and a log laying around :)
Are you using a reverse proxy?
Try restarting it see if it create a new nextcloud log file?

**Comment by JKNgo** [comment]
Thanks for your suggestion. It's definitely a Nginx issue.
