### ISSUE TITLE
30000Date20240417075404 - You can't specify target table 'oc_preferences' for update in FROM clause

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/photos#2592]
```
Exception: Database error when running migration 30000Date20240417075404 for app photos An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_preferences' for update in FROM clause
```

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/photos/pull/2571

**Comment by nickvergessen** [comment]
Should split the select and the delete (don't get confused by the word update and read it as row-modification instead).
On inserting we then also need to make sure to not have an IN with more than 1k elements (oracle)

**Comment by sorbaugh** [comment]
@yemkareems, could you please take a look 🙏
