### ISSUE TITLE
2 or more photos are opened at the same time

### ISSUE THREAD

**Issue by solracsf** [nextcloud/photos#2645]
**Describe the bug**
NC 29.0.7.
2 or more photos are opened at the same time after click on main view.

**To Reproduce**
1. Go to 'Photos
2. Click on '1st photo
3. 2 or more photos are opened

**Expected behavior**
One photo at a time.

**Screenshots**

![image](https://github.com/user-attachments/assets/bde4e055-80ab-4909-bc88-4e1acffa32e8)

![image](https://github.com/user-attachments/assets/aa7a8e6c-dd22-43b8-babd-cbfc73be8620)

**Desktop (please complete the following information):**
 - Browser Brave 1.69.162

**Browser log**
![image](https://github.com/user-attachments/assets/0fbbe1ea-0f39-4249-89bd-8d85d11947fd)

**Comment by szaimen** [comment]
Hi, can you try again after clearing the browser cache?

**Comment by solracsf** [comment]
Humm. That did it, but i was having the problem already on 29.0.6. I've waited for 29.0.7 to recheck.
Shouldn't the upgrade take care of cache invalidation (by changing the cache buster string) ? 🤔

**Comment by szaimen** [comment]
> Shouldn't the upgrade take care of cache invalidation

Yes. See https://github.com/nextcloud/viewer/issues/2454

**Comment by solracsf** [comment]
Thanks. That PR was merget on 29.0.7, but my problem was on 29.0.7.
Or should I understand that it will only work on 29.0.7 > 29.0.8?

**Comment by szaimen** [comment]
I guess it will only work afterwards
