### ISSUE TITLE
Add status bar when getting album list 

### ISSUE THREAD

**Issue by dassio** [nextcloud/photos#267]
In the album view,  when open an  sub folder, if there are too many albums in that sub tree, the initial  page is no photo.
![screen logging](https://media.giphy.com/media/mAOnAKmYGbCGugj6SM/giphy.gif)

after the response came from :https://domainname/index.php/apps/photos/api/v1/albums/storj-pictures, it will load all, need to have a status bar to show it id loading the album list

**Comment by skjnldsv** [comment]
When you say status bar, you mean a progress bar or a loading animation for you to understand this is not finished, right?

**Comment by dassio** [comment]
Yes,  i mean progress bar or loading animation

**Comment by skjnldsv** [comment]
Can you screencast this with your devtools open on the network tab please?

**Comment by dassio** [comment]
step i take:
1 **jump from file app to photos app, change network to GRPS to simulate slow network**
![initial state](https://nextcloud.dassionj.me/index.php/s/fSQXa3Sf6fJ9BR5/preview)
2 **open main album  page**
![main album](https://nextcloud.dassionj.me/index.php/s/Wo6BZZdFeTZtkdF/preview)
3 **click one album, both main folder and sub-folder are querying photo list**
![](https://nextcloud.dassionj.me/index.php/s/8bgXRgp7bqMJNQY/preview)
4 **open sub-folder, sub-folder photo query not finished yet, show empty page**
![](https://nextcloud.dassionj.me/index.php/s/NnRARMfAW2JqzzK/preview)
5 **when the query is done, preview image start to download**
![](https://nextcloud.dassionj.me/index.php/s/y6pZmST76eWzso4/preview)
