### ISSUE TITLE
Cant generate shared Album link - it always generates in "file share" view instead

### ISSUE THREAD

**Issue by maltokyo** [nextcloud/photos#269]
**Describe the bug**
Just installed NC18 that comes with the "Photos" app.

The issue is, when I, as a user go to "Photos", "Your Albums", My designated album, I see the images files, and if I click any of the images, I get a nicely sized preview (this is perfect!).

However, if I share the folder from here, and go to that link that the "share" button generates - I will get a file/folder view, not the Album view.  This should share the album view, not give simply the list of files.

The best one do in Nexclou 18 is access grid view that will show me small thumbnails - but if you click a file, it will start downloading it, instead of actually showing me a preview/gallery/slideshow etc.

Anyone who knows how I can get the correct behavior so that I can share albums and they can see previews (not just thumbnails?)

Please let me know if I should be more specific, I will try with some screendumps.

**To Reproduce**
See above.

**Expected behavior**
Can share link to a photo album, rather than a list of JPG files etc.

**Screenshots**
Will add if needed, please let me know if above is not clear.

**Desktop (please complete the following information):**
 - Browser Chrome & Firefox (latest updates applied)

**Comment by skjnldsv** [comment]
> However, if I share the folder from here, and go to that link that the "share" button generates - I will get a file/folder view, not the Album view. This should share the album view, not give simply the list of files.

Hey! :)
Yes, the photos view is not available in the public sharing views, see the dedicated issue there: #236

**Comment by skjnldsv** [comment]
> I get a nicely sized preview (this is perfect!).

thanks for the kind words and your interest on this app :hugs:
