### ISSUE TITLE
Make Photos usable in NC 18

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/photos#270]
Unfortunately, photos are not yet available for a requested use case: I have several photos and want to share them with other people via a link.

This was possible in the Gallery App and it will be possible again in the Photo App ([see](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32)). But it would be important if this would still work in NC 18. 

Here are the things that still have to be implemented:

- **Sorting pictures by taken date instead of modification date (https://github.com/nextcloud/photos/issues/87)**
- **Photos layout for link shares (https://github.com/nextcloud/photos/issues/236)**
- **No cropping photo design (https://github.com/nextcloud/photos/issues/143)**

Other important things have already been fixed - thanks for that:

- **Allow to browse the folder tree (https://github.com/nextcloud/photos/issues/142)**
- **Viewer also for public links (https://github.com/nextcloud/viewer/issues/89)**

Would it be possible to implement this functionality in NC 18?

**Comment by skjnldsv** [comment]
Hi,

All features you linked already have their own dedicated tickets.
What is the purpose of opening a new one?
This has been discussed pretty much all over the place and those answers already were given: no ETA. It will come when it will come.
Not enough time, but, if anyone want to jump and start coding, we'll be hapy to help.

Thanks for your interest in the matter

**Comment by smacz42** [comment]
The purpose is that there was functionality in previous versions of nextcloud that now require remediation due to a deprecation.

I believe the question remains, when will these deficiencies be remediated?
