### ISSUE TITLE
Photos app shows: "An error occured" after upgrading to Nextcloud v18.0.3

### ISSUE THREAD

**Issue by tlouwers** [nextcloud/photos#290]
**Describe the bug**
After upgrading from 17.0.3 to 18.0.3 I got the Photos app. When accessing this from the menu bar (top left) I get a blank page with the text: An error occured. I tried to look into the log files, but no hints here of what is happening.

**To Reproduce**
1. Go to top menu bar (top left)
2. Click on Photos icon
3. See error --> text "An error occured"

**Expected behavior**
Entirely blank page, or something indicating no folder configured yet...

**Screenshots**
![Photos - blank page](https://user-images.githubusercontent.com/38902842/79063916-1ad77f80-7ca5-11ea-9599-613843f3ee26.png)

**Desktop (please complete the following information):**
 - OS: Hosted Linux environment, PHP 7.3, MySQL 5.7, PHP memory: 128 MB  (and cannot change this)
 - Browser: Chrome, Brave
 - Version: 1.5.123

**Browser log**
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ notifications.js?v=833d4879-0:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=833d4879-0:1
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
e.default @ no-conflict.js:9
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ file.handlebars:1
n @ bootstrap:19
(anonymous) @ richObjectStringParser.js:13
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=833d4879-0:1
Sidebar.js:37 OCA.Files.Sidebar initialized
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
(anonymous) @ activity-sidebar.js?v=833d4879-0:124
(anonymous) @ activity-sidebar.js?v=833d4879-0:354
activity-sidebar.js?v=833d4879-0:561 Uncaught TypeError: Cannot read property 'extend' of undefined
    at activity-sidebar.js?v=833d4879-0:561
    at activity-sidebar.js?v=833d4879-0:761
(anonymous) @ activity-sidebar.js?v=833d4879-0:561
(anonymous) @ activity-sidebar.js?v=833d4879-0:761
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
(anonymous) @ templates.js:2
n @ bootstrap:19
(anonymous) @ comments.js:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ comments.js?v=833d4879-0:1
commentmodel.js:13 Uncaught TypeError: Cannot read property 'Client' of undefined
    at commentmodel.js:13
    at Object.<anonymous> (commentmodel.js:11)
    at n (bootstrap:19)
    at Module.<anonymous> (comments.js:1)
    at n (bootstrap:19)
    at bootstrap:83
    at comments.js?v=833d4879-0:1
(anonymous) @ commentmodel.js:13
(anonymous) @ commentmodel.js:11
n @ bootstrap:19
(anonymous) @ comments.js:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ comments.js?v=833d4879-0:1
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
t.default @ no-conflict.js:8
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ item.handlebars:1
n @ bootstrap:19
(anonymous) @ files_versions.js?v=833d4879-0:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=833d4879-0:1
versionstabview.js:18 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (versionstabview.js:18)
    at n (bootstrap:19)
    at bootstrap:83
    at files_versions.js?v=833d4879-0:1
(anonymous) @ versionstabview.js:18
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=833d4879-0:1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ Avatar.js:67
n @ Avatar.js:1
(anonymous) @ Avatar.js:67
n @ Avatar.js:1
(anonymous) @ Avatar.js:1
(anonymous) @ Avatar.js:1
n @ bootstrap:19
(anonymous) @ files_sharing_tab.js?v=833d4879-0:836
(anonymous) @ files_sharing_tab.js?v=833d4879-0:836
n @ bootstrap:19
(anonymous) @ files_sharing_tab.js?v=833d4879-0:1317
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_sharing_tab.js?v=833d4879-0:1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ files_sharing_tab.js?v=833d4879-0:836
(anonymous) @ files_sharing_tab.js?v=833d4879-0:836
n @ bootstrap:19
(anonymous) @ files_sharing_tab.js?v=833d4879-0:1317
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_sharing_tab.js?v=833d4879-0:1
ShareSearch.js:33 OCA.Sharing.ShareSearch initialized
ExternalLinkActions.js:33 OCA.Sharing.ExternalLinkActions initialized
Viewer.js:41 OCA.Viewer initialized
Viewer.vue:279 No OCA.Files app found, viewer is now in standalone mode
GridConfig.js:39 Current grid config {__ob__: It}
(index):1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden">​…​</form>​
[Violation] Forced reflow while executing JavaScript took 33ms
xhr.js:178 SEARCH https://pyxides.nl/remote.php/dav/ 405
(anonymous) @ xhr.js:178
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:50
Promise.then (async)
c.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ functions.js:10
value @ index.js:95
value @ index.js:207
c @ fetch.js:52
t.exports @ fetch.js:58
request @ request.js:102
getDirectoryContents @ directoryContents.js:47
getDirectoryContents @ factory.js:244
(anonymous) @ PhotoSearch.js:122
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
dn @ photos.js?v=833d4879-0:382
a @ photos.js?v=833d4879-0:403
(anonymous) @ photos.js?v=833d4879-0:403
(anonymous) @ photos.js?v=833d4879-0:403
pn @ photos.js?v=833d4879-0:403
hn @ PhotoSearch.js:40
(anonymous) @ CancelableRequest.js:46
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
Me @ photos.js?v=833d4879-0:359
a @ photos.js?v=833d4879-0:382
(anonymous) @ photos.js?v=833d4879-0:382
(anonymous) @ photos.js?v=833d4879-0:382
(anonymous) @ CancelableRequest.js:45
(anonymous) @ Timeline.vue:165
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
xn @ VirtualGrid.vue:16
a @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ Timeline.vue:142
(anonymous) @ Timeline.vue:135
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
xn @ VirtualGrid.vue:16
a @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ Timeline.vue:66
zt @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4219
t @ vue.runtime.esm.js:4043
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
l @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
l @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
In @ vue.runtime.esm.js:5085
(anonymous) @ main.js:60
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ photos.js?v=833d4879-0:1
Show 75 more frames
Timeline.vue:194 Error fetching timeline Error: Request failed with status code 405
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:61)
(anonymous) @ Timeline.vue:194
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
xn @ VirtualGrid.vue:16
s @ VirtualGrid.vue:16
Promise.then (async)
xn @ VirtualGrid.vue:16
a @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ Timeline.vue:142
(anonymous) @ Timeline.vue:135
c @ Multiselect.js:119
(anonymous) @ Multiselect.js:119
forEach.t.<computed> @ Multiselect.js:119
xn @ VirtualGrid.vue:16
a @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ VirtualGrid.vue:16
(anonymous) @ Timeline.vue:66
zt @ vue.runtime.esm.js:1854
en @ vue.runtime.esm.js:4219
t @ vue.runtime.esm.js:4043
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
n @ vue.runtime.esm.js:3301
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
l @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
p @ vue.runtime.esm.js:6053
l @ vue.runtime.esm.js:5954
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
l @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
In.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
In @ vue.runtime.esm.js:5085
(anonymous) @ main.js:60
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ photos.js?v=833d4879-0:1
Show 45 more frames
```

**Additional context**
I checked the Viewer application via OCC web: it is version 1.2.0, but note that the sudo command via OCC for me is not available since it is a hosted environment.

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by skjnldsv** [comment]
> xhr.js:178 SEARCH https://pyxides.nl/remote.php/dav/ 405

This one is your issue

I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by skjnldsv** [comment]
You can click the failed request after that and show me the response tab please :)

**Comment by tlouwers** [comment]
Do you mean these dumps?

![Dump1](https://user-images.githubusercontent.com/38902842/79067422-6dbe3080-7cbf-11ea-8b28-0b8274fbe94c.png)
![Dump2](https://user-images.githubusercontent.com/38902842/79067423-6eef5d80-7cbf-11ea-9705-d8db2d992167.png)

**Comment by skjnldsv** [comment]
Yes, but the response tab, on the bottom-right panel :)

**Comment by tlouwers** [comment]
I do see parts of the webbrowser I never found before... :P

I hope this is the right one:
![Dump3](https://user-images.githubusercontent.com/38902842/79076641-0a062880-7cfc-11ea-8968-c18c54b2e918.png)

**Comment by skjnldsv** [comment]
Do you have any errors in your nextcloud log?
Are you using external storages?

**Comment by tlouwers** [comment]
I have no external storage configured, this is all on the hosted location.
For the user there is a folder with a few wallpapers, *.jpeg and some other.
In the logging I cannot find anything specific, for days there were no errors listed at all - yesterday I found this one (but I have seen the issue without logging as well):
`{"reqId":"00Ujm881agUvrAEq898e","level":3,"time":"2020-04-13T16:03:40+00:00","remoteAddr":"<<<IPADDRESS>>>","user":"--","app":"no app in context","method":"GET","url":"/remote.php/dav/","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"photos.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/Route/Router.php","line":339,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["photos.page.index",[],1]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/URLGenerator.php","line":82,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["photos.page.index",[]]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/NavigationManager.php","line":293,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["photos.page.index"]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/NavigationManager.php","line":114,"function":"init","class":"OC\\NavigationManager","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/apps/theming/lib/ThemingDefaults.php","line":182,"function":"getAll","class":"OC\\NavigationManager","type":"->","args":["guest"]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/public/Defaults.php","line":160,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/Template/JSConfigHelper.php","line":284,"function":"getShortFooter","class":"OCP\\Defaults","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/TemplateLayout.php","line":190,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/lib/private/legacy/template.php","line":184,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest","dav"]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/apps/dav/lib/Files/BrowserErrorPagePlugin.php","line":98,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/apps/dav/lib/Files/BrowserErrorPagePlugin.php","line":83,"function":"generateBody","class":"OCA\\DAV\\Files\\BrowserErrorPagePlugin","type":"->","args":[]},{"function":"logException","class":"OCA\\DAV\\Files\\BrowserErrorPagePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\Exception\\NotAuthenticated"}]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Files\\BrowserErrorPagePlugin"},"logException"],[{"__class__":"Sabre\\DAV\\Exception\\NotAuthenticated"}]]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":259,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["exception",[{"__class__":"Sabre\\DAV\\Exception\\NotAuthenticated"}]]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/srv/data/web/vhosts/pyxides.nl/htdocs/remote.php","line":165,"args":["/srv/data/web/vhosts/pyxides.nl/htdocs/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/srv/data/web/vhosts/pyxides.nl/htdocs/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.3.0","id":"5e95ad5982c5c"}`

**Comment by skjnldsv** [comment]
That seems to be a weird issue.
How did you upgrade/install nextcloud? 
Does this error appear everytime you get the 401 error on photos?

Are you self hosting?

**Comment by tlouwers** [comment]
The Nextcloud instance is hosted with a provider, it is not self hosted. From what I understand is that this is a virtual machine with a single CPU and some ram - suitable for few users.

I started out with Nextcloud v16 (if I remember correctly), then upgraded each lowest point release. Since that worked quite well I made the switch to v17, did a similar thing to v17.0.3, then upgraded to v18.0.3.

The error from the log is the first time I see it, it has not appeared in the days before when I get the 401 error on Photos.

What I can try (but this will not be quick) is that I make a backup of what is in my Nextcloud instance, then wipe everything and do a re-install starting at v18.0.3.

**Comment by skjnldsv** [comment]
It looks weird to me, especially this: 
![image](https://user-images.githubusercontent.com/14975046/79232210-7f423c80-7e67-11ea-9d27-7aa3f96bf4e8.png)

Maybe see with your hosting service if they limit the kind of requests we can do, because our dav endpoint does not display 405 errors like that at all :/
They are outputted as html.

For me this is a hosting issue, not nextcloud :)

**Comment by skjnldsv** [comment]
(see with them, if it's not, please reopen this issue)

**Comment by tlouwers** [comment]
I managed to get my hosting provider to have a look at this issue and got a response which might help:

------------------------------------
[17-Aug-2020 06:54:26] WARNING: [pool www] server reached max_children setting (4), consider raising it

That's mean the resources of your instance that are impacted.

This message indicate that the simultaneous PHP processes allocated to your instance (4 for a size M) are regularly all busy.
------------------------------------

I also got a suggestion to take another package with more resources, but for me this seems to shift the problem, not solve it. When resources are busy, they eventually should become available again, or are more needed just to run the Photos app in this case?

**Comment by Snort-dissatisfied741** [comment]
@skjnldsv https://preprocessor.space/questions/check-boxes-in-html-form-elements

**Comment by donkfamily** [comment]
Reset the Database

    Stop your Nextcloud container. This prevents it from writing new data while we modify the database.
    Bash

docker stop nextcloud

Access your database container shell.
Bash

docker exec -it nextcloud-db bash

Find your database password. You can get this from your Nextcloud container's configuration file.

    Open a new terminal session (or a new tab).

    Run the following command to print the contents of the config file. Look for the 'dbpassword' entry.

Bash

docker exec nextcloud cat /config/www/nextcloud/config/config.php

Log in to the MariaDB database. Use the password you just found. The default database user and name for this setup are nextcloud.
Bash

mysql -u nextcloud -p

When prompted for the password, paste it in and press Enter.

Delete the corrupted database entry. This will remove all of the Photos app's settings for your user, forcing it to rebuild them.
SQL

DELETE FROM nextcloud.oc_preferences WHERE userid = 'admin2' AND appid = 'photos';

Exit the database shell and restart Nextcloud.
SQL

exit

Bash

    exit
    docker start nextcloud

After the container starts, clear your web browser's cache and cookies, then try opening the Photos app again. It should be reset and start scanning your Pictures folder from scratch.
