### ISSUE TITLE
Show photos from shared folders in timeline

### ISSUE THREAD

**Issue by bjoern-tantau** [nextcloud/photos#291]
This might be a duplicate of #196 or #129. My wife and I both have our photo upload folders shared with each other. But in the default timeline view of the photos app I only see my own photos. It would be great if I could see her photos as well, sorted by date, like all other pictures.

Her photos are available via shared albums. But a combined view would be really great.

**Comment by jakobroehrl** [comment]
Unfortunately not possible to implement due to performance issues :(

**Comment by bjoern-tantau** [comment]
Damn, even if all folders are local?

**Comment by jakobroehrl** [comment]
> 
> 
> Damn, even if all folders are local?

Yes, I think so...

**Comment by jakobroehrl** [comment]
This is working in NC22! 👍

**Comment by Mannshoch** [comment]
Anything i haveto activatefor this?
Currently I only have a photos in Shared with you. No photos in Timeline and non in the Tagged section. Which both would be important for me.
