### ISSUE TITLE
Firefox claims that photos slows down the browser when opening large folders

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/photos#292]
### Steps to reproduce
Open a large photo folder in the album view. In my case it is a groupfolder containing 15300 files, 190 GB of a mix of JPG, DNG and MP4 files.

### Expected behaviour
The folder should open and show the first few pictures immediately.

### Actual behaviour
No previews are shown. Firefox asks after some time whether it should stop the script since it slows down the browser.

## Server configuration detail

**Operating system:** Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.3.11-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloudpi

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - carnet: 0.20.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.5
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - music: 0.13.2
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - nextcloudpi: 0.0.1
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_texteditor
 - gallery
 - previewgenerator.orig
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": false,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "5": "nextcloudpi.local",
        "7": "nextcloudpi",
        "8": "nextcloudpi.lan",
        "1": "192.168.178.43",
        "11": "2.243.6.226",
        "20": "domain.com",
        "4": "domain.com",
        "12": "domain.com"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "https:\/\/yxc.selfhost.eu\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "tempdirectory": "\/media\/myCloudDrive\/ncdata\/tmp",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "maintenance": false,
    "logfile": "\/media\/myCloudDrive\/ncdata\/nextcloud.log",
    "jpeg_quality": "60",
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": "2",
    "data-fingerprint": "597c55b577e23a7077d2ff90438b8d4f",
    "theme": "",
    "log_type": "file",
    "has_rebuilt_cache": true,
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\Movie",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** USB harddrive

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Operating system:** Raspbian

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
OCA.Files.Sidebar initialized Sidebar.js:37:10
TypeError: OCA.Files.DetailTabView is undefined
activity-sidebar.js:561:24
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
TypeError: OCA.Files.DetailTabView is undefined
versionstabview.js:18:7
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 globals.js:66:15
TypeError: t.Files is undefined
commentmodel.js:13:1
OCA.Viewer initialized Viewer.js:41:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:279
Current grid config 
Object { marginTop: Getter & Setter, marginW: Getter & Setter, count: Getter & Setter, gap: Getter & Setter, … }
GridConfig.js:39:10
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). getInferredName.js:6:19
Current grid config 
Object { marginTop: Getter & Setter, marginW: Getter & Setter, count: Getter & Setter, gap: Getter & Setter, … }
GridConfig.js:39:10
Loading next page 1 Timeline.vue:242
Script terminated by timeout at:
pn.prototype.depend@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:27881
yn/<@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:29735
Ke</<@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:382:13858
ve@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:15947
Ke<@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:382:13789
t.prototype._render@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:35338
r@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:64415
pn.prototype.get@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:26652
pn.prototype.run@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:27536
dn@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:25644
ee/<@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:12315
Zt@https://domain.com/apps/photos/js/photos.js?v=5aa3f7ef-0:7:11759

</details>

**Comment by svenb1234** [comment]
Still valid for 18.0.4.

**Comment by skjnldsv** [comment]
Hey! Thanks for your patience!
We're talking about the "My albums" view, right?

**Comment by svenb1234** [comment]
"Deine Alben" is the German translation. In English that would be Your albums. But I think we are talking about the same.

**Comment by skjnldsv** [comment]
I'll experiment with this when I'll have more time! Thanks for your interest!

**Comment by Mikescops** [comment]
@svenb1234 I'll address this issue in the upcoming days, hope to have your feedback then :smile:

**Comment by svenb1234** [comment]
Sure. I do run only stable releases though. So 20.0.3 is probably the next release I update to if 19 does not get any releases anymore.

**Comment by Mikescops** [comment]
Then this will be for 21 release :+1:

**Comment by Mikescops** [comment]
#480 should do the trick, but @skjnldsv we should think about having infinite scroll there too.
