### ISSUE TITLE
"Shared albums" does not show albums you shared with others

### ISSUE THREAD

**Issue by strugee** [nextcloud/photos#299]
**Is your feature request related to a problem? Please describe.**

I have a few folders shared that I expected to show up in the "Shared albums" tab. I actually thought Photos was buggy until I happened to read in another bug that it's only albums that other people have shared with you. We should rename it to avoid this confusion.

**Describe the solution you'd like**

"Shared with me" seems like a good description.

**Describe alternatives you've considered**

"Albums shared with me" maybe? It's a little wordy though. Or maybe "Shared with you"? Let us bikeshed

**Additional context**

I'll probably try and poke at this and submit a PR if I get the time but someone else should feel free to get to it before me ;)

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Not sure I understand. "Shared albums" should of course also show albums that you shared eith others, just like the "Shared" section in Files.

**Comment by strugee** [comment]
Right, that makes sense to me too, but currently it doesn't do that. I figured this rename would be better to alleviate confusion in the short term until that's implemented. I actually don't know if there's a bug on file for it; I can check later when I'm not on mobile :-)

**Comment by t2d** [comment]
To me "Shared photos" is just empty. It shows neither albums shared with me nor by me.
NC: 18.0.4.2
Photos: 1.0.0

**Comment by jancborchardt** [comment]
@t2d could you open a separate issue for this? And please include any errors from the console or from the admin settings. :)
