### ISSUE TITLE
"&" in filename prevents the display of images when sharing via link

### ISSUE THREAD

**Issue by Boki4d** [nextcloud/photos#301]
**Description**
When you share a folder/album via link and a picture contains a "&" in its name, the picture is not displayed in the preview

![Screenshot_20200423_181329](https://user-images.githubusercontent.com/62222212/80123086-b4990980-858e-11ea-8829-e38b5acd6cd7.png)

After renaming the file (removing the "&") the image is displayed in preview.

Tested with NC 18.0.4.

**Comment by skjnldsv** [comment]
@juliushaertl I thought that was fixed in viewer?

**Comment by juliushaertl** [comment]
I guess not with the revert https://github.com/nextcloud/viewer/issues/415 but I haven't looked into that since then.

**Comment by skjnldsv** [comment]
I will then! :)
Thanks

**Comment by skjnldsv** [comment]
duplicate of https://github.com/nextcloud/viewer/issues/415
