### ISSUE TITLE
Clarify Roadmap/Features that are planned

### ISSUE THREAD

**Issue by karkraeg** [nextcloud/photos#302]
Hi, right now (Nextcloud 18.0.4) the Photos App is kind of plain: For example there is no filtering (show only pictures from Folder Xy, only Videos...), no option to jump to a specific Time, no option to delete or share individual pictures.

This Repo should clarify whats going to be implemented and what the rough timeframe for this is. Right now there is only [this comment in the Forums](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/32) which does not elaborate what the "greater plan" of this app is.

Thanks!

**Comment by skjnldsv** [comment]
Hi!
You can filter the scheduled tickets by using the filters.
If you were looking for ETA though, there is none.
But if there was some, you would see them with the milestone on the right.

We proceed like that for every app shipped with server in nextcloud.
Thanks for your interest!
