### ISSUE TITLE
Tagged Photos empty

### ISSUE THREAD

**Issue by mayonezo** [nextcloud/photos#304]
**Describe the bug**
I see the heading "Tagged photos" but no photos appear. It's just white space.

**To Reproduce**
1. Go to 'Photos'
2. Click on 'Tagged photos'

**Expected behavior**
The photos I tagged with shotwell, picasa and digikam should appear. (I have all of my photos tagged, so there should be a lot.)

**Desktop (please complete the following information):**
 - OS: debian buster
 - Browser: Firefox
 - Version: 75.0

**Browser log**
```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
OCA.Files.Sidebar initialized Sidebar.js:37:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 3 globals.js:66:15
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Viewer initialized Viewer.js:41:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:287
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
TypeError: OCA.Files.DetailTabView is undefined
activity-sidebar.js:561:24
    <anonymous> https://*my domain*/nextcloud/js/activity/activity-sidebar.js?v=04f0eb24-1:561
    <anonymous> https://*my domain*/nextcloud/js/activity/activity-sidebar.js?v=04f0eb24-1:761
TypeError: t.Files is undefined
commentmodel.js:13:1
    <anonymous> commentmodel.js:13
    <anonymous> commentmodel.js:93
    Webpack 5
        n
        <anonymous>
        n
        <anonymous>
        <anonymous>
TypeError: OCA.Files.DetailTabView is undefined
versionstabview.js:18:7
    <anonymous> versionstabview.js:18
    Webpack 3
        n
        <anonymous>
        <anonymous>
Current grid config 
Object { marginTop: Getter & Setter, marginW: Getter & Setter, count: Getter & Setter, gap: Getter & Setter, … }
GridConfig.js:39:10
Current grid config 
Object { marginTop: Getter & Setter, marginW: Getter & Setter, count: Getter & Setter, gap: Getter & Setter, … }
GridConfig.js:39:10
Loading next page 1 Timeline.vue:242
Error fetching timeline Error: "Request aborted"
    exports createError.js:16
    onabort xhr.js:73
    exports xhr.js:166
Timeline.vue:194
Promised response from onMessage listener went out of scope bundle.js:7:4571
```

**Comment by skjnldsv** [comment]
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by mayonezo** [comment]
![Screenshot from 2020-04-25 21-19-32](https://user-images.githubusercontent.com/5090215/80288798-bef80680-873a-11ea-9844-6fdffc58ff86.png)

**Comment by skjnldsv** [comment]
> The photos I tagged with shotwell, picasa and digikam should appear. (I have all of my photos tagged, so there should be a lot.)

That should teach me to better read.
Tagged photos displays tagged in Nextcloud. Not in other software.
To support this we need the #226

**Comment by mayonezo** [comment]
I see, that did not cross my mind. For future users running into this problem, is it possible to leave a hint that only photos tagged with Nextcloud will appear?
