### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by steiny2k** [nextcloud/photos#313]
**Is your feature request related to a problem? Please describe.**
I'm an iPhone user, and my phone shoots photos in HEIC format (rather than JPEGs). I chose to disable the "Maximum Compatibility" in the nextcloud app for iPhone, and prefer to upload HEIC files rather than in-phone converted JPEGs.
I'm fine with the Apple eco system, and all devices understand HEIC just fine.

**Describe the solution you'd like**
Show HEIC files as well as JPEG files in the photos app.

**Describe alternatives you've considered**
Enable "Maximum Compatibility" is not an option for me.

**Additional context**
Given the support for HEIC exists in the local imagemagick installation, nextcloud can handle HEIC files pretty well. The files app shows thumbnails and previews. However, photos ignores the files completely.

I've changed the MIMES array in lib/AppInfo/Application.php to include 'image/heic', and the thumbnails appear just fine. However, when clicking on the file, nothing happens, where I would expect the lightbox to appear and give a bigger view of the image.

**Comment by skjnldsv** [comment]
Hi! :)
This is because we need this https://github.com/nextcloud/viewer/issues/4

**Comment by skjnldsv** [comment]
> **Describe alternatives you've considered**
> Enable "Maximum Compatibility" is not an option for me.

What does that means?

**Comment by steiny2k** [comment]
> What does that means?

It means, I do not want to upload the files to nextcloud as JPEGs but rather keep using HEIC as the file format I upload from the nextcloud iOS app to the nextcloud server. And I would like to have the photos app to deal gracefully with them, if the system supports it (imagemagick has support it).

I'll have a look at nextcloud/viewer#4 and see whether I can help there with a PR to get that feature. Thanks for pointing me in the right directions.

**Comment by skjnldsv** [comment]
You're welcome! Thanks for your interest :)
Let me know if I can help pointing other stuff or if you're confused about some part :wink:

**Comment by steiny2k** [comment]
Hi @skjnldsv, just did the change and sent a PR. Please check https://github.com/nextcloud/viewer/pull/485 as well.

**Comment by manolo4711** [comment]
I'm also an iPhone user with the same wish to use heic format in my nextcloud. I also changed the viewer app like steiny2k instructions. That works for me in the viewer app without any issues. 

No I want also use heic format in the new photo app. So, I add the heic (mime) support to application.php. My test folder structure looks like this: /Photos/test/image.heic

But if I open a heic photo in the photo app I see an error (**Your Albums View**) :
<img width="607" alt="image" src="https://user-images.githubusercontent.com/23011984/83063620-b871ed00-a060-11ea-8b1b-c1aa32f72a59.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/23011984/83063328-3d103b80-a060-11ea-9b45-82ffef781a9f.png">

That's the browser console output:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/23011984/83064416-089d7f00-a062-11ea-8125-d3c7aec16b41.png">

If I open the same heic photo in the photo (**Your photos view**) the photo will be displayed

<img width="764" alt="image" src="https://user-images.githubusercontent.com/23011984/83063766-f3742080-a060-11ea-94fd-1eed68643142.png">

Very strange behavior, where I have no clue to solve the error. The error occur in nextcloud 18.0.4 and 19rc3.

**Comment by skjnldsv** [comment]
Because the viewer doesn't support heic @steiny2k

**Comment by MorrisJobke** [comment]
@skjnldsv Is this solved as well?

**Comment by manojknaikade** [comment]
is this working in Nextcloud 21?

**Comment by skjnldsv** [comment]
Yes if you enable the heic preview provider (see docs)

**Comment by manojknaikade** [comment]
I have it enabled in the config file but the HEIC preview does not work. I opened a help thread on the forum https://help.nextcloud.com/t/heic-in-browser/111656/7

**Comment by joergmschulz** [comment]
alpine users add: `apk add imagemagick-heic`
