### ISSUE TITLE
Delete command from sidebar list

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/photos#315]
Missing a easy fast DELETE command. Maybe in the side bar menu ...

**Comment by skjnldsv** [comment]
see https://github.com/nextcloud/viewer/issues/483

**Comment by 0xBYTESHIFT** [comment]
I can agree, this feature is the most useful yet sill missing. It's not right

**Comment by meichthys** [comment]
@skjnldsv It looks like https://github.com/nextcloud/viewer/issues/483 was merged, but it doesn't look like it it working in Photos.
