### ISSUE TITLE
Stream video on Android and iOS ?

### ISSUE THREAD

**Issue by df911** [nextcloud/photos#317]
Hello,

I’ve setup up Nextcloud 18.0.4 on Nginx 1.14 and PHP7.3-fpm.
I have many videos in MP4 format with different size (from 20 Mo to +1Go)  
I noticed it’s getting downloaded completly before the video player play. 

Is it possible to get video to stream instead of downloaded like Synology Photos does ? 
I installed FFMPEG but I’m pretty sure it has nothing to do with streaming.

Thanks for your feedback !

**Comment by skjnldsv** [comment]
Hey!
Weirdly, it shuold actually pre-load.
For me on desktop it preload automatically and does not wait for the whole file to be loaded. What browser are you using on your mobile?

**Comment by df911** [comment]
Hello,
I use the Nextcloud native app.

**Comment by skjnldsv** [comment]
@tobiasKaminsky ? Maybe the webkit implementation fails here?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky ? Maybe the webkit implementation fails here?

What webkit?
Streaming is done via a special endpoint which allows our built-in media player to stream from this generated url.

**Comment by skjnldsv** [comment]
Wait, there's something not clear here @df911 
Are you streaming on iOS or Android?
What does it have to do with the Photos app? This is only available on your browser (chrome, firefox, edge...)

@tobiasKaminsky sorry, I confused myself, we don't load our apps views in our native mobile apps :facepalm: Sorry :)

**Comment by df911** [comment]
Hi,
I tried to watch video with nextcloud native app on my iPad and my Oneplus (Android).
The videos don't play and I get the message "loading".

**Comment by jakobroehrl** [comment]
Hey @df911 
Is this your problem: https://github.com/nextcloud/android/issues/5800

**Comment by df911** [comment]
Hi,
Yes it is this issue :)

**Comment by jakobroehrl** [comment]
OK, so I will close this issue.
