### ISSUE TITLE
Server version 19 or higher is required

### ISSUE THREAD

**Issue by fingeg** [nextcloud/photos#322]
**Describe the bug**
I have the newest Nextcloud version, but cannot install the photos app. 
I am not sure if I did something wrong, but in the Nextcloud apps list I cannot find the Photos app, so I cloned the app manually into the apps folder, and got the following error when trying to activate the app: `Server version 19 or higher is required`

My Nextcloud version:
18.0.4 (I thougt this is the newest. Am I wrong?)

**To Reproduce**
1. Install Nextcloud
2. Cannot find App

**Expected behavior**
A normal installation in the Nextcloud Apps list

**Screenshots**
![image](https://user-images.githubusercontent.com/37025527/80872051-e0fc0680-8caf-11ea-88a7-405c5c044345.png)
![image](https://user-images.githubusercontent.com/37025527/80872031-c033b100-8caf-11ea-8728-496d5720362d.png)

**Additional context**
-

**Comment by skjnldsv** [comment]
Hi, photos is not available in the appstore. It is shipped automatically with every nextcloud release.
If you want to clone this repository, you need to checkout the stable18 branch
