### ISSUE TITLE
Albums URL bug in subfolders, %2F instead of /

### ISSUE THREAD

**Issue by JohnBenFu** [nextcloud/photos#327]
When you are using the 'albums' feature (index.php/apps/photos/albums/) and clicking through folder hierarchies, sometimes the URL changes wrongly when using Firefox (75.0 on Linux Mint).
When you go to a subfolder of any folder, the URL changes to e.g. "index.php/apps/photos/albums/MyPictures%2FGreece" instead of "index.php/apps/photos/albums/MyPictures/Greece", the / is wrongly displayed as the html-code %2F. When you reload while the browser in is such a subfolder, apache just passes you a 404-error. 
When going to even deeper subfolders, the error continues, / is still displayed as %2F which results in 404-errors when reloading. 

![Screenshot from 2020-05-04 20-43-14](https://user-images.githubusercontent.com/11487762/81002105-ffe1d080-8e48-11ea-9b80-eadef5a13340.png)

I am not skilled enough in php and in the NextCloud backend to pass a suitable correction for the app, so it would be nice, if anybody who feels skilled enough, could fix this little bug.

Greetings, John

**Comment by SimJoSt** [comment]
I can confirm this issue with Chrome as well.

**Comment by skjnldsv** [comment]
Are you all using apache?

**Comment by JohnBenFu** [comment]
Yes, the problem only occurs when using Apache.
When using Nginx, forward-slash still is replaced with %2F sometimes, but reloading the page works nevertheless without problems.
So this could just be an Apache error or even just a wrong web-server configuration.
Nevertheless, the fact that forward-slash sometimes is displayed with %2F cannot be intentionally.

**Comment by skjnldsv** [comment]
I guess this should be fix in a higher level.

**Comment by darmbrust** [comment]
Is URL rewriting supposed to be enabled for a nextcloud deployment?  If so, it would be nice if Nextcloud told us it was off / improperly configured on the admin page, like it does for so many other config issues.

**Comment by mblo** [comment]
Same problem here, with Safari/Edge tested on 19.0.2 (Photos on 1.1.0). My setup runs in a subfolder ("domain.com/sub/..nextcloud") and uses the nc default htaccess rewrite rules.

Any further information required?

**Comment by bars-suk** [comment]
Nextcloud 19.0.4
Server version: Apache/2.4.38 (Debian)

The problem is not fixed!!

**Comment by skjnldsv** [comment]
> Is URL rewriting supposed to be enabled for a nextcloud deployment? If so, it would be nice if Nextcloud told us it was off / improperly configured on the admin page, like it does for so many other config issues.

PR welcome :)
But it's in the documentation yeah https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#additional-apache-configurations

**Comment by darmbrust** [comment]
Are you referring to the https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#pretty-urls ?

I have mod_rewrite enabled on my server.  And all of the other recommended ones as well.  This bug exists with all of those enabled on apache, unless there is a config I need to set that I missed...

**Comment by bars-suk** [comment]
> Nextcloud 19.0.4
> Версия сервера: Apache / 2.4.38 (Debian)
> 
> Проблема не устранена !!

The problem occurs with a subfolder, with one folder there are no problems.

**Comment by skjnldsv** [comment]
@Mikescops this is the issue I was telling you about :)

**Comment by Mikescops** [comment]
Yep, I know, should find something because it's kinda annoying
