### ISSUE TITLE
Krita support

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/photos#329]
Since this app (or the file manager?) supports psd documents can you also add support for Krita (kra) documents?

Thanks!

**Comment by Dragon988** [comment]
Nevermind, apparently this is supported.

**Comment by skjnldsv** [comment]
Is it?
Not with viewer, no?

**Comment by Dragon988** [comment]
> 
> 
> Is it?
> Not with viewer, no?

Sorta. It doesn't work in photos but it does work in the file viewer once you enable 'Krita' as a preview option in the config.php.

I'm not sure if this carriers over to imagemagick though.

It'd be nice for photos to support it but for me the current setup works fine.

**Comment by Dragon988** [comment]
And even then it's just the thumbnails that are generated and not a preview image. Still works for my needs :)
