### ISSUE TITLE
Group photos by tags from exif

### ISSUE THREAD

**Issue by googol42** [nextcloud/photos#335]
**Is your feature request related to a problem? Please describe.**
You cannot group images in /apps/photos/ by the tags from exif  (like you can group them by the tags given in nextcloud). This would be useful as I tag my images (→ exif) and would like to show my selected images to others in my nextcloud. 

**Describe the solution you'd like**
Add an additional category "Tag from exif" (better name to be found) on /apps/photos. `HierarchicalSubject` from exif should be used. If not present `Subject` should be used. Tags should be displayed hierarchical.

**Comment by yekibud** [comment]
@googol42 This is also being discussed in #226
