### ISSUE TITLE
video (mp4) on shared folder with & in folder name does not play

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/photos#342]
**Describe the bug**
If i want to play a video on a public link in a folder with "&" i get an error.
I think the encoding is wrong.

**To Reproduce**
Read https://help.nextcloud.com/t/bug-in-video-play-because-of-folder-and-or-file-name/82794

**Expected behavior**
Video playing should play for every folder name inkl. &-character

**Screenshots**
see link above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 68.7 LTS 

**Browser log**
HTTP 404 for:
https://xxx.xx/u/s/QtbbmE5QCXGH7MJ/download?path=/colours%20&%20numbers%20&%20animals/1.%20learning%20the%20numbers/&files=1.%20learning%20the%20numbers%200-10.mp4

**Additional context**
For details read my forum entry see link above.

**Comment by skjnldsv** [comment]
Duplicicate of #301
