### ISSUE TITLE
iOS Live Photos Support

### ISSUE THREAD

**Issue by phenomax** [nextcloud/photos#344]
**Describe the solution you'd like**
Support of iOS Live Photos, as discussed on the old repo's issue tracker nextcloud/gallery

**Additional context**
https://developer.apple.com/live-photos/

**Comment by yvolchkov** [comment]
+1

**Comment by axheli** [comment]
+1

**Comment by andyxheli** [comment]
this would be a real nice feature

**Comment by davidsteglich** [comment]
+1

**Comment by meichthys** [comment]
For reference, the iOS Nextcloud app does seem to support live photos.

**Comment by miaulalala** [comment]
Already works in the viewer app: https://github.com/nextcloud/viewer/pull/80

**Comment by miaulalala** [comment]
Thanks for testing! Maybe it used to work, but seems like it doesn't now. @skjnldsv any ideas?

**Comment by skjnldsv** [comment]
> Maybe i have something configured incorrectly, but when i click on a photo that has a live video component, it is not played when viewing it through the viewer. Or perhaps Memories has made some kind of change to the photo/video files which has interfered with how Photos presents them.

Please share an example of what you think a live photo is :)
Do you have two files or one?

**Comment by skjnldsv** [comment]
As I expected. We already support this. If both files are next to each others, the video will start and once played display the  image as a static poster of the video. 
Tested with your files, and it works (the mov support on the other hand is not universal depending on your OS and browser)

**Comment by skjnldsv** [comment]
But I'll keep it  opened, because I think there are room for improvements in the photos UI to make it more visible that a file is a live photo.
But opening one works and is supported by nc :)

**Comment by skjnldsv** [comment]
> Hello under my server the files are not shown as one but two under Photos all media the live photos files should be as one

yes and no. Unfortunately some users want to actually see both, because this feature is also used regardless of live photos. Some users are creating posters for their videos and having the same file names is the way to go.
Nonetheless, for Photos, it might make sense to indeed hide the picture.

**Comment by skjnldsv** [comment]
> How do we make the files "next to each other".

They need to have the same file name

`image1.jpg` and `image1.mp4`

**Comment by AndyXheli** [comment]
@skjnldsv 

My files are showing the same one is .jpg and other is .mov and under the photos app they are not showing together 

![image](https://github.com/nextcloud/photos/assets/59488153/2e900075-cb8b-48b4-90f2-a542952a00be)
![image](https://github.com/nextcloud/photos/assets/59488153/db088b92-4e50-4ed9-a0f2-d3b0c8d8cc49)
