### ISSUE TITLE
"An error ocurred" when using the photos app

### ISSUE THREAD

**Issue by philfry** [nextcloud/photos#348]
**Describe the bug**
After upgrading from NC 17.0.4 to 18.0.4 the gallery app vanished and was replaced by the photos app.
Unfortunately, when trying to use this app, I get "Es ist ein Fehler aufgetreten" ("An error occured") with these paths:
- /index.php/apps/photos/
- /index.php/apps/photos/favorites

These paths work, though:
- /index.php/apps/photos/albums
- /index.php/apps/photos/shared
- /index.php/apps/photos/tags

There's nothing of value in the logs.

**To Reproduce**
1. Go to nextcloud 18.0.4 installation
2. Click on "Fotos" ("Photos")
3. See error

**Expected behavior**
The photos app to show either some photos or a message that I haven't set up any favorites yet or whatever the app is trying to say with "An error occured".

**Screenshots**
![Screenshot from 2020-06-02 09-21-38](https://user-images.githubusercontent.com/1649785/83492247-490e5a00-a4b3-11ea-8aed-9cdf463a6fc1.png)
![Screenshot from 2020-06-02 09-21-43](https://user-images.githubusercontent.com/1649785/83492251-49a6f080-a4b3-11ea-9a61-0040b24766e5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox, Chrome
 - Version [e.g. 22] latest

**Browser log**
```
Error fetching timeline Error: "Request failed with status code 405"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
Timeline.vue:194
    t Timeline.vue:194
    c Multiselect.js:119
    _invoke Multiselect.js:119
    e Multiselect.js:119
    S photos.4.js:65
    s photos.4.js:65
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by petrich** [comment]
Same here

**Comment by petrich** [comment]
Problem fixed on my side. The Fix was... allowing Apache the HTTP Method `SEARCH`.
After this... all works again.

**Comment by philfry** [comment]
You're right, thanks!
For those using apache httpd with `mod_allowmethods` use
```
AllowMethods reset
```
as there's no dedicated option for `SEARCH`.

**Comment by charredchar** [comment]
I ran across this issue as well, may I get a little more detail on the fix? I looked up mod_allowmethods and `AllowMethods reset` but I want to verify how I should go about this. I found mod_allowmethods was not already enabled, I used the install script from nextcloud/vm. Where exactly would I put the `AllowMethods reset` option? Would this need to be in the `nextcloud.conf` or `apache2.conf`?
