### ISSUE TITLE
Photos should honor enabled preview providers

### ISSUE THREAD

**Issue by J0WI** [nextcloud/photos#362]
**Describe the bug**
E.g. even if `avconv` and `ffmpeg` are not available or enabled, photos is still trying to load thumbnails.

**To Reproduce**
1. Set `'enable_previews' => false`
2. Go to photos
3. Loading forever

**Expected behavior**
Exclude disabled preview providers or do not load the app at all if previews are disabled.

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/photos/pull/509
