### ISSUE TITLE
Support ARW and possibly other raw image formats

### ISSUE THREAD

**Issue by DanBenHa** [nextcloud/photos#366]
**Is your feature request related to a problem? Please describe.**
Photos doesn't show ARW images from a Sony camera.

**Describe the solution you'd like**
Show ARW images.

**Describe alternatives you've considered**
Rename ARW to TIF. But TIF doesn't seem to be supported either.

**Comment by mailinglists35** [comment]
can this be used? https://github.com/LibRaw/LibRaw

**Comment by mailinglists35** [comment]
After "download and enable" camerarawpreviews app, then re-run previewgenerator I can see ARW files in Photos

**Comment by skjnldsv** [comment]
Yes, this is a job for the camerarawpreviews app :)

**Comment by prairietree** [comment]
@mailinglists35 when you re-run previewgenerator, was that running the command `php occ preview:generate-all`?

I am asking because I am trying to get TIFF to work but even after installing "Camera RAW Previews" app and running php occ preview:generate-all I am not seeing any of my TIFF files.

Thanks for your help.

**Comment by mailinglists35** [comment]
I gave up on nextcloud as a Media app. It's really far from usable. I just use it as a cloud regular file manager.

**Comment by prairietree** [comment]
Thanks @mailinglists35 
That is pretty much to the point I am at again! Again because I tried to get NextCloud set up as a way to manage and document and share photos a few years back. I ended up giving up on it than. I think I made it farther this time then before. I thought maybe it had improved by now, but get the impression that Photos is not really designed as a way to manage photos but rather a way view them (but I am not impressed by the slide show viewer). 

So far I have found the Files app more usable, even for photos. 

I am going to look into some other photo management programs. 

Thanks again and have a good day.

**Comment by pulsejet** [comment]
You might be missing some configuration, e.g. [file type support](https://github.com/pulsejet/memories/wiki/File-Type-Support#heic-and-tiff) or max preview generation [limits](https://github.com/pulsejet/memories/wiki/Configuration#imagevideo-support). If it still doesn't work, might be a bug in the preview generation process. A sample photo might be useful here.

> I thought maybe it had improved by now, but get the impression that Photos is not really designed as a way to manage photos but rather a way view them (but I am not impressed by the slide show viewer).

I try avoiding advertising something I built, but you might want to try [Nextcloud Memories](https://github.com/pulsejet/memories). It fixes several outstanding issues with Photos and [can be considered at par](https://github.com/meichthys/foss_photo_libraries) with all other open source photo solutions.

**Comment by prairietree** [comment]
Thanks, in this case the previews work fine. In the Files app I can see the thumbnails and open the slide show viewer for the TIFF files. It is just in photos they do not show in the folders view. More info here https://github.com/nextcloud/photos/issues/1754

Thanks for the recommendation. I will take a look at it.

**Comment by mailinglists35** [comment]
> I try avoiding advertising something I built, but you might want to try [Nextcloud Memories](https://github.com/pulsejet/memories). It fixes several outstanding issues with Photos and [can be considered](https://github.com/meichthys/foss_photo_libraries) one of the best open source photo solutions.

the feature list looks promising, @pulsejet !
is there any chance you could setup a demo instance, accessible both from web and from ios/android clients?

**Comment by pulsejet** [comment]
@mailinglists35 here's the demo: https://memories-demo.radialapps.com/apps/memories/
There is no native mobile client yet, but the web app is very optimized for mobile (try it out). For auto upload you'll need the official Nextcloud mobile app.

**Comment by pulsejet** [comment]
> Thanks, in this case the previews work fine. In the Files app I can see the thumbnails and open the slide show viewer for the TIFF files. It is just in photos they do not show in the folders view. More info here #1754

Ah I see. It's just that tiff isn't whitelisted as a photo format.
https://github.com/nextcloud/photos/blob/1a34ca7aaa5a4ddbe449161d028176d17d4867e4/lib/AppInfo/Application.php#L49

**Comment by prairietree** [comment]
Wow. Interesting, so photos only supports four image formats and two video formats. But why? Is it that difficult to support more?

It seems like that information should be one of first pieces of information in any description of photos app. It would save a lot of people a lot of time.

**Comment by skjnldsv** [comment]
> Wow. Interesting, so photos only supports four image formats and two video formats. But why? Is it that difficult to support more?

Because it has been discussed in the past and this is the list of photos-related images that we (community+nextcloud, back when this was discussed) came up with :)
It's not complicated to support more, but this has to make sense. Like adding "bmp" support would not make sense to me (for example) in a Photos app :)

**Comment by skjnldsv** [comment]
Feel free to open a pull request to add support for it by editing this file:
https://github.com/nextcloud/photos/blob/1a34ca7aaa5a4ddbe449161d028176d17d4867e4/lib/AppInfo/Application.php#L49-L58

Then it can be discussed on a case-by-case basis on said pull request! :wink:

**Comment by prairietree** [comment]
Thanks @skjnldsv, Is there a mission statement for Photos? I feel like maybe Photos is not trying to be the app that I need and I do not want to conflict with the vision of others. 

I have a large collection of scanned family photos that I am trying to organize, notate, and share. The requirements and work flow for this are different than someone that just want to sync there phone and have a place find and view their photos.

An app cannot be all things to all people. It might be best if Photos just focused on it core user base and pointed other users to some other project. There is a lot of discussion 

online about getting Next Cloud/Photos to work with TIFF  and RAW and I was thinking that this is maybe a thing but maybe from the maintainers view it is not a thing. So it is just kind of confusing. 

As an alternative to having a discussion about adding every semi-common photo format, if it is within Photos scope, maybe there should be an option for the Next Cloud admin to turn on or off different formats. Perhaps this could be based on what system level tools/libraries are available to support  them.

**Comment by skjnldsv** [comment]
@prairietree I think you nailed the dilemma :)
It's hard sometimes on Nextcloud to find the sweet spot, without adding 3561 config switch to fit everyone's needs :)

Having a mission statement would be nice, unfortunately, I don't think there is any written down :disappointed: 
In any case, the discussion is always opened and welcome here (as long as there isn't already a ticket with lots of comments addressing the same issue :wink: )
