### ISSUE TITLE
Photos depends on Viewer

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/photos#38]
When accessing the app, the Nextcloud "Interner Serverfehler" page shows up.

Related Nextcloud error entry:
```
[index] Error: Exception: Class 'OCA\Viewer\Event\LoadViewer' not found at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 123
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Photos\Contr ... }}, "index")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Photos\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "photos.page.index"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "photos.page.index"})
3. /var/www/nextcloud/lib/private/Route/Router.php line 298
   call_user_func(OC\AppFramework\ ... {}, {_route: "photos.page.index"})
4. /var/www/nextcloud/lib/base.php line 1006
   OC\Route\Router->match("/apps/photos/")
5. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /nextcloud/apps/photos/
from 95.81.18.51 by Micha at 2019-12-10T13:13:41+01:00
```

As a guess, I enabled the Viewer app and voila! No error, but first access takes VERY long to generate previous I guess. However it works.

I don't know if app dependencies are such a great idea, especially since there seems to be no infrastructure to handle those, e.g. enabling required apps automatically and warn when disabling dependencies etc. Wouldn't it make sense to simply merge those two apps then? I was already confused when Viewer app was added the first time, added as core app, while Gallery app already provided all feature I require, hence I disabled obsolete Viewer. Now Gallery seems to have been replaced by Photos?

At least a missing app should be handled gracefully with clear info, instead of such an error, which is hard to read for most.

**Comment by skjnldsv** [comment]
Welcome!! Yes, your version of viewer is not up to date :)
Though we should add a warning and allow the user to enable the viewer app from here! :rocket: 

> but first access takes VERY long to generate previous I guess

Yes performances needs to be worked on for the final release see #7

**Comment by MichaIng** [comment]
@skjnldsv 
> Yes, your version of viewer is not up to date :)

Should be? It is the one pulled with NC 18.0.0 Beta1 update, for what I can see the only issue really was that I had it disabled.

> Though we should add a warning and allow the user to enable the viewer app from here!

If this can be caught somehow, would be great. However, if app dependencies should become a common case in Nextcloud, then probably an app dependency infrastructure should be added to core.

> Yes performances needs to be worked on for the final release

Jep, really ALL image previews seem to be generated on access. It makes sense to limit this to the ones that are actually shown on screen and load more only when scrolling. Pre-generating should be left to PreviewGenerator app then, if required. I have it, but configured previews to be generated for Files app and Gallery sizes only, hence the new size that Photo app seems to require is missing 😉.
