### ISSUE TITLE
preview got duplicated when saw all the photos

### ISSUE THREAD

**Issue by zahradehghanpur** [nextcloud/photos#404]
**Describe the bug**
when see and open all the photos and go back , the previews of each of them got doubled. And when refresh the page ,everything go back to their normal behaviour.
**To Reproduce**
1. Go to 'photos'
2. Click on 'all the photos and see them all'
3. In 'Your Photos' section you will see all the preview got duplicated.

**Screenshots**
![image](https://user-images.githubusercontent.com/56598444/88542911-6e8b9000-d02c-11ea-97ec-45910714508a.png)

**Comment by Mikescops** [comment]
FYI @skjnldsv I can reproduce this on master too
![image](https://user-images.githubusercontent.com/4266283/95095224-13ac9e00-072b-11eb-979f-194638b274d8.png)

**Comment by Mikescops** [comment]
This is likely fixed by #468 :tada:

**Comment by Mikescops** [comment]
This is fixed.
