### ISSUE TITLE
Diaporama timing to fast, could it be adjustable ?

### ISSUE THREAD

**Issue by feydreva** [nextcloud/photos#428]
**Is your feature request related to a problem? Please describe.**
During diaporama, it changes pictures every 3 seconds

**Describe the solution you'd like**
We should be able to choose the timimg during which the photo is displayed.. 3s is too fast

**Describe alternatives you've considered**
A drop down, with 3s, 5s, 10 for exemple ?

**Comment by skjnldsv** [comment]
Dupe of https://github.com/nextcloud/viewer/issues/447
