### ISSUE TITLE
Modify slideshow feature

### ISSUE THREAD

**Issue by timoschrader88** [nextcloud/photos#430]
Hey folks,

just wondering if (and where) I can modify the slideshow feature in Nextcloud to, potentially, shuffle photos, create a never-ending loop, or extend the time photos are shown. Whether it's via the "https://MYDOMAIN.com/nextcloud/index.php/apps/photos/" folder path or a sub-path like "https://MYDOMAIN.com/nextcloud/index.php/apps/photos/favorites" doesn't matter. I just want to run the slideshow basically like a digital photo frame.

I was hoping I could just edit some file to modify the slideshow script, but I have little to no experience with coding to find or edit this feature.

Photos are private so none of this can be public.

Please do let me know how to make this work as it would be a lovely way to make use of all the TBs of photos my wife and I have sitting on my NAS.

Thank you!

**Comment by skjnldsv** [comment]
Hey!
Thanks for this suggestion.
There is currently no plans for it, but let's ask @jancborchardt his opinion on this :)

Have a great day!

**Comment by timoschrader88** [comment]
Oh, my bad, sorry! I really thought I could just somehow modify the slideshow in some config file for it to add shuffle and adjust the display time etc. I didn't know it's actually not possible yet. Thank you so much for letting me know! I'll keep an eye out for any changes to the slideshow feature.

Have a nice day!

**Comment by skjnldsv** [comment]
> I really thought I could just somehow modify the slideshow in some config file

This is something we don't do at nextcloud, because it suddenly create very complex configs and setups, and makes it hard for us to maintain :)

So, we usually just think if it make sense for a wide array of users and if it does, we add this to the "to develop" list :wink: 
Let's wait for Jan's input :sun_behind_large_cloud:

**Comment by jancborchardt** [comment]
The time for showing could be easily adjusted in the code I guess @skjnldsv? The drawback is that it could reset on every app update @timoschrader88 

Otherwise there are no plans to offer customization of the slideshow feature at the moment. :)

**Comment by skjnldsv** [comment]
> The time for showing could be easily adjusted in the code I guess

No, it would needs compile and fail integrity :confused:

**Comment by timoschrader88** [comment]
No worries at all, thank you both for the clarification! Would be awesome to use the existing photo viewer features to run/shuffle a slideshow. I could set this up on an unused device, a dedicated WiFi digital frame, or stream the slideshow out to friends and family. I could, for example, make a specific folder for my parents, setup a device that hooks up to my Nextcloud, and then just let it run the slideshow in their home on their wall or whatever.

Either way, thanks so much and I'll keep an eye out even if no customization is currently planned. You've been lovely to respond to me.

**Comment by jancborchardt** [comment]
Thanks a lot for understanding and your friendly reply @timoschrader88! :) I’ll then close this issue
