### ISSUE TITLE
Invalid URL placed into URL bar with subfolders

### ISSUE THREAD

**Issue by darmbrust** [nextcloud/photos#431]
**Describe the bug**
In the Photos app, navigating to a subfolder causes the URL bar to have an escaped '/' put in the URL, which is then not handled correctly if you refresh the page, causing a 404 error.

**To Reproduce**
1. In Photos, browse to a nested folder.  For example: nextcloud/index.php/apps/photos/shared/MyPhone/Camera
2. Click the browser refresh button
3. Get a 404 error from the server

**Expected behavior**
Refresh the page properly

**Additional context**
In my case, I'm opening Photos, going to the "Shared" photos, as they are shared from an account my phone uses.  Click on a subfolder like "MyPhone" and then another subfolder like "Camera".

The URL that gets generated for me at this point looks like:

nextcloud/index.php/apps/photos/shared/MyPhone%2FCamera

That URL does not resolve properly.

Correcting the URL to 
nextcloud/index.php/apps/photos/shared/MyPhone/Camera

And it works correctly.

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/photos/issues/327

**Comment by bars-suk** [comment]
The problem is not solved
