### ISSUE TITLE
Date separators

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#45]
Add date separators/dividers in the timeline view

**Comment by jancborchardt** [comment]
Simple way to start would be month dividers:

- January 2020
- December 2019
- November 2019
- etc.

The month dividers are headings, and the year can be shown with grey maxcontrast color to not take so much visibility.

The dividers should be sticky when scrolled down. The container should not have any background color so it simply overlays the images.

**Comment by jancborchardt** [comment]
Simple way to start would be month dividers:

- January 2020
- December 2019
- November 2019
- etc.

The month dividers are headings, and the year can be shown with grey maxcontrast color to not take so much visibility.

The dividers should be sticky when scrolled down. The container should not have any background color so it simply overlays the images.

**Comment by Mikescops** [comment]
I tried to implement this but failed because it needs a totally different data structure from what we have now.
@skjnldsv if you have hints on how to acheive this, would be nice

**Comment by jancborchardt** [comment]
@Mikescops for reference, can you explain what the current data structure is, and what we would ideally need?

**Comment by Mikescops** [comment]
For now we store what we get from the DAV in a simple array [ ].
It's nice when you have a single sorted list but not when you need to group the entries in it.

For instance i tried this structure:
```
{
     "2019-12" : [ img1, img2 ],
     "2020-01" : [ img3]
}
```
It could work well (i tried it), but we need to change lot of stuff, including the way we load more files when reaching the bottom.

**Comment by skjnldsv** [comment]
@Mikescops there is absolutely no rush for it now.
We're also in feature freeze for 18, so thi sis scheduled for the next release anyway :)

**Comment by Mikescops** [comment]
Yes sure, i was considering this as well!
