### ISSUE TITLE
Nothing happens when clicking "Share this folder" within a folder

### ISSUE THREAD

**Issue by maetthew** [nextcloud/photos#467]
**Describe the bug**
Clicking "Share this folder" within a folder does nothing

**To Reproduce**
1. Go to "Photos app"
2. Click on "Your albums"
3. Open a folder/album
4. Click "Share this folder" button

**Expected behavior**
I assume a panel is supposed to pop out from the right like the other share behaviour within Nextcloud?

**Screenshots**
No screenshot, can provide a video on request.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tested with Firefox 81.0.1 (that has addons installed), Chrome 86.0.4240.75 and Edge 85.0.564.70. Chrome and Edge doesn't have addons installed

**Smartphone (please complete the following information):**
 - Device: OnePlus 67
 - OS: Android 10
 - Browser Brave
 - Version 1.14.86

**Browser log**
vue.runtime.esm.js:1888 TypeError: e.$refs.sidebar.updateTabs is not a function
    at i.<anonymous> (Sidebar.vue:288)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at We (vue.runtime.esm.js:1906)
$e @ vue.runtime.esm.js:1888
Ge @ vue.runtime.esm.js:1879
He @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1982
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
resetData @ Sidebar.vue:285
(anonymous) @ Sidebar.vue:419
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
open @ Sidebar.vue:414
showSidebar @ Navigation.vue:138
execFirstAction @ Actions.js:66
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Er.i._wrapper @ vue.runtime.esm.js:6917
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
time @ Sidebar.vue:161
mn.get @ vue.runtime.esm.js:4479
mn.evaluate @ vue.runtime.esm.js:4584
(anonymous) @ vue.runtime.esm.js:4836
subtitle @ Sidebar.vue:153
mn.get @ vue.runtime.esm.js:4479
mn.evaluate @ vue.runtime.esm.js:4584
(anonymous) @ vue.runtime.esm.js:4836
appSidebar @ Sidebar.vue:194
mn.get @ vue.runtime.esm.js:4479
mn.evaluate @ vue.runtime.esm.js:4584
(anonymous) @ vue.runtime.esm.js:4836
(anonymous) @ Sidebar.vue?f775:1
e._render @ vue.runtime.esm.js:3548
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ Sidebar.vue:422
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
Promise.then (async)
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
open @ Sidebar.vue:414
showSidebar @ Navigation.vue:138
execFirstAction @ Actions.js:66
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Er.i._wrapper @ vue.runtime.esm.js:6917
vue.runtime.esm.js:1888 TypeError: n.$refs.sidebar.updateTabs is not a function
    at i.<anonymous> (Sidebar.vue:434)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at We (vue.runtime.esm.js:1906)
$e @ vue.runtime.esm.js:1888
Ge @ vue.runtime.esm.js:1879
He @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1982
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ Sidebar.vue:422
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
Promise.then (async)
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
open @ Sidebar.vue:414
showSidebar @ Navigation.vue:138
execFirstAction @ Actions.js:66
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Er.i._wrapper @ vue.runtime.esm.js:6917
capabilities.js:32 OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities
getCapabilities @ capabilities.js:32
get @ ConfigService.js:181
inputPlaceholder @ SharingInput.vue:120
mn.get @ vue.runtime.esm.js:4479
mn.evaluate @ vue.runtime.esm.js:4584
(anonymous) @ vue.runtime.esm.js:4836
(anonymous) @ SharingInput.vue?391c:1
e._render @ vue.runtime.esm.js:3548
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
Tn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
p @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ SharingTab.vue:230
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
Ne @ files_sharing_tab.js?v=28b1ef34-0:1
s @ files_sharing_tab.js?v=28b1ef34-0:1
Promise.then (async)
Ne @ files_sharing_tab.js?v=28b1ef34-0:1
s @ files_sharing_tab.js?v=28b1ef34-0:1
(anonymous) @ files_sharing_tab.js?v=28b1ef34-0:1
(anonymous) @ files_sharing_tab.js?v=28b1ef34-0:1
getShares @ files_sharing_tab.js?v=28b1ef34-0:1
beforeMount @ SharingTab.vue:195
Qe @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
e @ vue.runtime.esm.js:4043
Tn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
p @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ Sidebar.vue:422
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
Promise.then (async)
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
open @ Sidebar.vue:414
showSidebar @ Navigation.vue:138
execFirstAction @ Actions.js:66
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Er.i._wrapper @ vue.runtime.esm.js:6917
capabilities.js:32 OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities
getCapabilities @ capabilities.js:32
data @ SharingLinkList.vue:80
(anonymous) @ vue.runtime.esm.js:1219
(anonymous) @ vue.runtime.esm.js:4748
(anonymous) @ vue.runtime.esm.js:4705
gn @ vue.runtime.esm.js:4642
e._init @ vue.runtime.esm.js:5006
i @ vue.runtime.esm.js:5154
(anonymous) @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
(anonymous) @ vue.runtime.esm.js:5978
p @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ SharingTab.vue:230
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
Ne @ files_sharing_tab.js?v=28b1ef34-0:1
s @ files_sharing_tab.js?v=28b1ef34-0:1
Promise.then (async)
Ne @ files_sharing_tab.js?v=28b1ef34-0:1
s @ files_sharing_tab.js?v=28b1ef34-0:1
(anonymous) @ files_sharing_tab.js?v=28b1ef34-0:1
(anonymous) @ files_sharing_tab.js?v=28b1ef34-0:1
getShares @ files_sharing_tab.js?v=28b1ef34-0:1
beforeMount @ SharingTab.vue:195
Qe @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
e @ vue.runtime.esm.js:4043
Tn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
p @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6216
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6193
w @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
mn.get @ vue.runtime.esm.js:4479
mn.run @ vue.runtime.esm.js:4554
un @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
We @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
mn.update @ vue.runtime.esm.js:4544
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
fn.set @ vue.runtime.esm.js:4631
(anonymous) @ Sidebar.vue:422
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
Promise.then (async)
w @ sidebar.js?v=28b1ef34-0:1
i @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
(anonymous) @ sidebar.js?v=28b1ef34-0:1
open @ Sidebar.vue:414
showSidebar @ Navigation.vue:138
execFirstAction @ Actions.js:66
Ge @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Er.i._wrapper @ vue.runtime.esm.js:6917
SharingInput.vue:292 recommendations [__ob__: we]

**Comment by maetthew** [comment]
I should add that this is with an almost fresh install of NextCloud 20, with a few apps installed.

**Comment by maetthew** [comment]
@skjnldsv Thanks for the quick fix! I noticed clicking the "Open sidebar" is kinda quirky too. Sometimes I can see the button upon opening an image, and then disappearing when the image has finished loading. I've seen it not disappear upon loading, but clicking it removes it. In the console I get this error:

TypeError: n.$refs.sidebar.updateTabs is not a function

Do these two errors correlate, or should I open a new ticket for this?

**Comment by skjnldsv** [comment]
Same issue :)
