### ISSUE TITLE
Previews sometimes looks pixelized

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#49]
Because we generate previews with size in power of 4, the images preview are loaded with 256px. The next step is 1024 which is a lot more data to load

cc @jancborchardt @rullzer

**Comment by rullzer** [comment]
Yeah. This is how it is for now. I have no real solution yet.

**Comment by skjnldsv** [comment]
Ah, I understand why.

The preview manager use the maximum, meaning if your picture is 2560*1000, and you request for a 256px, instead of being 655x256, it will be 256x100 (which make sense)
But since we're cropping the images and fitting them to a square...

The preview manager have an option to request a square (`&a=false`) but the cropping is not centered, so maybe we could fix this?
Because this works well in landscapes, but not in portrait
![Capture d’écran_2019-12-22_14-50-03](https://user-images.githubusercontent.com/14975046/71322648-6386e500-24ca-11ea-8137-88b95544f006.png)

**Comment by skjnldsv** [comment]
Just tried it, works nicely!
