### ISSUE TITLE
Translators need context for "Enable cropped layout"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/photos#494]
https://github.com/nextcloud/photos/blob/4de71e575aa35a4cf95a2ef8c1662b0ef018eabc/src/components/Settings/CroppedLayoutSettings.vue#L33

Is Layout same like "view"?

Is cropped a wording for sqare view?

**Comment by Mikescops** [comment]
Yes! Maybe we can change the initial wording if you think "square" is more appropriate.

**Comment by Mikescops** [comment]
We go from this:
![image](https://user-images.githubusercontent.com/4266283/96334259-b17b6380-106f-11eb-9b50-10a197144674.png)

To this:
![image](https://user-images.githubusercontent.com/4266283/96334267-bb04cb80-106f-11eb-9840-4be390add285.png)

**Comment by Valdnet** [comment]
I also wondered about this when translating.

@Mikescops Thanks for the clarification 😉.

**Comment by skjnldsv** [comment]
Thank you all for translating!! You are incredible!! :hugs:

**Comment by rakekniven** [comment]
My vote would be "Enable square view" and "view" instead of "layout".

**Comment by Mikescops** [comment]
Ok got it, thanks!

**Comment by Valdnet** [comment]
So maybe: "Enable squared photos view" 😁.

**Comment by rakekniven** [comment]
We are in photos app already, no need to add the word "photos".

What is the turn around action? "Enable default view"?

**Comment by rakekniven** [comment]
See my comment at #500
