### ISSUE TITLE
HEIC photo viewing does not work in nextcloud 20

### ISSUE THREAD

**Issue by ntimo** [nextcloud/photos#498]
**Describe the bug**
Currently viewing heic images does not work in  Nextcloud 20. But this MR seems to have added heic support https://github.com/nextcloud/photos/pull/318. Also opening the images using in the files app of nextcloud works and the preview of the image gets opened correctly.

**To Reproduce**
1. Open the Photos page
2. Select a Album
3. Open a heic image

**Expected behavior**
The image should be displayed.

**Screenshots**
![Screenshot 2020-10-19 at 09 24 51](https://user-images.githubusercontent.com/6145026/96414138-fd9fe280-11ec-11eb-9932-948fd442ae53.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Browser log**
![Screenshot 2020-10-19 at 09 26 02](https://user-images.githubusercontent.com/6145026/96414240-23c58280-11ed-11eb-8421-a864c0efb466.png)

**Comment by skjnldsv** [comment]
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it, then do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

I assume there will be some failed requests in red

**Comment by ntimo** [comment]
@skjnldsv 
Hey sure here is the screenshot. But there is are no failed requests:
![Uploading Screenshot 2020-10-19 at 12.21.49.png…]()

**Comment by skjnldsv** [comment]
Ah, you need to enable the previews for heic on your nextcloud config.
Though we should know what file is available for the previews, related issue: https://github.com/nextcloud/server/issues/22873

**Comment by ntimo** [comment]
@skjnldsv I have the following in my nextcloud server config.php:
```
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\HEIC',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\XBitmap',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\TXT',
    8 => 'OC\\Preview\\MarkDown',
    9 => 'OC\\Preview\\OpenDocument',
    10 => 'OC\\Preview\\Krita',
  ),
```

this should enable HEIC previews if I am not mistaken right? I also wasn't able to find any documentation about this :(

**Comment by skjnldsv** [comment]
should work™ :)
Can you screenshot the setup warning of your instance in `/settings/admin/overview` ?

**Comment by ntimo** [comment]
Sure there you go :)
![Screenshot 2020-10-19 at 12 34 27](https://user-images.githubusercontent.com/6145026/96439895-757b0680-1207-11eb-855f-7882b85bf687.png)

**Comment by skjnldsv** [comment]
Weird, so I guess you have imagick installed and setup. :thinking:

**Comment by ntimo** [comment]
Yes, I am using the nextcloud docker container nextcloud:20.0.0-apache. So imagick should already be installed :)

**Comment by skjnldsv** [comment]
Can you check the propfind request on your network screenshot and copy/paste the response content here? :)

**Comment by ntimo** [comment]
@skjnldsv 
Sure
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/files/ntimo/Photos/2020/09/20-09-27%2016-04-05%202168.heic</d:href><d:propstat><d:prop><d:getlastmodified>Sun, 27 Sep 2020 21:48:05 GMT</d:getlastmodified><d:getetag>&quot;5f8c1cd55b548&quot;</d:getetag><d:getcontenttype>image/heic</d:getcontenttype><d:resourcetype/><oc:fileid>99754</oc:fileid><oc:permissions>RGDNVW</oc:permissions><oc:size>3751667</oc:size><d:getcontentlength>3751667</d:getcontentlength><nc:has-preview>true</nc:has-preview><nc:mount-type></nc:mount-type><x1:share-permissions xmlns:x1="http://open-collaboration-services.org/ns">19</x1:share-permissions><oc:tags/><oc:favorite>0</oc:favorite><oc:comments-unread>0</oc:comments-unread><oc:owner-id>ntimo</oc:owner-id><oc:owner-display-name>Timo</oc:owner-display-name><oc:share-types/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><nc:is-encrypted/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
```

**Comment by skjnldsv** [comment]
<nc:has-preview>true</nc:has-preview>
So it does have preview, weird that it doesn't use it :thinking:

**Comment by skjnldsv** [comment]
Does it work with this file? 
https://github.com/nextcloud/viewer/blob/master/cypress/fixtures/image.heic?raw=true

**Comment by ntimo** [comment]
Nope does not work. Here is the output of the profind request:
```
<?xml version="1.0"?>
<d:multistatus
    xmlns:d="DAV:"
    xmlns:s="http://sabredav.org/ns"
    xmlns:oc="http://owncloud.org/ns"
    xmlns:nc="http://nextcloud.org/ns">
    <d:response>
        <d:href>/remote.php/dav/files/ntimo/Photos/test/image.heic</d:href>
        <d:propstat>
            <d:prop>
                <d:getlastmodified>Mon, 19 Oct 2020 12:39:50 GMT</d:getlastmodified>
                <d:getetag>&quot;5f8d8942f09e2&quot;</d:getetag>
                <d:getcontenttype>image/heic</d:getcontenttype>
                <d:resourcetype/>
                <oc:fileid>160687</oc:fileid>
                <oc:permissions>RGDNVW</oc:permissions>
                <oc:size>2049547</oc:size>
                <d:getcontentlength>2049547</d:getcontentlength>
                <nc:has-preview>true</nc:has-preview>
                <nc:mount-type></nc:mount-type>
                <x1:share-permissions
                    xmlns:x1="http://open-collaboration-services.org/ns">19
                </x1:share-permissions>
                <oc:tags/>
                <oc:favorite>0</oc:favorite>
                <oc:comments-unread>0</oc:comments-unread>
                <oc:owner-id>ntimo</oc:owner-id>
                <oc:owner-display-name>Timo</oc:owner-display-name>
                <oc:share-types/>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
        <d:propstat>
            <d:prop>
                <nc:is-encrypted/>
            </d:prop>
            <d:status>HTTP/1.1 404 Not Found</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

**Comment by skjnldsv** [comment]
does this returns something for you? https://yourdomain.com/index.php/core/preview?fileId=160687&x=2560&y=1440&a=true

**Comment by ntimo** [comment]
Yes that works fine :)

**Comment by skjnldsv** [comment]
That is weird! :thinking:

**Comment by skjnldsv** [comment]
Can you create a folder with two images in it and share the folder to me?

**Comment by ntimo** [comment]
Sure, you should have received a email with the shared folder :)

**Comment by ntimo** [comment]
Did email share work? :) @skjnldsv

**Comment by tborychowski** [comment]
Installing preview-generator app fixed that for me.

**Comment by ntimo** [comment]
@tborychowski I have it installed, and it still does not work

**Comment by tborychowski** [comment]
@ntimo 
That's weird. 
I'm using the same - docker v20, apache.
And struggling since morning with heic & mov thumbnail generation :-)
Have you tried generating them manually (run this command inside the running container), e.g. (if you're using docker-compose):
```sh
docker-compose exec -u www-data app bash -c ."/occ preview:generate-all -vvv"
```
Does it list your images?
If not try another command (that solved MOV previews for me, but it's a workaround rather than a proper fix):
```sh
docker-compose exec app bash -c "apt update && apt upgrade -y && apt install -y ffmpeg imagemagick ghostscript"
```


Also - it wouldn't be cache would it? :-)
Maybe try opening it in a Private browser window, just to make sure?

**Comment by ntimo** [comment]
Hey @tborychowski,
I am now letting the preview:generation run again. Also clearing my browser cache did not help :).

And yes of course I have the `'enable_previews' => true,` line in my config. Since I have more then 20k images in my nextcloud the generation takes ages and I will have to wait for it to reach the HEIC image folder.

**Comment by skjnldsv** [comment]
> Did email share work? :) @skjnldsv

Received! I will have a look tomorrow :)

**Comment by skjnldsv** [comment]
@ntimo ah, it expired! Please share it again, feel free to put like 3 days on it as I am also working on other areas :wink:  :pray:

**Comment by ntimo** [comment]
Hey @skjnldsv sorry for my late reply. I have now reshared the folder with you. But in the meantime I have completely reinstalled my Nextcloud using local storage since before I was using S3 as primary storage. I also tested if the preview image can be requested for the photo and that works just fine. But the photos app still says it can't display the image.

**Comment by skjnldsv** [comment]
Thanks, I can also see that it works fine.
Ha, coming from the photo app, I can see an issue in my head, I need to investigate.

**Comment by skjnldsv** [comment]
@ntimo are you opening from Albums? or timeline? or tags?

**Comment by ntimo** [comment]
@skjnldsv I am opening from Albums

**Comment by ntimo** [comment]
Thank you for fixing it :) Can't wait for the MR to be merged and for a new release that contains the fix.

**Comment by skjnldsv** [comment]
Merged and backported.
Will be present in the upcoming releases :rocket:

**Comment by montvid** [comment]
@skjnldsv Thanks for merging the fix. Is heic support working in nextcloud 19 or what do you mean by backported? Nextcloud 19 snap does not have heic support so before reporting a bug I wanted to be clear.
