### ISSUE TITLE
.nomedia / .noimage is not working in 20.0.0

### ISSUE THREAD

**Issue by tolotos-rgu** [nextcloud/photos#537]
The webpage gallery of NC 20.0.0 ignore the .noimage / .nomedia files completely.
IOS app shows the same issue and devs said it was no app function.
As it works in NC <= 19.x it must be NC 20 server related.

**Comment by skjnldsv** [comment]
Please search for existing issues before posting
https://github.com/nextcloud/photos/issues/234

**Comment by skjnldsv** [comment]
Regarding the iOS app, this have to me handled with the iOS developer and repository please :)
