### ISSUE TITLE
"Your photos" still creates ghost images

### ISSUE THREAD

**Issue by wpa1160** [nextcloud/photos#539]
**Describe the bug**

Might be related to closed #404 but still is an issue: When browsing within the "Your photos" section, the browser tab either freezes when going right or generates duplicates of duplicates when going to the left.

See video [screencast.zip](https://github.com/nextcloud/photos/files/5516766/screencast.zip) for reference. "Your albums" works as expected.

**Firefox 82.0.2 console:**

vue.runtime.esm.js:1888:12
TypeError: e is undefined
    VueJS 20
    resetSlideshow Modal.js:67
    next Modal.js:67
    handleKeydown Modal.js:67
    beforeMount Modal.js:67
    VueJS 15
vue.runtime.esm.js:1888:12
    VueJS 12
    resetSlideshow Modal.js:67
    next Modal.js:67
    handleKeydown Modal.js:67
    beforeMount Modal.js:67
    VueJS 15

**Chrome 86.0.4240.183 console:**

vue.runtime.esm.js:1888 TypeError: Cannot read property 'key' of undefined
    at en (vue.runtime.esm.js:5817)
    at vue.runtime.esm.js:6219
    at D (vue.runtime.esm.js:6319)
    at vue.runtime.esm.js:6193
    at D (vue.runtime.esm.js:6319)
    at a.__patch__ (vue.runtime.esm.js:6482)
    at a.e._update (vue.runtime.esm.js:3948)
    at a.n (vue.runtime.esm.js:4066)
    at fr.get (vue.runtime.esm.js:4479)
    at fr.run (vue.runtime.esm.js:4554)
Ge @ vue.runtime.esm.js:1888
Ve @ vue.runtime.esm.js:1879
qe @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1982
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
pr.set @ vue.runtime.esm.js:4631
resetSlideshow @ Modal.js:67
next @ Modal.js:67
handleKeydown @ Modal.js:67

**Comment by skjnldsv** [comment]
Please give us your nextcloud version

**Comment by wpa1160** [comment]
Forgot that initially:

Nextcloud 20.0.1
Photos 1.2.0

**Comment by skjnldsv** [comment]
@Mikescops we fixed it on nc21 only, right?

**Comment by Mikescops** [comment]
Yes!

**Comment by skjnldsv** [comment]
Was the fix for it backportable or too deep integrated into the big grid lib change?

**Comment by Mikescops** [comment]
I think it's related to the grid

**Comment by skjnldsv** [comment]
Then, closing as wontfix unfortunately @wpa1160 
We changed a lot for 21 and we'll keep improving photos as much as we can, sorry for the inconvenience :(
