### ISSUE TITLE
Ability to open originals instead of previews

### ISSUE THREAD

**Issue by ValdasK** [nextcloud/photos#541]
Currently all images are opened as previews, which leads to duplicate storage and/or poor quality photos.

Given that there are configuration options available, it would make sense to add toggle which would change behavior, so when opening a photo user could select if he wants to see preview (for remote or slow connections); or original (in case of high speed networks, such as home usage (where I think NC is most often deployed)).

The only part which I am not exactly sure is should this be enabled by default, or not - would it be possible to make server-wide configurable somehow (for very specific deployments)?

**Comment by skjnldsv** [comment]
Hi, this question was asked before and answered in various areas:
https://github.com/nextcloud/viewer/issues/562
https://github.com/nextcloud/viewer/issues/578

**Comment by zylstra** [comment]
@szaimen and @skjnldsv, why is this issue closed if it has not been fixed?

**Comment by szaimen** [comment]
Because it was decided to not implement this
