### ISSUE TITLE
Add folder for scan pic

### ISSUE THREAD

**Issue by billouetaudrey** [nextcloud/photos#552]
Hi,

I'm sure many people already ask for this, but I don't find myself, or I don't know how to do 👍 

So, anyone can help me to add a folder to scan picture ? My folder is /mnt/webox/Documents/Pic

Thanks :)

**Comment by skjnldsv** [comment]
Hi, I really don't understand what you are trying to do here? :thinking:

**Comment by billouetaudrey** [comment]
> Hi, I really don't understand what you are trying to do here? 🤔

Hi, I want to do same as Google Photos... I have lot of pic on other folder, so is it possible Nextcloud to scan these pic, and display on Photos/Gallerie tab ?

Thanks for reply

**Comment by skjnldsv** [comment]
Hi,
That is a setup issue, nothing to do with this app :)
If you want files to be shown in here, you need to import them in your nextcloud. We can't display files outside of nextcloud.

**Comment by billouetaudrey** [comment]
Ok I see.
My bad
Thanks again ❤️

**Comment by skjnldsv** [comment]
you're welcome! :)
