### ISSUE TITLE
Geotagged images plotted on a map view

### ISSUE THREAD

**Issue by TurkeyMan** [nextcloud/photos#563]
**Describe the solution you'd like**
I am a travelling photographer. I have huge libraries of geotagged images, and it would be spectacular if there were a map view that would plot all the images in a set/album/whatever on a map which you can scroll around, and allow to click on the markers to show the photo, or hover to show a small preview.

Map view is an important way that I locate the particular images I'm searching for from the thousands in the archive without sifting manually.

**Describe alternatives you've considered**
I have experience with other services that have this feature; I'll have to continue using those services for now, even though I use nextcloud for archiving.

**Comment by skjnldsv** [comment]
Hey, that is what the Maps app does, no?

**Comment by TurkeyMan** [comment]
Not really, that's a bloated pig :/
I don't want a single other feature from the Maps app, and I don't want _another_ tab at the top (this is a nextcloud design problem in general).
I just want it associated deeply with Photos somehow, and nothing else.

Ie, in Photos, in the column on the left, I want Map View. I don't want the Maps app in general.
Is it possible for the Maps app to integrate with Photos that way? Can this be a matter of configuration flexibility via Maps?

**Comment by TurkeyMan** [comment]
Perhaps photos can present an API to include a new view in the left-hand column, which Maps can detect and insert an item into?

**Comment by skjnldsv** [comment]
> Not really, that's a bloated pig :/

Not a very positive wording. Please have some considerations for the people that work on this.



> Ie, in Photos, in the column on the left, I want Map View. I don't want the Maps app in general

Sorry, we won't do that in photos.
This is out of the roadmap and we won't spend time implementing a feature that already exists somewhere else :)


> Perhaps photos can present an API to include a new view in the left-hand column, which Maps can detect and insert an item into?

That would be a solution, but require some heavy work which I'm not sure is worth the effort for now.
Cheers!
