### ISSUE TITLE
Can't access to "Photos" 

### ISSUE THREAD

**Issue by kalimbra** [nextcloud/photos#564]
Hello, 

When I try to access "Photos" / "your photos" app I get immediately an error. The only error I see in Web Dev is about the "Dav/" folder. 

Other accesses (albums, shared albums, etc..) seems to work correctly.

Any idea ? 

Screenshot and HAR added.
![Opera Instantané_2020-11-25_090725_cloud kalimbra com](https://user-images.githubusercontent.com/7127212/100199695-daf49e00-2efd-11eb-8d63-0eb479d02ef0.png)
[cloud.kalimbra.com_Archive [20-11-25 09-07-52].har.zip](https://github.com/nextcloud/photos/files/5595212/cloud.kalimbra.com_Archive.20-11-25.09-07-52.har.zip)

**Comment by skjnldsv** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <title>405 Method Not Allowed</title>
  </head>
  <body>
    <h1>Error 405 Method Not Allowed</h1>
    <p>Method Not Allowed</p>
    <hr>
    <p>Varnish L7 server</p>
  </body>
</html>
```

Looks like a server issue to me

**Comment by skjnldsv** [comment]
Make sure your proxy or webserver (or both) allow the SEARCH method
