### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by hahagu** [nextcloud/photos#565]
**Describe the bug**
Going into an album with many different subfolders with pictures, memory of the browser is overloaded by the GET requests returning the error `net::ERR_INSUFFICIENT_RESOURCES`.

**To Reproduce**
1. Go to photos
2. Open a folder with many subfolders each containing photos
3. Wait for thumbnail to load

**Expected behavior**
The thumbnail should load in without problems.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave Browser
 - Version: 1.17.73

**Browser log**
`> GET https://{URL}/index.php/apps/photos/api/v1/albums/{Directory}/{Subdirectory}
net::ERR_INSUFFICIENT_RESOURCES
`

**Additional context**
The photos app should support lazy loading like the file manager, to ease on the concurrent memory usage of the browser instead of trying to load every folder thumbnail at once.

**Comment by skjnldsv** [comment]
Hey! :)
What is your webserver/php memory limit?

**Comment by hahagu** [comment]
> Hey! :)
> What is your webserver/php memory limit?

Thanks for the quick response!
However, I believe that this is a local browser problem.
The memory limit for the webserver is 2gb, which should be enough to handle all the GET requests, and there are no out of memory errors logged on the server side either.
Besides, lazy loading should be introduced, as not only the browser, but also the server in which the instance resides will take a heavy toll when it is receiving so much GET requests, and the maximum connections can be saturated easily.

**Comment by hahagu** [comment]
Also, I'm facing an additional problem where only a few pictures appear on the `Your Photos` section, from a single folder instead of all the folders.
There are no errors logged, and therefore I could not debug where the problem comes from though.

**Comment by skjnldsv** [comment]
Ah, ERR_INSUFFICIENT_RESOURCES is actually coming from the browser indeed.
Nothing to do with the server. Your computer doesn't have enough power to render it all.

We improved and fixed a lot for 21. Unfortunately we were not able to backport this work in the earlier version like 20. :(

**Comment by hahagu** [comment]
> Ah, ERR_INSUFFICIENT_RESOURCES is actually coming from the browser indeed.
> Nothing to do with the server. Your computer doesn't have enough power to render it all.
> 
> We improved and fixed a lot for 21. Unfortunately we were not able to backport this work in the earlier version like 20. :(

Oof..
That's unfortunate..
I hope that this issue is resolved on the next version of nextcloud.

Since this is a personal server, though, is it possible then, to try out version 21?
Version 21 does not seem to be available on the public update channels, and there seems to still be some time left for it to officially release.

**Comment by skjnldsv** [comment]
> Since this is a personal server, though, is it possible then, to try out version 21?
> Version 21 does not seem to be available on the public update channels, and there seems to still be some time left for it to officially release.

No, this is still being developped :)
I have an opened pull request to have this backported to 20 here. If you feel confident, you can download and test it out :)
https://github.com/nextcloud/photos/pull/550

**Comment by hahagu** [comment]
> > Since this is a personal server, though, is it possible then, to try out version 21?
> > Version 21 does not seem to be available on the public update channels, and there seems to still be some time left for it to officially release.
> 
> No, this is still being developped :)
> I have an opened pull request to have this backported to 20 here. If you feel confident, you can download and test it out :)
> #550

I can confirm that lazy loading is implemented on the new build!
Thanks for the help!

However, the issue https://github.com/nextcloud/photos/issues/522 is still not resolved on the new build unfortunately. 😢

**Comment by skjnldsv** [comment]
> However, the issue #522 is still not resolved on the new build unfortunately.

it is still opened, meaning not fixed ;)

**Comment by skjnldsv** [comment]
Thanks for testing it out!!

**Comment by hahagu** [comment]
> Thanks for testing it out!!

The new version looks promising!
Thanks for letting me try out!
