### ISSUE TITLE
Define a default view

### ISSUE THREAD

**Issue by szaimen** [nextcloud/photos#573]
**Is your feature request related to a problem? Please describe.**
As an admin I would like to define a default view for my users.

**Describe the solution you'd like**
Great would be having an admin setting for this app to define a default view for anyone when opening the photos app, so that e.g. `Your folders` can get opened by default.

**Describe alternatives you've considered**
Alternatively, each user should be able to choose a default view by opening the photos settings.
This is how the Tasks app handles a default list for reference:
![image](https://user-images.githubusercontent.com/42591237/100517575-be6d9580-318b-11eb-9d54-8c36ae73d0f5.png)

**Comment by skjnldsv** [comment]
Hey :)

> As an admin I would like to define a default view for my users.

I failed to see why an admin would enforce such thing. For me it would be just as bad as the current state.
Why would the admin choice be more suitable than the current default? :)

**Comment by skjnldsv** [comment]
@jancborchardt what do you think? :)

**Comment by szaimen** [comment]
> Why would the admin choice be more suitable than the current default? :)

Because `Your photos` is always empty for all users on my installation and `Your folders` is not. Hence `Your folders` is the better choice on my instance, imo :)

I just want to show them that there are indeed photos that can be shown when opening the photos app but due to https://github.com/nextcloud/photos/issues/154#issuecomment-592482300 the photos app appears empty when opening the app.
I understand that this was done because of performance issues but `Your folders` works on my instance hence I would like to make it the default.

I hope that makes it a bit clearer :)

**Comment by skjnldsv** [comment]
> Because `Your photos` is always empty for all users on my installation

Isn't that the root issue instead? ^^
Why is this empty? :)

**Comment by skjnldsv** [comment]
Yeah, for me this is not the way to go. We need to promote the Timeline as this is the new feature and was the most requested one. The ext storage issue needs to be fixed instead.

**Comment by szaimen** [comment]
> The ext storage issue needs to be fixed instead.

Well, this is of course a solution but I still think that `Your folders` is better suited for my instance also if the timeline would work because of the raw amount of photos I am storing in Nextcloud (or have connected to Nextcloud). I don't consider the timeline view really useful if I have to scroll very far to view different folders (when they have many pictures inside). The `Your folders` view represents the folder structure better and is thus better understandable for the normal user and faster to navigate, imo. :)

**Comment by szaimen** [comment]
So what do you think @skjnldsv? :)

**Comment by skjnldsv** [comment]
I'm not fond of this.
Otherwise this would apply to all apps. Why not add an option to select the default mail account, or files view, or contacts group, or calendar... etc :)
Adding this will just add one more setting that will most likely barely be used.

**Comment by szaimen** [comment]
> Why not add an option to select the default mail account, or files view, or contacts group, or calendar... etc :)

Actually, most of them makes sense, at least on a user basis, imo :)

Here is e.g. the request for the calendar app: https://github.com/nextcloud/calendar/issues/1835

But let's wait for @jancborchardt what he sais :)

**Comment by skjnldsv** [comment]
I'll post this here :p

![image](https://user-images.githubusercontent.com/14975046/100624330-a16bca80-3323-11eb-87a2-81eb45aed762.png)

**Comment by jancborchardt** [comment]
Sorry for my absence, was out for the last week. :) 

So as @skjnldsv already said, we shouldn’t add a setting for this, especially not for the admin as this is quite irrelevant for admins, and even users shouldn’t need to bother about it.

The solution is quite simple: The app should simply remove the last view you had open. That is, if you were in "Your folders" and close the tab, or go to another app in Nextcloud, the next time you open Photos it should go to "Your folders" again. That way @szaimen in your case the first run is still the intended way (and yes https://github.com/nextcloud/photos/issues/154#issuecomment-601897364 should be fixed instead as the root issue), but going forward, the preferences of people will automatically be picked up.

**Comment by szaimen** [comment]
So then, let's close this in exchange for https://github.com/nextcloud/photos/issues/271?
