### ISSUE TITLE
Miss tabs/register in photo app. Taging not possible

### ISSUE THREAD

**Issue by CoreTechnologyAG** [nextcloud/photos#580]
**only register/tab Chat and sharing available / No register/tab Activity, Comment,..  and no tag function available**
I can't define tags on a photo and there aren't tabs like Activity, Comments Versions. 

**To Reproduce**
1. Drag and drop photos to the photo app
2. Click on photo
3. Click on "Open sidebar"
4. There I see only register/tab: Chat and  sharing and there isn't the circle with the 3 dots for tagging.

**Expected behavior**
something like the printscreen in issue https://github.com/nextcloud/photos/issues/551 from Toucan.jpg but with the additional the Chat register.
![image](https://user-images.githubusercontent.com/11159094/99189258-a3009480-2760-11eb-927a-18e2e321833b.png)

**my Screenshots without Activity, Comments and Versions**
![image](https://user-images.githubusercontent.com/7665561/101357821-42193780-389a-11eb-8a42-faf30cd3a0d3.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Browser [chrome, firefox, edge]
 - Version [in all browser, latest version]

**Browser log**

# Firefox
![image](https://user-images.githubusercontent.com/7665561/101358435-206c8000-389b-11eb-817e-fd0759ee85c5.png)

![image](https://user-images.githubusercontent.com/7665561/101358535-47c34d00-389b-11eb-97b4-4bcf71a5d67c.png)
[testfpm.nextcloud.core.ch-1607348930468.log](https://github.com/nextcloud/photos/files/5653015/testfpm.nextcloud.core.ch-1607348930468.log)

**Comment by skjnldsv** [comment]
Hey!
This is a bigger issue that is slowly being taken care of :)
https://github.com/nextcloud/server/issues/20020
