### ISSUE TITLE
Way to download photo on the fly

### ISSUE THREAD

**Issue by FelixDefrance** [nextcloud/photos#582]
Hi, 

**Two ideas:**

- I would like to have a download icon (arrow) like this on the gallery, to add the possibility to download photo on the fly..
https://www.btactic.com/wp-content/uploads/2018/07/Screenshot_20180709_132545-768x502.png

- Another idea:  it could be cool if it's possible to have something like shopping cart. Your familly/friend could consults photos and add them (on the fly) in cart which is possible to download in the end..

Thx

**Comment by skjnldsv** [comment]
Hey Felix :)

> * I would like to have a download icon (arrow) like this on the gallery, to add the possibility to download photo on the fly..

https://github.com/nextcloud/viewer/issues/88


> * Another idea:  it could be cool if it's possible to have something like shopping cart. Your familly/friend could consults photos and add them (on the fly) in cart which is possible to download in the end..

I think this is out of scope.
Nonetheless I find this similar with the request of creating a selection while browsing with the Viewer.
https://github.com/nextcloud/viewer/issues/324

After starting a selection and adding multiple images to it, the multioptions wuold allow you to download your selection.
