### ISSUE TITLE
Improve timeline view

### ISSUE THREAD

**Issue by darrepac** [nextcloud/photos#586]
Hi,

The new timeline view of latest Beta is very nice and permits to have a similar user experience than Google Photos or others.
Yet there are an issue when scrolling: it takes time to load next photos and it makes it impossible to jump from exemple from now to 5 years ago very quickly as it is possible on google photos and others.
May-be other services are generating a global date index in order to quickly jump at the right place (?)

**Comment by skjnldsv** [comment]
duplicate of https://github.com/nextcloud/photos/issues/426

**Comment by skjnldsv** [comment]
Thanks for testing the beta :)
