### ISSUE TITLE
NC 20.0.3: Scrolling not possible on big screen's

### ISSUE THREAD

**Issue by tacruc** [nextcloud/photos#587]
**Describe the bug**
When loading the photos app 35 pictures are shown. As I have a big screen, they do not fill the screen and no scrollbar is shown. Therefore scrolling down to load more pictures doesn't work. If I resize the browser window until the window is field scrolling down and loading more pictures is working nicely.

**To Reproduce**
1. open Photos app
2. wait
3. wait longer
4. Still only 35 pictures and no way to scroll.

**Expected behavior**
If the app should load pictures until the screen is full.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/402891/101910112-c92e1e80-3bbe-11eb-8b8d-2a0949d28e52.png)

**Desktop (please complete the following information):**
 - OS: OpenSuse
 - Browser Firefox

**Browser log**

Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
![grafik](https://user-images.githubusercontent.com/402891/101910882-df88aa00-3bbf-11eb-9d44-bef6535c5958.png)

**Additional context**

**Comment by skjnldsv** [comment]
cc @Mikescops we don't check for reached end on load I assume?

**Comment by Mikescops** [comment]
@skjnldsv probably yes, also we should load a number of photos that fillls at least twice the height of the view otherwise it doesn't feel smooth at all

**Comment by skjnldsv** [comment]
We load xx lines, no?
I remember we talked about that. Don't recall if we did the change or not

**Comment by Mikescops** [comment]
We load 7 lines (x 5) but it shouldn't be that static

**Comment by Mikescops** [comment]
I'm fixing this in the grid lib

**Comment by Mikescops** [comment]
You can now use https://www.npmjs.com/package/vue-virtual-grid v2.3.0
