### ISSUE TITLE
Show exact date and time of a photo in sidebar

### ISSUE THREAD

**Issue by CWempe** [nextcloud/photos#598]
**Is your feature request related to a problem? Please describe.**
I want to see the exact date and time a photo was take/the file was created.

**Describe the solution you'd like**
I would like to see the timestamp in the sidebar.
![image](https://user-images.githubusercontent.com/1270359/102392172-09ced300-3fd7-11eb-8fd7-4e9c9e8def58.png)

Like this: `11.01.2019 20:38 (2 years ago)`.

**Describe alternatives you've considered**
Alternatively a tool tip when mouse over the approx. date would be fine.

Like here on  Github.
![image](https://user-images.githubusercontent.com/1270359/102392595-924d7380-3fd7-11eb-8415-55496c09d057.png)

**Comment by Pytal** [comment]
nextcloud/nextcloud-vue#1971 and nextcloud/server#27051 merged 🚀
