### ISSUE TITLE
SW registration failed:  TypeError: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by solracsf** [nextcloud/photos#606]
Is this something expected?
I have 2 instances (20.0.4), both are outputting this in the Apache logs (nothing in the Nextcloud log):

`File does not exist: /apps/photos/service-worker.js`

But file do exist, and i can display it's contents when browsing to `https://nextcloud.com/apps/photos/service-worker.js`

On the Browser console (Brave) i get:

```
Photos.vue:114 SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://nextcloud.com/')
with script ('https://nextcloud.com/apps/photos/service-worker.js'):
A bad HTTP response code (404) was received when fetching the script.

(anonymous) @ Photos.vue:114
Promise.catch (async)
(anonymous) @ Photos.vue:113
load (async)
beforeMount @ Photos.vue:108
Ge @ vue.runtime.esm.js:1854
Kt @ vue.runtime.esm.js:4219
e @ vue.runtime.esm.js:4043
bn.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
m @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
An.get @ vue.runtime.esm.js:4479
An @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
bn.$mount @ vue.runtime.esm.js:8415
e._init @ vue.runtime.esm.js:5018
bn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:60
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ photos-main.js?v=7b33d1a2-20:1
```

![image](https://user-images.githubusercontent.com/12234510/108624825-91a5e300-7447-11eb-992f-e23149704fad.png)

**Comment by skjnldsv** [comment]
That is weird, it looks like your setup isn't forwarding js files through index.php.
Can you double check your setup with our docs please?

**Comment by acsfer** [comment]
@skjnldsv installation totally complies with https://docs.nextcloud.com/server/20/admin_manual/installation/source_installation.html and `/settings/admin/overview` says everything is fine too. What else should i check?

**Comment by skjnldsv** [comment]
Everything works for me :thinking: 
What happens if you reach https://cloud.domain.com/apps/photos/service-worker.js ?

**Comment by acsfer** [comment]
Source is displayed, so file exists.

**Comment by skjnldsv** [comment]
Ah! Then it's fine! Indeed, we serve this file dynamically, so apache will fallback to php instead of direct-file serving. If everything works perfectly, then we're good.

**Comment by acsfer** [comment]
O, but even the browser sends a 404 when file is requested directly...but it show it's content. 🤔

**Comment by skjnldsv** [comment]
AH, then it's not good!
Let's debug further. On the photos app, I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the `other` filter. Do your action and screenshot the network log like this:

![image](https://user-images.githubusercontent.com/14975046/102979526-76316100-4506-11eb-99d3-fbdad6d5828a.png)

**Comment by acsfer** [comment]
### Brave
![image](https://user-images.githubusercontent.com/12234510/102979957-1e472a00-4507-11eb-9fe6-1bb07c27bac4.png)

### Firefox
![image](https://user-images.githubusercontent.com/12234510/102980050-3cad2580-4507-11eb-8658-40519663a660.png)

**Comment by acsfer** [comment]
And the console error from Brave:
> A bad HTTP response code (404) was received when fetching the script.
Photos.vue:114 SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('https://cloud.example.com/') with script ('https://cloud.example.com/apps/photos/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.

From Firefox:

> SW registration failed:  TypeError: ServiceWorker script at https://cloud.example.com/apps/photos/service-worker.js for scope https://cloud.example.com/ encountered an error during installation. Photos.vue:114
    beforeMount Photos.vue:114
    (Asynchrone : promise callback)
    beforeMount Photos.vue:113
    (Asynchrone : EventListener.handleEvent)
    beforeMount Photos.vue:108
    VueJS 16
    <anonyme> main.js:60
    Webpack 3

**Comment by skjnldsv** [comment]
Do you use a reverse proxy?

**Comment by acsfer** [comment]
Well, I've tested it with and without on those 2 domains; the first is Apache only (direct) the second is Apache behind Nginx.
Both produce the same error.

**Comment by acsfer** [comment]
On a 3rd with, **Nginx only**, no problem. 🤔

**Comment by acsfer** [comment]
As the script is failing to register a ServiceWorker for scope ('https://cloud.example.com/') with script ('https://cloud.example.com/apps/photos/service-worker.js') shouldn't the scope be ('https://cloud.example.com/apps/photos/') instead of ('https://cloud.example.com/')?

**Comment by skjnldsv** [comment]
No, we changed the scope manually. I works fine on other instances. For me this is definitely an apache issue. But I'(m using the docker apache and everything works fine here.

Are you using https everywhere?

**Comment by acsfer** [comment]
Yes, HTTPS everywhere.

**Comment by Mikescops** [comment]
Hey @acsfer did you solve this issue or not?

**Comment by acsfer** [comment]
@Mikescops nop. Still the same.

**Comment by Mikescops** [comment]
are you hosting nextcloud in a subfolder?

**Comment by acsfer** [comment]
No, not subfolder. And I've tested several hosts with (very) different configurations. All that have Apache involved produced this error. only the one with nginx only haven't.

**Comment by Mikescops** [comment]
Interesting because I personally use Apache and I don't have this issue. Can you list the apache mods that are enabled for you?

**Comment by acsfer** [comment]
```
LoadModule authn_file_module lib  /mod_authn_file.so
LoadModule authn_dbm_module lib  /mod_authn_dbm.so
LoadModule authn_anon_module lib  /mod_authn_anon.so
LoadModule authn_dbd_module lib  /mod_authn_dbd.so
LoadModule authn_socache_module lib  /mod_authn_socache.so
LoadModule authn_core_module lib  /mod_authn_core.so
LoadModule authz_host_module lib  /mod_authz_host.so
LoadModule authz_groupfile_module lib  /mod_authz_groupfile.so
LoadModule authz_user_module lib  /mod_authz_user.so
LoadModule authz_dbm_module lib  /mod_authz_dbm.so
LoadModule authz_owner_module lib  /mod_authz_owner.so
LoadModule authz_dbd_module lib  /mod_authz_dbd.so
LoadModule authz_core_module lib  /mod_authz_core.so
LoadModule authnz_ldap_module lib  /mod_authnz_ldap.so
LoadModule access_compat_module lib  /mod_access_compat.so
LoadModule auth_basic_module lib  /mod_auth_basic.so
LoadModule auth_form_module lib  /mod_auth_form.so
LoadModule auth_digest_module lib  /mod_auth_digest.so
LoadModule allowmethods_module lib  /mod_allowmethods.so
LoadModule file_cache_module lib  /mod_file_cache.so
LoadModule cache_module lib  /mod_cache.so
LoadModule cache_disk_module lib  /mod_cache_disk.so
LoadModule socache_shmcb_module lib  /mod_socache_shmcb.so
LoadModule socache_dbm_module lib  /mod_socache_dbm.so
LoadModule socache_memcache_module lib  /mod_socache_memcache.so
LoadModule dbd_module lib  /mod_dbd.so
LoadModule dumpio_module lib  /mod_dumpio.so
LoadModule buffer_module lib  /mod_buffer.so
LoadModule ratelimit_module lib  /mod_ratelimit.so
LoadModule reqtimeout_module lib  /mod_reqtimeout.so
LoadModule ext_filter_module lib  /mod_ext_filter.so
LoadModule request_module lib  /mod_request.so
LoadModule include_module lib  /mod_include.so
LoadModule filter_module lib  /mod_filter.so
LoadModule substitute_module lib  /mod_substitute.so
LoadModule sed_module lib  /mod_sed.so
LoadModule deflate_module lib  /mod_deflate.so
LoadModule mime_module lib  /mod_mime.so
LoadModule ldap_module lib  /mod_ldap.so
LoadModule log_config_module lib  /mod_log_config.so
LoadModule log_debug_module lib  /mod_log_debug.so
LoadModule logio_module lib  /mod_logio.so
LoadModule env_module lib  /mod_env.so
LoadModule expires_module lib  /mod_expires.so
LoadModule headers_module lib  /mod_headers.so
LoadModule setenvif_module lib  /mod_setenvif.so
LoadModule version_module lib  /mod_version.so
LoadModule remoteip_module lib  /mod_remoteip.so
LoadModule proxy_module lib  /mod_proxy.so
LoadModule proxy_connect_module lib  /mod_proxy_connect.so
LoadModule proxy_ftp_module lib  /mod_proxy_ftp.so
LoadModule proxy_http_module lib  /mod_proxy_http.so
LoadModule proxy_fcgi_module lib  /mod_proxy_fcgi.so
LoadModule proxy_scgi_module lib  /mod_proxy_scgi.so
LoadModule proxy_ajp_module lib  /mod_proxy_ajp.so
LoadModule proxy_balancer_module lib  /mod_proxy_balancer.so
LoadModule proxy_express_module lib  /mod_proxy_express.so
LoadModule session_module lib  /mod_session.so
LoadModule session_cookie_module lib  /mod_session_cookie.so
LoadModule session_dbd_module lib  /mod_session_dbd.so
LoadModule slotmem_shm_module lib  /mod_slotmem_shm.so
LoadModule ssl_module lib  /mod_ssl.so
LoadModule lbmethod_byrequests_module lib  /mod_lbmethod_byrequests.so
LoadModule lbmethod_bytraffic_module lib  /mod_lbmethod_bytraffic.so
LoadModule lbmethod_bybusyness_module lib  /mod_lbmethod_bybusyness.so
LoadModule unixd_module lib  /mod_unixd.so
LoadModule dav_module lib  /mod_dav.so
LoadModule status_module lib  /mod_status.so
LoadModule autoindex_module lib  /mod_autoindex.so
LoadModule info_module lib  /mod_info.so
LoadModule cgid_module lib  /mod_cgid.so
LoadModule dav_fs_module lib  /mod_dav_fs.so
LoadModule vhost_alias_module lib  /mod_vhost_alias.so
LoadModule negotiation_module lib  /mod_negotiation.so
LoadModule dir_module lib  /mod_dir.so
LoadModule actions_module lib  /mod_actions.so
LoadModule speling_module lib  /mod_speling.so
LoadModule userdir_module lib  /mod_userdir.so
LoadModule alias_module lib  /mod_alias.so
LoadModule rewrite_module lib  /mod_rewrite.so
LoadModule suexec_module lib  /mod_suexec.so
```

**Comment by acsfer** [comment]
Updated initial post with browser information.

**Comment by skjnldsv** [comment]
@acsfer are you using self signed certificates?

**Comment by acsfer** [comment]
No, Let's Encrypt.

**Comment by cvakiitho** [comment]
I don't usually like same here, but there's non like that so, same here! :) 

(setup is almost vanilla Nextcloud VM - apache2, latest nextcloud, and Let's Encrypt https)

**Comment by Mikescops** [comment]
@cvakiitho at least add some information about your browser and server configuration that could help a lot defining in what way it's "same here".

**Comment by cvakiitho** [comment]
right sorry, I thought it's more about the backend setup. 

```
SW registration failed:  TypeError: Failed to register a ServiceWorker for scope ('xxx') with script ('xxx/apps/photos/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
(anonymous) @ Photos.vue:114
```

Version 90.0.4430.93 (Official Build) (x86_64) - no extensions 

backend is a nextcloud VM: https://github.com/nextcloud/vm 

with letsencrypt set for a domain - green certificate mark in chrome, redirects 80 to 433, 
geoblock + maps installed I think, nothing fancy.

**Comment by bigcat88** [comment]
I have the same problem. I am not good at web coding, but need to solve that error anyway, so time is come :(
PHP 7.4.3
Nextcloud 21.0.2
Let's Encrypt certificate.
Nextcloud installed in /var/www/nextcloud
Installed from https://github.com/nextcloud/vm
Can see this file in browser. 

In terminal i didn't see that file in `/var/www/nextcloud/apps/photos`
But I see `photos-service-worker.js` in js folder(`/var/www/nextcloud/apps/photos\js`). 
When i use http then error is gone(i dont see that it is loaded at all in http, but maybe i am wrong).

I decided to look, there is a file `photos-0.js` that loaded normal in https.
Here is requests from Safari, maybe someone will understand what is going on:
`URL: https://domain.com/apps/photos/js/photos-0.js?v=c43babe4344139d21e72` 
`Status: 200`
`Source: Network`
`Address: domain.com:443`
`Initiator:` 
`bootstrap:128`

For `service-worker.js`:
`URL: https://domain.com/apps/photos/service-worker.js`
`Status: 404`
`Source: Network`
`Address: domain.com:443`

Do I need to add somewhere `js` in path to this file? Or copy that file one directory above? 
And why I have the same behaviour:
> But the browser sends a 404 when file is requested directly...but it show it's content. 🤔

How is this possible? Any advice will help...

**Comment by Frank1967** [comment]
I have an observation that might be bullshit, or might be useful to somebody. I just do not have the knowledge, but I thought it wise to share this.

I'm using apache24 and never had this error message, but I started to receive the error as soon as I switched (last week) to php-fpm (previously I used mod_php in apache).

**Comment by meichthys** [comment]
I'm also seeing this using the nextcloud VM. @solracsf are you also using the nextcloud vm? Perhaps it's an apache mis-configuration in the VM repo?

**Comment by marcelklehr** [comment]
I've heard before of people having issues with webworkers using the vm

**Comment by solracsf** [comment]
I was not using the VM when reported, but I personally don't have this issue anymore. If this is a config issue, I can't really tell as I'm using a managed service now (Cloudeezy).
