### ISSUE TITLE
Sort photos and videos by name

### ISSUE THREAD

**Issue by DonPicciotto** [nextcloud/photos#615]
Hi, I have some problems using the photos app: a lot of my pictures and videos are recently edited and they appear in the wrong position in the timeline. I use a YYYY-MM-DD format for all my photos and videos, and they would show in the correct position if I could sort them by name. Is there a solution for this problem? It could be really helpful to add an option to custom sort by filename or something else.

**Comment by JuanDelPueblo** [comment]
An option for sorting by name or EXIF date is very much needed considering how Windows changes the date each time you move/rename files. A workaround in the meantime is to utilize an utility like exiftool or exiv2 to set the date modified to the EXIF created date.

**Comment by StarSmasher44** [comment]
Jesus please, who the hell makes an app that reads the last modified values? Copying and transferring is enough to completely fuck up the whole order of things.

Beside the fact that android client's auto upload "Sort in folder by date" is broken to shit as well and 99% of my pictures from 2019 and 2018 are now in a 2021/05 folder..

Honestly my suggestion to you two is to look for an alternative software to manage and take care of photos, Nextcloud may work fine for simply storing them but completely lacks in any other area when it comes to using them. Most of the threads/issues (like this one) remain ignored or get the "Do it yourself" answer.

**Comment by gbshdev-neuban** [comment]
Hey, whats up with sorting Photos by EXIF data ?

**Comment by StarSmasher44** [comment]
Next to impossible, unfortunately.

**Comment by joshtrichards** [comment]
Hi. Take a look at #87 and #397 where progress is being tracked on this situation. To avoid confusion and duplicate work, please close out this Issue.

**Comment by joshtrichards** [comment]
Closing to consolidate into #397
