### ISSUE TITLE
close button is the wrong one

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/photos#63]
18.0.0 beta 3

<img width="833" alt="Screen Shot 2019-12-19 at 13 51 34" src="https://user-images.githubusercontent.com/867445/71175022-c7a96f00-2266-11ea-96ca-71e2adcfdec6.png">

**Comment by karlitschek** [comment]
@rullzer

**Comment by karlitschek** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
It's already fixed, but not released.
This also happens on lower versions with anything using the modal :)
