### ISSUE TITLE
All photos view

### ISSUE THREAD

**Issue by antcer** [nextcloud/photos#632]
HI,

I would like to have a view where both my photos and shared photos are displayed by date. 

Thanks you.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/photos/issues/154
https://github.com/nextcloud/photos/issues/575
https://github.com/nextcloud/photos/issues/291

**Comment by jakobroehrl** [comment]
Shared folders and external storage is working.
Groupfolders: I don't know
