### ISSUE TITLE
File rescan does not update photos

### ISSUE THREAD

**Issue by iamb4lrog** [nextcloud/photos#633]
**Describe the bug**
As the date grouping is based on the file attributes rather that then Exif data, ran a script to modify the file modified & created date to match the data contained in the photo EXIF data. And rescanned the files. This does not changed the stored data in the Photo view.

**To Reproduce**
1. Go to a CLI and change the dates on some photos
2. From the OCC folder run occ files:scan <user name>
3. Once scan is complete return to Photo app.
4. File date is not changed.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by skjnldsv** [comment]
Files:scan checks for new files, but does not update dates/metadata.
Sorry, this is not something that is implemented nor do we have plans for it :(
