### ISSUE TITLE
Video in Slide Show: Play/Fullscreen Buttons overlapped by navigation links

### ISSUE THREAD

**Issue by hul51u** [nextcloud/photos#657]
Hi there,

At some (narrow) browser window scaling in addition to wide-scaled video:
Play/Fullscreen Buttons are overlapped by slide show navigation links.
For example if you try to click the "Play/Pause" button (left bottom) you accidently navigate to the previous image or video.

css classes "preview invisible", "next invisible" "prev" and "next" could be adjusted or replaced for video content.

Nextcloud 20.0.6.1
Photos 1.2.3
Video player 1.9.0
Firefox 85.0.2 (Desktop)
Chrome 88.0 (Desktop)
Chrome 88.0 (Android, Smartphone Portrait Mode)

![nextcloud_navigate_videos](https://user-images.githubusercontent.com/78090961/107623856-44ad5a00-6c5a-11eb-8509-443f75c4ea70.png)

**Comment by skjnldsv** [comment]
Hey! :)
Can you give your resolution please?

**Comment by hul51u** [comment]
Here you are...
Browser screen resolution: 1316x848 (zoom @ 100%)
Video resolution: full hd

However this bug appears at several browser screen widths smaller than video widths.

**Comment by szaimen** [comment]
I think this should be fixed in the meantime. (I've fixed it a while ago.)
