### ISSUE TITLE
Short documentation for setting up debugging javascript

### ISSUE THREAD

**Issue by dsmic** [nextcloud/photos#658]
Would be nice, if you could document how to debug javascript. 

In the original setup one can only debug in the preprocessed javascipt files (which makes it nearly impossible to understand where the source code is from).

**Comment by skjnldsv** [comment]
> In the original setup one can only debug in the preprocessed javascipt files (which makes it nearly impossible to understand where the source code is from).

We ship map files, if your server is properly configured, your browser will get them and map it to the source files.

If you want to build the app yourself https://github.com/nextcloud/photos#-development-setup
