### ISSUE TITLE
Timeline By Date Taken

### ISSUE THREAD

**Issue by GaryParr** [nextcloud/photos#662]
**Is your feature request related to a problem? Please describe.**
I had to copy all my data over from an old NAS that was failing. Of course, I didn't realize Photos did not utilize picture metadata so I wasn't worried about changing file timestamp. Now, 10 years of pictures are all shown as being taken on the same day.

**Describe the solution you'd like**
Would really appreciate it if Photos could read the metadata and show the timeline based on when a picture was actually taken rather than when the file was touched. Related to that, showing the metadata in the sidebar would be good too.

**Describe alternatives you've considered**
I've considered deleting all 10 years of pictures and moving them over in a way that doesn't touch the time stamp... but honestly, I can't be sure they have the correct time stamps in the original NAS source either.

**Additional context**
I could be wrong, but to my knowledge every other photo management solution uses photo metadata for date, location, etc.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/issues/87
