### ISSUE TITLE
Images intermittently not loading

### ISSUE THREAD

**Issue by Exist2Resist** [nextcloud/photos#663]
### Steps to reproduce
1. Login to nextcloud
2. Navigate to photos 
3. Photos loader spins and doesn't load photos. 
4. Hit F12 to bring up Developer console
5. Hit F5 to reload page with developer console open, poctures load. 
6. Close developer console hit F5, pictures do not load. 
7. Close developer console and close tab. 
8. Keep browser open. 
9. Open nextcloud in a new tab 20 min later
10. Open photos
11. Photos load without the developer console open. 

I believe it has something to do with this:
```
Uncaught (in promise) TypeError: t.gridConfig is undefined
    e Timeline.vue:228
    u runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    T photos-5.js:65
    a photos-5.js:65
    _ photos-5.js:65
    _ photos-5.js:65
    getContent Timeline.vue:209
    beforeMount Timeline.vue:193
    VueJS 18
Timeline.vue:228
    T photos-5.js:65
    a photos-5.js:65
    _ photos-5.js:65
    _ photos-5.js:65
    getContent Timeline.vue:209
    getContent self-hosted:844
    beforeMount Timeline.vue:193
    VueJS 18

```

When the images load successfully that exception is not present in the browser console output.

### Expected behaviour
Photos should load instantly.

### Actual behaviour
Loader spinner keeps spinning. 

### Server configuration

**Operating system:**
unraid/docker

**Web server:**
nginx 1.18.0

**Database:**
mariadb 10.4

**PHP version:**
7.4.15

**Nextcloud version:** (see Nextcloud admin page)
v20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update and Fresh install been testing this for over a week now. 

**Where did you install Nextcloud from:**
linuxserver.io docker repo

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.8.1
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - richdocuments
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "loglevel": 0,
        "overwriteprotocol": "https",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.151:448",
            "cloud.nerdlord.duckdns.org"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "https:\/\/192.168.1.151:448",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** n/a

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
n/a
```
</details>

### Client configuration
**Browser:**
Vivaldi, Firefox, Edge

**Operating system:**
Windows 10 20H2

#### Web server error log
<details>
<summary>Web server error log</summary>

see web server error log
```
https://cloud.nerdlord.duckdns.org/s/HRK3L3RCE8kcfq6
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

see nextcloud log
```
https://cloud.nerdlord.duckdns.org/s/HRK3L3RCE8kcfq6
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

See HAR file and console export
```
https://cloud.nerdlord.duckdns.org/s/HRK3L3RCE8kcfq6
```
</details>

**Comment by skjnldsv** [comment]
What nextcloud version are you using? You put 20, but is it latest 20?

**Comment by Exist2Resist** [comment]
Oh sorry updated it, it's 20.0.7

**Comment by Exist2Resist** [comment]
> cc @skjnldsv photos or server? 🤔

It's just the photos tab/page on the server. I can manually navigate to the folder and open them.

**Comment by Exist2Resist** [comment]
Like I said this issue is intermittent. 
Another weird thing about the photos tab/app in Nextcloud 20, when the pictures do load certain files are not showing up in the "Your Folders" view. But you can see them in the "Your Photos" view. In this case it's all photos from November 2020. 
I have them all in subfolders.

Your Folders view
![Screenshot 2021-02-18 195228](https://user-images.githubusercontent.com/8682792/108451385-f8e34d80-7223-11eb-958a-fbe25af58401.png)
![Screenshot 2021-02-18 195411](https://user-images.githubusercontent.com/8682792/108451392-fe409800-7223-11eb-8d5b-5548fd3f9b4e.png)

Your Photos view
![Screenshot 2021-02-18 195331](https://user-images.githubusercontent.com/8682792/108451576-4bbd0500-7224-11eb-955f-334c67ccde57.png)

Files
![Screenshot 2021-02-18 195552](https://user-images.githubusercontent.com/8682792/108451590-51b2e600-7224-11eb-9a9a-1434194ab59d.png)

**Comment by skjnldsv** [comment]
When it fails, can you share the browser logs?

Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Exist2Resist** [comment]
There are two console export files in that share I posted earlier. 

https://cloud.nerdlord.duckdns.org/s/HRK3L3RCE8kcfq6

**Comment by andrzej-r** [comment]
Not sure if this is the same issue but I get a lot of problems with images not loading in Firefox. This does not happen, or at least I haven't noticed it, in Chromium.

This looks like a caching problem because these "missing" images were loaded earlier and the web server doesn't report any new requests for them. Typically it happens if I scroll up the page with photo images.

**Comment by Exist2Resist** [comment]
Yes I have this as an intermittent problem. Happens sometimes but not other times.

**Comment by skjnldsv** [comment]
Should be fixed by https://github.com/nextcloud/photos/pull/686

**Comment by andrzej-r** [comment]
I've noticed issues with *some* images not loading also in small browser windows.

**Comment by Exist2Resist** [comment]
This is an issue with browser window size. 
3860 x 1600 will not load any images, but if I rescale my window to 1930 x 1600 (half screen) they load fine.
