### ISSUE TITLE
Timeline for selecting a year/month/day in the sorted by date view

### ISSUE THREAD

**Issue by andrzej-r** [nextcloud/photos#687]
**Is your feature request related to a problem? Please describe.**
Currently photos/videos are sorted by the file creation date and when the issue #397 is sorted that will become sort by date the photo was taken (can't wait for fixing that, btw, currently my photos are all mixed up because they were copied as files).

However, that's only a part of the solution. With many photos in the library, scrolling down the list to a desired year/month/day takes a lot of time, especially that the scrolling in Nextcloud Photos is very slow.

**Describe the solution you'd like**
I'd like some sort of a "timeline widget" with years/months/days marked. Ideally it would indicate the number of photos in that period or show the first photo of that period.

**Describe alternatives you've considered**
A simple date selection or a text field for jumping to a requested date would work fine as well, although it wouldn't be as attractive visually.

**Additional context**
none

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/issues/426
