### ISSUE TITLE
Photos stored on an 'External Storage' won't appear in 'Your Photos' for Photos 1.3.0 and nextcloud 21

### ISSUE THREAD

**Issue by pricopvalentin** [nextcloud/photos#695]
**Describe the bug**
(New) Photos stored on an 'External Storage' won't appear in 'Your Photos' for Photos 1.3.0 with nextcloud 21.0.0.18
The issue does not appear with Photos 1.2.0 and nextcloud 20.0.1.1

**To Reproduce**
1. Place a photo in an external storage folder (see 2021-03-02_233815.jpg in Nerd folder in screenshot 1)
2. Click on 'Photos' and observe the missing photo in the 'Your photos' section (screenshot 2)
3. Move the photo to another folder that is not external storage (see screenshot 3)
4. Click on 'Photos' and observe that the photo is no longer missing in the 'Your photos' section (screenshot 4)

**Expected behavior**
I was expecting to find a list of the most recently added photos to my folders in the 'Your photos' section of Photos.
This behaviour is as expected if photos are uploaded to a folder which is not configured as external storage.
If photos are uploaded to external storage folders, then no photos appear in the 'Your photos' section.
The bug reproduces on the Android client of nextcloud as well.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/79946767/109729294-ee2b9f80-7bb7-11eb-8fe1-e94e5f7aa483.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/79946767/109729552-524e6380-7bb8-11eb-9d48-52421f29e8ed.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/79946767/109729780-b2dda080-7bb8-11eb-94a7-319373f162ef.png)

Screenshot 4:
![image](https://user-images.githubusercontent.com/79946767/109729864-d43e8c80-7bb8-11eb-82fd-e0f4d512d114.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Browser log**
**Chrome console capture when the photo is stored on a non-external storage folder and the bug is not manifesting:**
index.js:46 No OC found
t.getLanguage @ index.js:46
value @ gettext.js:45
(anonymous) @ l10n.js:3
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=0460d9c0-5:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
701 @ files_client.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
701 @ files_client.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:121
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:125
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:125
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
(anonymous) @ jquery.js:14
n @ bootstrap:19
(anonymous) @ sidebar.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ sidebar.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
(anonymous) @ jquery.js:14
n @ bootstrap:19
(anonymous) @ sidebar.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ sidebar.js?v=0460d9c0-5:1
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
pe @ globals.js:60
get @ globals.js:91
478 @ templates.js:2
t @ bootstrap:19
476 @ comments.js:1
t @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ comments.js?v=0460d9c0-5:1
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
pe @ globals.js:60
get @ globals.js:91
t.default @ no-conflict.js:8
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ item.handlebars:1
n @ bootstrap:19
(anonymous) @ files_versions.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=0460d9c0-5:1
versionstabview.js:18 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (versionstabview.js:18)
    at n (bootstrap:19)
    at bootstrap:83
    at files_versions.js?v=0460d9c0-5:1
(anonymous) @ versionstabview.js:18
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ ua-parser.js:912
(anonymous) @ ua-parser.js:10
n @ bootstrap:19
(anonymous) @ browserCheck.js:24
n @ bootstrap:19
(anonymous) @ CallButton.vue:53
n @ bootstrap:19
(anonymous) @ CallButton.vue?aafb:1
n @ bootstrap:19
(anonymous) @ CallButton.vue:1
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue:67
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue?6529:1
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue:1
n @ bootstrap:19
(anonymous) @ mainFilesSidebar.js:27
n @ bootstrap:19
(anonymous) @ talk-files-sidebar.js?v=0460d9c0-5:2576
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ talk-files-sidebar.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ script.js?v=0460d9c0-5:492
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ files.js?v=0460d9c0-5:122
session-heartbeat.js:97 session heartbeat polling started
Viewer.vue:235 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:235
fn.run @ vue.runtime.esm.js:4568
ln @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fn.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:81
(anonymous) @ main.js:26

**Chrome console capture when the photo is stored on an external storage folder and the bug is manifesting:**
index.js:46 No OC found
t.getLanguage @ index.js:46
value @ gettext.js:45
(anonymous) @ l10n.js:3
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=0460d9c0-5:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
701 @ files_client.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
701 @ files_client.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:121
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:125
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
mounted @ App.vue:125
zt @ vue.runtime.esm.js:1854
Ke @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
L @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
Mn.$mount @ vue.runtime.esm.js:8415
t._init @ vue.runtime.esm.js:5018
Mn @ vue.runtime.esm.js:5085
(anonymous) @ main.js:32
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications-main.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
(anonymous) @ jquery.js:14
n @ bootstrap:19
(anonymous) @ sidebar.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ sidebar.js?v=0460d9c0-5:1
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
(anonymous) @ jquery.js:14
n @ bootstrap:19
(anonymous) @ sidebar.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ sidebar.js?v=0460d9c0-5:1
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
pe @ globals.js:60
get @ globals.js:91
478 @ templates.js:2
t @ bootstrap:19
476 @ comments.js:1
t @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ comments.js?v=0460d9c0-5:1
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
pe @ globals.js:60
get @ globals.js:91
t.default @ no-conflict.js:8
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ item.handlebars:1
n @ bootstrap:19
(anonymous) @ files_versions.js?v=0460d9c0-5:1
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=0460d9c0-5:1
versionstabview.js:18 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (versionstabview.js:18)
    at n (bootstrap:19)
    at bootstrap:83
    at files_versions.js?v=0460d9c0-5:1
(anonymous) @ versionstabview.js:18
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ ua-parser.js:912
(anonymous) @ ua-parser.js:10
n @ bootstrap:19
(anonymous) @ browserCheck.js:24
n @ bootstrap:19
(anonymous) @ CallButton.vue:53
n @ bootstrap:19
(anonymous) @ CallButton.vue?aafb:1
n @ bootstrap:19
(anonymous) @ CallButton.vue:1
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue:67
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue?6529:1
n @ bootstrap:19
(anonymous) @ FilesSidebarTabApp.vue:1
n @ bootstrap:19
(anonymous) @ mainFilesSidebar.js:27
n @ bootstrap:19
(anonymous) @ talk-files-sidebar.js?v=0460d9c0-5:2576
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ talk-files-sidebar.js?v=0460d9c0-5:1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ script.js?v=0460d9c0-5:492
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
get @ globals.js:91
(anonymous) @ files.js?v=0460d9c0-5:122
session-heartbeat.js:97 session heartbeat polling started
Viewer.vue:235 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:235
fn.run @ vue.runtime.esm.js:4568
ln @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Ke @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fn.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:81
(anonymous) @ main.js:26

**Additional context**
NA.

**Comment by skjnldsv** [comment]
Duplicate, please search before posting :)
Cheers!

**Comment by pricopvalentin** [comment]
Can you please let me know what is the post where this bug is being discussed?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+external
