### ISSUE TITLE
Performance steps

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#7]
- [x] Virtual scroller for the grid
- [x] Paginate timelines (show first 100? cc @jancborchardt )
- [ ] Because of the power of 4, the images preview are loaded with 1024px min, otherwise it's 256 which is visibly pixelated. cc @rullzer

**Comment by MichaIng** [comment]
The image grid, when accessing Photos app, does not use `1024px` previews, does it? From shown size it could be a 256x256 square. Could you verify which preview sizes are required, so PreviewGenerator can be configured accordingly.

Accessing the app seems to generate all images previews, while it would make sense to only generate those which are visible on screen, probably half a page more?

**Comment by skjnldsv** [comment]
I changed it to 256 last week, we'll see how it goes later on :)

**Comment by jancborchardt** [comment]
> Paginate timelines (show first 100? cc @jancborchardt )

Yeah, show a reasonable amount initially, 100 seems good. And then always preload enough so that when people scroll it never looks like it needs to load, but they are already there.

**Comment by MichaIng** [comment]
Would it be too much overhead to check grid size on client and e.g. preload e.g. two "pages" instead of a hardcoded 100 images? 100 might be fine on some clients/screen sizes but too much or too low on others.

**Comment by skjnldsv** [comment]
I'll do it slightly differently. But definitely load 100 at once, this is too much
