### ISSUE TITLE
Photos get duplicate when going from "Your albums" to "Your photos"

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/photos#70]
All photos get duplicate when going from "your albums" to "your photos" tabs.

Initial situation:
![image](https://user-images.githubusercontent.com/4266283/71469822-9f6fc200-27ca-11ea-9d5d-29585f481257.png)

Then after going to your albums and then go back to your photos:
![image](https://user-images.githubusercontent.com/4266283/71469869-c4fccb80-27ca-11ea-8f0d-d509043c41ad.png)

Another iteration:
![image](https://user-images.githubusercontent.com/4266283/71469898-d47c1480-27ca-11ea-90af-c2d367604e0c.png)

**Comment by skjnldsv** [comment]
Btw @Mikescops you can join and ask questions on the public channel here: https://cloud.nextcloud.com/call/m7tc7ndi :)
