### ISSUE TITLE
l10n: Month names

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/photos#708]
In the gallery, the names of the months above the photos are in English only.

![obraz](https://user-images.githubusercontent.com/47037905/111478940-d06e4680-8730-11eb-90ea-8a94b6b8cd3c.png)

App:
Photos  1.2.3
Nextcloud 20.0.8

**Comment by skjnldsv** [comment]
Hi, what is your locale setting?

**Comment by Valdnet** [comment]
@skjnldsv My region and language is set to Polish 😉.

![obraz](https://user-images.githubusercontent.com/47037905/111524348-99ae2580-875c-11eb-99f6-323ef0f7cfdc.png)

**Comment by Valdnet** [comment]
The problem may be related to: https://github.com/nextcloud/server/issues/24143.

**Comment by skjnldsv** [comment]
No, this is from here: https://github.com/nextcloud/photos/blob/ef6530fa639db12e0d524e6dc50fc374f0a0bace/src/views/Timeline.vue#L289

We don't load the proper locale, this is a mistake :)

**Comment by Valdnet** [comment]
> We don't load the proper locale, this is a mistake :)

Thanks for the information. So we are waiting for a fix 😉.
