### ISSUE TITLE
Rows make photos disappear when resizing window

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/photos#73]
I'd like to challenge the use of rows in the grid. 

### Issue

The current way splits array of photos into multiple chunks of 5 photos. This leads to mistakes when the view/grid gets resized and can't display this amount of photos.

For instance here is a demo:
![image](https://user-images.githubusercontent.com/4266283/71478640-fdaf9b80-27f0-11ea-8e27-569e3077241f.png)

8 photos are currently displayed here.
And then when we resize:
![image](https://user-images.githubusercontent.com/4266283/71478670-1c159700-27f1-11ea-9b21-a8eb1404370b.png)

6 photos being displayed on mobile view.

### Why current use of rows breaks in the future:

It would be great to have photos appearing without thumbnailing, in their original ratio aspect. That means the row will have a variable number of photos in it.

Also, if you take an upcoming feature to split by date the grid, this will endup in lot of Array slicing operations that shoud be handled by css styling.

**Comment by skjnldsv** [comment]
> if you take an upcoming feature to split by date the grid

#45 



> It would be great to have photos appearing without thumbnailing, in their original ratio aspect. That means the row will have a variable number of photos in it.

That is a future discussion, but this has been proposed here: https://github.com/nextcloud/gallery/issues/550

**Comment by Mikescops** [comment]
Ok great discussion, I'm totally in for this feature, having this square grid is really old school.
Maybe we can start discussing what kind of grid we want and the technical needs it implies :smile: 

My suggestion: it would be easier to load a given number of images (let's say 25 for instance) and start lazy loading when the browser is one or two rows close to the end of the page. 
If a row is not filled entirely and we know there are still image to load we can display a grey animated box until the loading succeed.

**Comment by skjnldsv** [comment]
> it would be easier to load a given number of images (let's say 25 for instance) and start lazy loading when the browser is one or two rows close to the end of the page.

this is what we currently do :)
We load 10 rows (depending on the browser's width) adn then we prefetch the next set when close to the bottom

**Comment by Mikescops** [comment]
What is this then?
```
/**
 * Split an array into chunks
 *
 * @param {Array} arr an array to split
 * @param {number} count lenght of the chunk
 * @returns {Array}
 */
export default function(arr = [], count = 5) {
	return arrayRange(Math.ceil(arr.length / count)).map((x, i) =>
		arr.slice(i * count, i * count + count)
	)
}
```

**Comment by skjnldsv** [comment]
An old remnant of previous code :see_no_evil: 
https://github.com/nextcloud/photos/blob/42c89a1c886b0fe8ef797600b1556d998c1c1c2f/src/views/Timeline.vue#L106
We don't use the chunked list anymore

**Comment by Mikescops** [comment]
Oh wrongly read the code then! My bad
