### ISSUE TITLE
Opening the tag view not possible 

### ISSUE THREAD

**Issue by selaviee** [nextcloud/photos#744]
**Describe the bug**
When opening the tag view it displays "an error occured".

**To Reproduce**
1. Go to 'Photos with Tags': "An error occured"

**Expected behavior**
Choose from colloborative tags and show selected tagged photos

**Desktop/Smarphones:**
 - Windows and Android
 - Firefox, Chrome
 - latest Versions
 - NC 21.0.1

**Browser log**
TypeError: r.localeCompare is not a function
Tags.vue:233

**Comment by maretodoric** [comment]
Hello.
I have Nextcloud 20.0.10, Photos app version is 1.2.3.
When i try to view photos with tags, i don't get "An error occurred" message. I get:
```
No tags yet
Photos with tags will show up here
```

Tried on desktop on firefox and google chrome, items are tagged automatically using flows.

**Comment by selaviee** [comment]
It works with this Versions fine:

Nextcloud 22.2
Photos 1.4

**Comment by maretodoric** [comment]
This still doesn't work in my case. Nextcloud just upgraded to 22.2 and Photos to 1.4.0
When i go to Photos and select a tag, it still says:

```
No tags yet
Photos with tags will show up here
```
