### ISSUE TITLE
Not taking into account the .noimage flag

### ISSUE THREAD

**Issue by tillwf** [nextcloud/photos#75]
Folders with the file `.noimage` are still viewable.

**Comment by Mikescops** [comment]
Exact, I could reproduce that one too.

**Comment by skjnldsv** [comment]
Ah right! :)
@rullzer can we exclude this from the albums?

**Comment by rullzer** [comment]
Sure.

**Comment by PriceChild** [comment]
[There's precedent for looking for two files](https://github.com/nextcloud/gallery):
Ignore folders containing a ".nomedia" or ".noimage" file

**Comment by cly0514** [comment]
please recognize .nomedia folder and exclude it thank you

**Comment by archont00** [comment]
Yep. I have a music folder with really a lot of sub-folders, many having an Album Cover image. Showing these images in Photos not a way to go.

**Comment by slgray** [comment]
My Nextcloud Server version is 18.0.1 and the Photos App version is 1.0.0, the problem still exist. Do I need to upgrade the Photos App?

**Comment by skjnldsv** [comment]
@slgray which view are we talking about here?

**Comment by slgray** [comment]
> @slgray which view are we talking about here?

Hi @skjnldsv, it is `Your photos`
![2020-03-05_22-18](https://user-images.githubusercontent.com/1411489/75990219-88b6bb80-5f2f-11ea-9be7-d3bde1ea8539.png)

**Comment by skjnldsv** [comment]
Ah, it is not taken into account there though :thinking: 
Though I guess can be fixed with #141

**Comment by slgray** [comment]
Got it, thanks.

**Comment by n1try** [comment]
I'm running Nextcloud 18.0.1 with Photos 1.0.0, but the bug still occurs. Can somebody help me getting this fixed through an update or so?

**Comment by lbdroid** [comment]
> Ah, it is not taken into account there though 
> Though I guess can be fixed with #141

That wouldn't fix it, that would only obscure it. It should still be possible to add a .nomedia file into some subdirectory of the designated "photos" tree, for instance, to block off a thumbnails directory.

**Comment by skjnldsv** [comment]
-> https://github.com/nextcloud/photos/issues/234

**Comment by steve4835** [comment]
Any update on this?  It is still an issue in Nextcloud 22

**Comment by marcelklehr** [comment]
@steve4835 This is fixed in Nextcloud 24

**Comment by gorrunyo** [comment]
I'm using 24.0.6_15.3.35 and both `.noimage` and `.nomedia` placed in external storage are ignored when running

`occ maps:scan-photos <user_name>`

**Comment by marcelklehr** [comment]
Hi @q2apro 
this issue was closed 4 years ago, it's likely this is a regression. As such, please open a new issue.
