### ISSUE TITLE
Photo app is triggering fail2ban 

### ISSUE THREAD

**Issue by muranava** [nextcloud/photos#766]
**Describe the bug**
When app is trying to list my photos it seems to trigger my fail2ban?
**To Reproduce**
1. Go to 'photo'
2. wait for photos to load
3. keeps loading
4. triggers fail2ban when trying to navigate to another tab in Nextcloud

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 10.11.6
 - Browser Firefox
 -  Version 78.10.1esr 

**Smartphone (please complete the following information):**

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
