### ISSUE TITLE
Back to previous album can end up in an empty folder

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/photos#79]
Related to #74, when you go in Albums list you see children albums "in depth" and any intermediate folder not containing photos is skipped. 
But if you click on a level 2 children for instance "Documents/somephotos" and click to go back you get to "Documents" and not the root album.

The navigation for the end user is not the same then.

**Comment by jancborchardt** [comment]
Yep, @skjnldsv and I were discussing that. Going "Back to" via the back arrow should always go back to the view you were before, not the parent folder. :)

**Comment by Mikescops** [comment]
Great I think we can use history npm package to achieve this by keeping the previous state in memory

**Comment by skjnldsv** [comment]
@Mikescops maybe vue router already have this :)

**Comment by Mikescops** [comment]
Oh i'm not aware, i never used vue, just a bit of react at work

**Comment by Mikescops** [comment]
As I see now, intermediate folders not containing pictures are not skipped.

@skjnldsv I guess we can close this issue if you agree.

**Comment by skjnldsv** [comment]
Of course!
