### ISSUE TITLE
Maps navigation entry

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#8]
Add link to maps if installed or the maps in the store if not installed

**Comment by jakobroehrl** [comment]
There is already a link called Locations, is this the right one?
How can I find out, If an app is installed or not?

**Comment by skjnldsv** [comment]
Yes this is the one :)
I think you will have to add the check in phph and send the ingo to the front by using the initialstate api

There is already one example of it in the app, you could create a second data set for the map?

**Comment by jakobroehrl** [comment]
> ... send the ingo to the front by using the initialstate api

What do you mean by that?

> There is already one example of it in the app, you could create a second data set for the map?

Could't find it. Would you give me a hint? 😬

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/blob/893b8974a091af019681cd7669133287edac5655/lib/Controller/PageController.php#L70
https://github.com/nextcloud/photos/blob/893b8974a091af019681cd7669133287edac5655/src/services/AllowedMimes.js#L25
