### ISSUE TITLE
Shared albums are not sorted

### ISSUE THREAD

**Issue by tillwf** [nextcloud/photos#81]
![2019-12-27_15-34](https://user-images.githubusercontent.com/7115035/71520899-6876da80-28b6-11ea-8ad9-4a56572c1954.png)

These albums are in the same folder.

**Comment by skjnldsv** [comment]
They should be sorted by last modified :)
Could you check?

**Comment by tillwf** [comment]
```
déc.  18 15:38 2019-12-17 [Leila]/
déc.  20 13:47 2019-12-18 [Leila]/
déc.  20 13:48 2019-12-19 [Leila]/
```
It does not seem to be that.

**Comment by tillwf** [comment]
For the pictures inside folders it is indeed the modification time. Is it the behavior wanted ?

**Comment by skjnldsv** [comment]
Yes this is :)

**Comment by tillwf** [comment]
@skjnldsv Why did you close this issue ? I was saying that you were right for pictures, but for the folder it does not seem to be the modification time.

**Comment by skjnldsv** [comment]
Ah, sorry, I understood that you were saying that it was indeed the pictures within the folder that was taken into account.

Please double check that it is not the case?

**Comment by skjnldsv** [comment]
> Please double check that it is not the case?

Any news?

**Comment by joshtrichards** [comment]
Closing due to no followup >4 years.
