### ISSUE TITLE
Failed dynamic import of 'empty' image

### ISSUE THREAD

**Issue by ramezrafla** [nextcloud/photos#840]
**Describe the bug**
When no images are stored in NC, an error is triggered in the console about missing empty image

**To Reproduce**
1. Start with clean install with no images
2. Go to photos app
3. Look at the console.log ```EmptyContent.vue:105 Could not get the error illustration Error: Cannot find module '../assets/Illustrations/empty.svg'
    at e (components|sync:2)
    at EmptyContent.vue:102
    at async o.getIllustration (EmptyContent.vue:102)```

**Problem**
Webpack needs to know at compile time what to import and build. Line 102 in EmptyContent.vue can't work work:
```const illustration = await import(`../assets/Illustrations/${this.illustrationName}.svg`)```

**Solutions**
1. What's the point of having dynamic image `this.illustrationName` -- just use `empty.svg` -- the line should read:
```const illustration = await import(`../assets/Illustrations/empty.svg`)```
2. Use DOM `<img>` and let the browser handle it

**Comment by Pytal** [comment]
Resolved by #842

**Comment by Pytal** [comment]
Resolved by #842
