### ISSUE TITLE
Add timescale for navigation

### ISSUE THREAD

**Issue by Ilia1** [nextcloud/photos#848]
When there are many photos taken at different times and not sorted into folders, it is difficult to find old photos.

The decision to make the timeline as in Yandex.Disk or Plex.
![timescale-yd](https://user-images.githubusercontent.com/16576224/128857898-243add0c-7d8b-450e-9f55-0ccffecac87d.png)

**Comment by skjnldsv** [comment]
Hey! Duplicate of https://github.com/nextcloud/photos/issues/426
