### ISSUE TITLE
No thumbnail of video files

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/photos#854]
**Describe the bug**
Video thumbnails (mp4) are not displayed when viewing photos or videos.

**Expected behavior**
Display the standard thumbnail of video files (mp4) or the thumbnail of the video file frame.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47037905/130266988-bb96c304-6f56-477b-a7c6-1cf2e04b512c.png)

Apps:
Nextcloud 22.1.0
Photos 1.4.0
Firefox 91.0.1

**Comment by skjnldsv** [comment]
> I suspect it might not be possible to put a variable name when importing like this, but not sure.

Yes it is, webpack understands it and split chunks accordingly

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/photos/pull/842

**Comment by skjnldsv** [comment]
Completely forgot about this, I forgot to backport.

**Comment by PVince81** [comment]
the backport was done here: https://github.com/nextcloud/photos/pull/876
