### ISSUE TITLE
🖼️ Sorting pictures by taken date instead of modification date

### ISSUE THREAD

**Issue by tillwf** [nextcloud/photos#87]
For travel albums or for any event, pictures modification time does not reflect the event timeline.

It happens a lot that pictures are modify (cropping, enhancements, etc.), and changing their orders does not help readability.

Could the creation date be the default info used ?

**Comment by skjnldsv** [comment]
It would be a nice enhancement.
But we do not store the taken date for now.

cc @rullzer

**Comment by skjnldsv** [comment]
cc @jancborchardt if it make sense

**Comment by jancborchardt** [comment]
Yep, very good point – for photos it absolutely makes sense to sort by taken date, exactly for the reasons @tillwf mentioned. :)

**Comment by tillwf** [comment]
Could it simply be sorted by the name as a start ? With current cameras naming convention, the filename reflects the creation date order.

**Comment by skjnldsv** [comment]
I'd rather have modification date (like all mobile galleries work) than name

**Comment by jancborchardt** [comment]
> Could it simply be sorted by the name as a start ? With current cameras naming convention, the filename reflects the creation date order.

This would break down as soon as you get photos from a second camera or from friends, or the numbering of your own camera wraps – so the current way is better for now. :)

**Comment by tillwf** [comment]
@jancborchardt You're right. However, it is not better now, because currently the order is completely random as I transfer my picture using `scp`. That is why I was saying "as a start". I prefer to have 2 sets of photos ordered than nothing coherent.

**Comment by frieck** [comment]
Guys, can't we just change this line https://github.com/nextcloud/photos/blob/c993c63a32ad3283c49852cccc249ad0d228a057/lib/Controller/AlbumsController.php#L102
to use `$node->getCreationTime()`?
That makes picture be displayed in a more logical order....

**Comment by skjnldsv** [comment]
@frieck this suggest is about the taken date, not the creation date of the file.
So we'd need exif support

**Comment by frieck** [comment]
Hi @skjnldsv, 
For me all photos are being displayed in an incorrect order as they all have been modified sometime. 
So changing that line that I mentioned helped me to fix part of the problem, I understand that a File can have a creation date different from the photo that it represents, but that seems to be more uncommon than having a modification date and everything listed by that modification date.

**Comment by skjnldsv** [comment]
@frieck not arguing with your specific issue :)
It fits some people uses, but also not for others. Just reminding that this issue is about the photo taken date, not creation date.

> Could the creation date be the default info used ?

Nonetheless, I just notice this line on the main post, which make this confusing :stuck_out_tongue: 
@jancborchardt shall we use creation date by default instead of last modified?

**Comment by jancborchardt** [comment]
> @jancborchardt shall we use creation date by default instead of last modified?

Yep! :)

**Comment by da-anda** [comment]
creation date of the file is better than the mtime, but EXIF data would ofc be best. Unfortunately, creation date (filesystem level) is also of no use if you use the NC app to sync your pictures from the phone, since all files end up with a creation date of the time of the upload :(

**Comment by jancborchardt** [comment]
@skjnldsv considering the amount of discussion and also the pitfalls you mentioned in your comments, this does not seem like a good first issue?

**Comment by skjnldsv** [comment]
> @skjnldsv considering the amount of discussion and also the pitfalls you mentioned in your comments, this does not seem like a good first issue?

You mentioned created date, which we have. For exif taken date of course this is not a good first issue. :)
There is another issue laying around somewhere that is also similar iirc

**Comment by jcclerval** [comment]
Hi,
I would also like to sort photos by taken date, rather than last modified date, for the same reason : I have different photos, taken by different devices, covering the same event, and I would like to see them all in chronological order.
I'm new to Nextcloud, and I have a fairly limited experience with php, but I figured I could prototype some temporary function using php built-in EXIF support:
```
function getOriginalDate($nd) {
	$filename = $nd->getPath();
	$filebase = $nd->getName();
        if ($filebase == "." or $filebase == ".."){
                return 0;
        }
        if (exif_imagetype($filename)) {
                $exif = exif_read_data($filename, 'EXIF');
                if (is_array($exif) || is_object($exif)) {
                        foreach ($exif as $key => $value) {
                                if ($key == 'DateTimeOriginal') {
                                        return strtotime($value);
                                }
                        }
                }
        }
	return $nd->getMTime();
}
```

and then in photos/lib/Controller/AlbumsController.php:
`'lastmod' => getOriginalDate($node)`

This way, if the photo has EXIF entries I can use them, otherwise use last modified entry.
But sadly it didn't work.
So I tried to force set all modified date to EXIF taken date if available using EXIF-Tool
```
for i in *.JPG;
do
echo Traitement de $i
touch -t `exiftool -s -s -s -d "%Y%m%d%H%M.%S" -DateTimeOriginal $i` $i
echo `exiftool -s -s -s -d "%Y:%m:%d %H:%M:%S" -FileModifyDate $i`
echo ""
done
exit 0
```
But although the code ran, and the files seemed to have been modified, nothing changed when I displayed the album in Nextcloud.

I know the cleanest method would be to handle this server-side but I can't figure out what went wrong with my attempt.
Regards,
J-C

**Comment by frumania** [comment]
> Hi @skjnldsv,
> For me all photos are being displayed in an incorrect order as they all have been modified sometime.
> So changing that line that I mentioned helped me to fix part of the problem, I understand that a File can have a creation date different from the photo that it represents, but that seems to be more uncommon than having a modification date and everything listed by that modification date.

Does this require a "rescan" or should it work out of the box?

**Comment by bugsyb** [comment]
> But although the code ran, and the files seemed to have been modified, nothing changed when I displayed the album in Nextcloud.

@jcclerval , belief is that you'd need to run re-scan at least on that folder where photos are.

The best would be to have your approach implemented, meaning:
a) try to extract EXIF picture taken timestamp (normalize to UTC) and display either at presentation layer translated to local one or use timezone as in EXIF,
b) check if file naming convention doesn't reveal YYYY-MM-DD or something similar (trick is to small amount of files is available, i.e. what means 2020-01-01 - for most of Europeans it would be Jan 1st, but not necessarily for everyone),
c) if nothing of above gives good result, use file timestamp (last resort).

This would need to be stored somewhere in a table, probably together with other EXIF related details, like GPS, etc. 
This opens nice avenue for presentation layer.

**Comment by jcclerval** [comment]
Indeed, I ran a re-scan and now it works 👍  (although it only was the original code with altered last modification date, now I'll try to check the piece of code with non-altered photos)

**Comment by cornzy** [comment]
I think it would be useful to have an option to set cdate of photos to exif DateTimeOriginal and sort photos by cdate. In my opinion, this feature is very important to the photos app as users expect photos to always be sorted by the date they were taken.

**Comment by Zaijo** [comment]
Is anyone working on this already? @skjnldsv @jancborchardt Maybe if there's a PR started I could help.

**Comment by jancborchardt** [comment]
@Zaijo hi, right now no one seems to be working on this – if you want to dig into the code that would be great! @skjnldsv @Mikescops will be able to help with any questions. :)

**Comment by Zaijo** [comment]
OK, how can we communicate about this? Do you have a chat or developer forum somewhere? I need help.

**Comment by Zaijo** [comment]
BTW, there's this application https://github.com/gino0631/nextcloud-metadata which can already extract metadata of many formats. Is there a way to use that? @Mikescops @skjnldsv ?

**Comment by gipadm** [comment]
@Zaijo I am also interested in helping out with this one. Let me know.

**Comment by Zaijo** [comment]
I'm sorry guys but in between I found Photoprism https://docs.photoprism.org/ which I now use alongside with Nextcloud and this EXIF way for Nextcloud Photos seems to have a veeeery long path before it's usable for me.

**Comment by johannestophoj** [comment]
@Zaijo , did you use some guide to install photoprism and set it up with nextcloud. This sync-option looks like it duplicates the image data (?) https://docs.photoprism.org/user-guide/settings/sync/

**Comment by Zaijo** [comment]
Let's move to e.g. Twitter with that so we don't spam this thread. https://twitter.com/zaj0

**Comment by skjnldsv** [comment]
> BTW, there's this application [gino0631/nextcloud-metadata](https://github.com/gino0631/nextcloud-metadata) which can already extract metadata of many formats. Is there a way to use that? @Mikescops @skjnldsv ?

Like mentioned on this thread and others multiple time, this require metadata to be merged and shipper into nextcloud server, available through dav and have a dedicated API for other apps.
Then it would be a few lines of code for the Photos app.

**Comment by Joshua2504** [comment]
Why is this still a thing?

I want to switch to Nextcloud from Google Photos, means I did a full Google Export and uploaded the around 100.000 files to Nextcloud just to figure this out.

When will you change this?

**Comment by jcclerval** [comment]
I reckon it will take some time before it is properly managed server-side. How about some partial temporary feature using PHP built-in EXIF support ? Something similar at what I have written above, but better and at the right place ?

**Comment by skjnldsv** [comment]
No, it must be done right or none at all. Temporary hackish features are what got us in lots of trouble in lots of areas. And then no one maintains it, and it suddenly becomes the bottleneck for any desired changes. :confounded: 

Locking this thread, nothing more productive seems to be added, you are all free to start working on this and I will help you implement it if you do. :+1:

**Comment by jakobroehrl** [comment]
@marcelklehr 
How hard is it to fix this issues when https://github.com/nextcloud/server/pull/30366 will be merged?

**Comment by marcelklehr** [comment]
Shouldn't be too hard, IMHO. One problem is that file creation dates are a relatively recent addition to the linux family so may not always be available...

**Comment by jancborchardt** [comment]
@artonge what do you think about this one regarding feasibility? Would it need EXIF data to be saved or something else as prerequisite?

**Comment by artonge** [comment]
This would need the EXIF data to be saved in the `oc_file_metadata` table. Easy. But this would also need to be able to order files with on a metadata entry. Harder as there is no logic for that yet. I did not event looked at it, so not even sure that is possible, but I hope it is.

**Comment by jancborchardt** [comment]
What’s the current state or feasibility regarding this now that we have the data in the metadata table (right?) – @artonge?

**Comment by szaimen** [comment]
Looks like this would need to be first done by the desktop and other client apps?
See https://github.com/nextcloud/server/pull/30366#issuecomment-1156572519

**Comment by jancborchardt** [comment]
cc @tobiasKaminsky also for the client part as mentioned by @szaimen.

**Comment by tobiasKaminsky** [comment]
> This would need the EXIF data to be saved in the `oc_file_metadata` table.

This is only on server.
On clients there is no reliable way to check/send creation date.

**Comment by artonge** [comment]
> What’s the current state or feasibility regarding this now that we have the data in the metadata table (right?) – @artonge?

I do not think that we have the data yet.

**Comment by szaimen** [comment]
Is this not exttacting the information?

https://github.com/nextcloud/server/blob/6d0dabedd83bce94f43dc0375b110e80af8514f8/lib/private/Metadata/Provider/ExifProvider.php

**Comment by szaimen** [comment]
So I guess we would need to extract the information on server and store it in the metadata table first?
