### ISSUE TITLE
Photo Viewer navigation buttons disappear, leading to unituitive behavior

### ISSUE THREAD

**Issue by haarp** [nextcloud/photos#886]
Hello,

**Describe the bug**
In the photo viewer, there are navigation buttons for e.g. previous/next picture. If there's no mouse movement for 5 seconds, these elements fade out. This leads to unintuitive and downright annoying behavior.

Whenever I flip through pictures while the mouse rests on a nav button, and wait too long looking at a picture, a left click will now close the picture viewer instead of navigating to the next element, as expected.

*IMO, nav elements shouldn't disappear as long as the mouse is hovering over them.*

**To Reproduce**
1. Open picture in photo viewer
2. Place mouse on the "next pic" button
3. Wait for the buttons to fade out
4. Click

**Current behavior**
Picture viewer closes "because you clicked outside the picture"

**Expected behavior**
Next picture appears

**Desktop:**
 - Browser: Firefox 91, but should be irrelevant

Thanks!

**Comment by szaimen** [comment]
Not disappearing anymore
