### ISSUE TITLE
Wrong URL link when using special characters in folder title

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/photos#89]
When naming an album with a question mark for instance "Question ?", the generated url is wrong and the user is redirected to an empty folder.

![image](https://user-images.githubusercontent.com/4266283/71896431-16ef0b00-3154-11ea-9f9a-17361df2a977.png)

The "%3F" is missing in the generated url:
![image](https://user-images.githubusercontent.com/4266283/71896495-3c7c1480-3154-11ea-9779-f5bf24da9d23.png)

@skjnldsv is the automatic redirection when visiting an empty album intended?

**Comment by skjnldsv** [comment]
This is not an empty album, this is an invalid path.
So the redirection is indeed intended :)

I guess it's an issue with the url encode/decode somewhere :)

**Comment by Mikescops** [comment]
This issue is super annoying with the `?` because it is used for the parameters
