### ISSUE TITLE
Add sidebar button on the Navigation

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/photos#9]
Right next to the folder name, show an icon to open the new sidebar

There will be tabs missing as some are not working without the files app (will bugfix after) but the sharing tab should work I think :)
The viewer also needs to be update to work with the new Sidebar https://github.com/nextcloud/viewer/blob/c76f79a4419a5488322a66afa334811b9a12bc55/src/views/Viewer.vue#L569

The new sidebar was implemented here https://github.com/nextcloud/server/pull/15719
the new functions for the sidebar are:
 - `OCA.Files.Sidebar.close()`
 - `OCA.Files.Sidebar.setActiveTab(tabId)`
 - `OCA.Files.Sidebar.open(path)`

**Comment by jakobroehrl** [comment]
This is not working:
OCA.Files.Sidebar.open(this.filename)
Error in v-on handler: "TypeError: Cannot read property 'Sidebar' of undefined"
