### ISSUE TITLE
Photos still shoing pictures outside my Photos folder in the root directory.

### ISSUE THREAD

**Issue by noobscode** [nextcloud/photos#903]
The photo viewer is still showing photos that I have zipped away, photos outside my photos folder. I have executed the file scan job several times and tried adding .nomedia / .noimage filder in directory but it does nothing. same issue on both pc and phone.

**Comment by hobbsecky** [comment]
me too

**Comment by martabal** [comment]
Same...

**Comment by iluvatyr** [comment]
same... needs to be fixed for sure!

**Comment by marcelklehr** [comment]
Support for .nomedia files has landed since.
