### ISSUE TITLE
generate previews of images in a background process

### ISSUE THREAD

**Issue by markuman** [nextcloud/photos#904]
Since https://github.com/nextcloud-outlaws/previewgenerator is orphaned, I'd like to see the functionality to generate previews server-side directly in the `photos` app.  
this is an essential feature when you use nextcloud as a drop-in replacement for google photos for example.

https://github.com/nextcloud/previewgenerator/issues/243

**Comment by umgfoin** [comment]
Previewgenerator is no longer "orphaned" - a new maintainer has been found.
[appinfo/info.xml](https://github.com/nextcloud/previewgenerator/commit/d6e55fb486cda6b9144035fd10f5b72d09d92daa#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9e)
