### ISSUE TITLE
Photos lists items from External storage even with usage of .nomedia and .noimage empty file

### ISSUE THREAD

**Issue by dashbash9787** [nextcloud/photos#908]
**Describe the bug**
Photos lists items from External storage even with usage of .nomedia and .noimage empty file.

2 x SMB External storage

Both root dirs have .nomedia and .noimage

However both list any media files in Photos

Have rescanned both using occ files:scan -all  --path=/USERNAME/files/FOLDERNAME(as listed on External storage page)

**To Reproduce**
1. Connect to External storage using SMB
2. Photos will list items from those dirs ignoring .nomedia and .noimage

**Expected behavior**
Would expect any media in those dirs and below to be ignored.

**Desktop (please complete the following information):**
 - Operating System: Linux 5.10.28-Unraid x86_64
 - Browser: Chrome , Vivaldi
 - Nextcloud 22.2.0

**Comment by hobbsecky** [comment]
this problem is effecting ALL folders that have .nomedia set

**Comment by hobbsecky** [comment]
actually removing this app from my nextcloud servers. I don't see a need for it.

**Comment by marcelklehr** [comment]
support for .nomedia files has landed.
