### ISSUE TITLE
No default thumbnail for video files when preview provider for video files is not enabled

### ISSUE THREAD

**Issue by orandev** [nextcloud/photos#909]
**Describe the bug**
I still have the issue described in https://github.com/nextcloud/photos/issues/854, even after installing Nextcloud 22.2.0, which in theory contains https://github.com/nextcloud/photos/pull/876 which is supposed to fix the issue.
The default thumbnail is not displayed for video files (.mp4), with the Movie or MP4 preview provider disabled.

**To Reproduce**
Do not modify the default NC list of enabled preview providers (i.e. Movie and MP4 preview providers are not enabled)
Upload some .mp4 video files to NC
Open https://server_url/apps/photos/ or https://server_url/apps/photos/videos

**Expected behavior**
I expect to see the default svg image for video files, which we can correctly see when we browse to https://server_url/apps/files (i.e. a "play" icon inside a square)

**Screenshots**
NC 19.0.13 html code (default thumbnail is ok):
![Nextcloud_bug_photos_app_video_previews_NC19_OK](https://user-images.githubusercontent.com/63342732/137111421-63484dfe-eac9-458b-8cf3-aca5597df11c.png)

NC 22.2.0 html code:
![Nextcloud_bug_photos_app_video_previews_NC22 2 0_KO](https://user-images.githubusercontent.com/63342732/137111431-b2ea7c98-9edf-4b13-b578-9f13e4e83199.png)

NC 22.2.0 appearance:
![Nextcloud_bug_photos_app_video_previews_NC22 2 0_KO_appearance](https://user-images.githubusercontent.com/63342732/137111482-d5cb8d4d-dbf0-477a-a967-f3f2a6a6390b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 78.15esr and Edge Chromium

**Browser log**
[photos] Grid config Object { marginTop: 88, marginW: 66, count: 7, gap: 8 }
SW registration failed:  TypeError: ServiceWorker script at https://server_url/apps/photos/service-worker.js for scope https://server_url/ encountered an error during installation. Photos.vue:114

**Additional context**
NC 22.2.0
Photos 1.4.0
PHP 7.4.23
S3 as primary storage

**Comment by skjnldsv** [comment]
> No thumbnails are displayed for the video files (.mp4), not even the default/empty one.

Double check your logs to see if the previews are actually generated. Please also check that you enabled generation for video files

**Comment by iluvatyr** [comment]
yep, is this being fixed at some point?
