### ISSUE TITLE
Add Support for WebP file type

### ISSUE THREAD

**Issue by MrDj200** [nextcloud/photos#932]
**Is your feature request related to a problem? Please describe.**
I wanna save disk space and have all my pictures in .WebP format, but the photo viewer is not showing .WebP files.

**Describe the solution you'd like**
Show .WebP files in Photo viewer (file viewer already has this)

**Describe alternatives you've considered**
Using .png files to use 90% more disk space

**Additional context**
Maybe also consider adding support for WebM videos

**Comment by vladstudio** [comment]
+100. WebP support would be greatly appreciated.

**Comment by killiandt** [comment]
Any news about the webp support?

**Comment by Kitanit** [comment]
> Any news about the webp support?

hmm, I have always had webp open since nc 23

**Comment by marcelklehr** [comment]
This is where the allowed mime types are listed: https://github.com/nextcloud/photos/blob/master/lib/AppInfo/Application.php#L36

**Comment by moritz76** [comment]
Thank you! Now they are displayed. But I can only see that there should be a picture, the real picture is not displayed.
I generally have the problem that .webp images are not displayed in the Nextcloud web interface, but are always downloaded. 
Is there a setting that needs to be made in the viewer app?

**Comment by rriemann** [comment]
Using NC 25, I can see webp files in the files app folder view with preview, but I cannot see them in the photo app folder view nor anywhere else in the photo app.

**Comment by jjisnow** [comment]
+1

**Comment by cloudmaker97** [comment]
Sad that this isn't merged yet by a maintainer because i use webp and webm a lot to save disk space. As workaround i've uncommented the lines for webp and webm under `/apps/photos/lib/AppInfo/Application.php`.
