### ISSUE TITLE
Sending pull requests is a nightmare

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/photos#949]
**Describe the bug**
After every pulled PR all others will have to be rebased, because the build output is checked into the source repository

**To Reproduce**
1. Create pull request
2. Wait for it to be accepted
3. A different pull request is merged
4. Your pull request has merge conflicts

**Expected behavior**
Do not check in build output into git.

**Comment by skjnldsv** [comment]
Yeah, that's how it is for now.
It's a long ongoing discussion, but we currently have no other choices.
You can decide to NOT ship the builds, and usethe compile bot to amendthe assets when it's ready to merge `/compile amend /js`

**Comment by marcelklehr** [comment]
> It's a long ongoing discussion

Could you point me to the discussion? Just curious :)

> /compile amend /js

Ah, that's a slight relieve at least. Thank you. 

PS: Sorry if my tone was a bit off above.

**Comment by skjnldsv** [comment]
No worries, note that I'm 100% onboard.
But the release script does not contain the necessary steps to build each  apps. So we rely on repositories containing the necessary assets.


> Could you point me to the discussion? Just curious :)

It's a mix between talk, irl discussions and internal chats. Surely there are a few tickets about this too. 
One of those is https://github.com/nextcloud/server/issues/27442

**Comment by skjnldsv** [comment]
Oh, btw, you can rebase your work with the rebase bot too :wink:
`/rebase`
