### ISSUE TITLE
Dashboard plugin showing 'on this day' photos preview

### ISSUE THREAD

**Issue by galandilias** [nextcloud/photos#972]
**Is your feature request related to a problem? Please describe.**
As we almost have 'on the day' photos feature next step would be to expose the contents on the dashboard - as this is first landing page of Nextcloud

**Describe the solution you'd like**
On the dashboard I would love to have a widget showing a preview from the 'on the day' view of photos app

**Describe alternatives you've considered**
no other alternatives :)))

**Additional context**
-

**Comment by jakobroehrl** [comment]
YES!
