### ISSUE TITLE
An error has occurred during loading of Photos App

### ISSUE THREAD

**Issue by SaschaMuehl** [nextcloud/photos#997]
**Describe the bug**

**To Reproduce**
1. Go to 'Nextcloud'
2. Click on 'Photos-App'

**Expected behavior**
Loading of all pictures (external and internal)

**Screenshots**![image](https://user-images.githubusercontent.com/62723171/149947141-98829673-c2e6-4b8d-8d21-e2be1e057e5b.png)

**Desktop (please complete the following information):**
 - Browser internet explorer

**Smartphone (please complete the following information):**
 - Device: Galaxy S6 Active
 - Browser samsung browser

**Browser log**
![image](https://user-images.githubusercontent.com/62723171/149948056-8d3a8464-c2cc-4e31-8b85-43a1e1cb5490.png)

**Additional context**
Can anybody tell me why the photos app isn't loading the pics? I use also the thumbnail-generator and recognize (after days the indexing of my 1,8TB pictures are still not finished). 

I use Nextcloud Hub II (23.0.0) behind a reverse proxy on a LEMP-Stack.

**Comment by skjnldsv** [comment]
504 = gateway timeout.
This is a setup issue, your webserver is taking too long. How long are we talking about?
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by SaschaMuehl** [comment]
@skjnldsv, thans for your fast reply. This is the network (XHR) extract: 
![grafik](https://user-images.githubusercontent.com/62723171/149970726-f632eabc-5cad-4377-ab3e-8b9d47c13f87.png)

**Comment by skjnldsv** [comment]
Your setup timeout is too low. It also seems your webserver is taking a long time to reply to such complicated request (60sec is long), so either upgrade your timeouts (see documentation), or upgrade your hardware :)
Probably 1.8TB pictures is reaching the limits of your instance
